### ISSUE TITLE
Room settings: crash when navigating quickly between tabs

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1007]
To reproduce:

1. Open a room, then go in room settings
2. Navigate quickly several times between tabs, especially between files and settings

Crash
I sent a bug report.
My device is a Samsung S3.

**Comment by ylecollen** [comment]
It has been fixed in  https://github.com/vector-im/riot-android/commit/528f864632a78f191972d648c692f3e8a24e04e8

**Comment by jeangb** [comment]
Validated
