### ISSUE TITLE
Support Android 7.0 inline notification replies

### ISSUE THREAD

**Issue by lieuwex** [vector-im/riot-android#1016]
This could be used instead of the current custom quick reply implementation, or maybe use the custom implementation as fallback of some sort on older Android versions.

https://developer.android.com/guide/topics/ui/notifiers/notifications.html#direct

**Comment by bmarty** [comment]
@BillCarsonFr is implementing this! At last! (See WIP: #2880)

**Comment by bmarty** [comment]
Will be merged in February
