### ISSUE TITLE
[Registration] : Re-open the MSISDN token dialog if the previous entered one was invalid

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1029]
Steps to reproduce
1- create a new account with a MSISDN
2- when the MSDISN token dialog is opened, write an invalid token

Currently, there is a toast with the error reason (invalid token) but there is no way to write the valid one because the dialog is closed. The user has to trigger a new registration request

**Comment by sabrinaj** [comment]
Not reproduced
