### ISSUE TITLE
The image / video thumbnails should be larger

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#103]
The image / video thumbnails should fill the screen width.

**Comment by ylecollen** [comment]
The android client has been updated to have the same attachments thumbnails size as the IOS client.
It is really larger.

But it does not follow the expected design but it was a quite fast improvement.

**Comment by ylecollen** [comment]
Move to P3 because it is better even if not perfect.

**Comment by bmarty** [comment]
Nothing more will be done here
