### ISSUE TITLE
[Registration] : the SKIP button should be disabled if there is an email and/or a MSISDN

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1030]
In the second registration activities, the user could add an email and/or a MSISDN.
There are two buttons SKIP and REGISTER.

The REGISTER button should be disabled if there no valid email address and/or MSISDN.
THE SKIP button should be disabled if there are some valid items

**Comment by sabrinaj** [comment]
Behavior same as iOS.
