### ISSUE TITLE
Riot Android requires having power (level 50?) for adding local aliases

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-android#1033]
This requirement isn't in Riot Desktop and would be helpful with the issue where rooms show no aliases (I am not sure if there is an issue for it at Synapse at the moment).

I am on Google Play Store version 0.6.8 (8f1140d).

**Comment by Matrixcoffee** [comment]
ISTR that Synapse was changed so that any user can add local aliases to a room. The webclient has been updated with this new behaviour, but the Android client so far has not.

Should be an easy fix (remove the permission check).

**Comment by Matrixcoffee** [comment]
Is this a P2 or a P3 issue?

**Comment by bmarty** [comment]
Ok, fixed
