### ISSUE TITLE
Display local notifications from /sync rather than relying on body of GCM notification

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1047]
This is the Android equivalent of https://github.com/vector-im/riot-ios/issues/188, which is the client-side of https://github.com/matrix-org/synapse/issues/1540.  We should not be leaking message bodies in plaintext to Google.

**Comment by ylecollen** [comment]
It is already done.
The body is only used if the user disabled the background sync.
Thus, the e2e messages are properly notified.

**Comment by travisghansen** [comment]
@ylecollen I'm unclear if non e2e messages are being sent to their respective push services?

**Comment by ara4n** [comment]
https://github.com/matrix-org/synapse/issues/1540 is the bug tracking that bit.
