### ISSUE TITLE
Better handling of notifications for multiple rooms

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-android#1049]
This morning, when I turned on my phone (is always in airplane mode at night), I recieved a GCM notification for Riot. I clicked on it and was directly taken to a room where several new messages had arrived over night.

There was a new message in another room, too, however, a direct chat, which I didn't notice because I was directly taken to that other room. Only when I switched back to the room list because I wanted to write something an hour later, I noticed that another (much more important) message had been waiting for me.

An easy improvement would be that clicking on the notification would lead to the room list if notifications for more than one room are pending. For large room lists, though, this won't make things much better.

How could a UI look like that makes clear that there are new messages waiting in other rooms?

**Comment by Matrixcoffee** [comment]
It would be good if the notification widget remembered *all* the notifications (or the *n* most recent ones), and sort more important notifications to the top.

For example, look at how the clipstack behaves for multiple entries:

![Clipstack notification collapsed](https://raw.githubusercontent.com/Matrixcoffee/todo/issue-screenshots/SS20170321094509_Notification-collapsed.png)

And after dragging down, it opens up to:

![Clipstack notification expanded](https://raw.githubusercontent.com/Matrixcoffee/todo/issue-screenshots/SS20170321094523_Notification-expanded.png)

Tapping on the collapsed Riot notification (or the notification header, when expanded) could open a scrollable view of all notifications, before going to the rooms list. If there is only one notification, it should go directly to the room as before.

**Comment by bmarty** [comment]
Done in Riot 0.8.26
