### ISSUE TITLE
Forgot password: 'I have verified my mail' button is missing

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1053]
To reproduce:
1. From login screen, hit forgot password button
2. Complete form with a valid mail and matching passwords. In this case, verification is done by checking the mail on your desktop.

On the following screen, the button 'I have verified my email address' is missing.
Keyboard stay opened. The button isn't hidden by the keyboard.
![missing verified mail button](https://cloud.githubusercontent.com/assets/22364949/24158887/df4b815e-0e5d-11e7-982a-cd00f40027af.jpeg)

**Comment by jeangb** [comment]
After the correction:
When I click on the button without having actually verified the mail, I have this screen:
![not verified mail](https://cloud.githubusercontent.com/assets/22364949/24253807/90649bd6-0fe1-11e7-9107-c5c868b06f93.jpeg)
The expected comportment is to stay in the same screen until user click on the link in his mailbox.

**Comment by sabrinaj** [comment]
Fixed on `develop` branch.

**Comment by jeangb** [comment]
Validated
