### ISSUE TITLE
Too long time to response for wrong account or password when login

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-android#1059]
When login, input wrong account or passward, then click the log in button, it need too long time to give result, and no error notification.

**Comment by ylecollen** [comment]
Do you have a good network connection ? 
Do you use your custom home server ?
We don't have such behaviour on our side.

**Comment by wjhtinger** [comment]
Find the cause, close the issue.

**Comment by udee297** [comment]
what the cause? @wjhtinger
