### ISSUE TITLE
use available width 

### ISSUE THREAD

**Issue by derWalter** [vector-im/riot-android#1068]
if I fold the left and right panels in, there still is a lot of space on the left and right side, which is not used at all. in case the area for showing the chat stream would expand till next to the edge, a lot of line wraps would be saved and i would see more information on screen and i had less to scroll.

especially important on devices with low resolution (!)

**Comment by ylecollen** [comment]
@derWalter 
Could you post here a screenshot with some drawings (it is often more understandable than words)

**Comment by MilkManzJourDaddy** [comment]
Hmmm...  "left and right panels"...

Are you sure you're not talking about Riot-Web?  Or another client besides Riot-Android?  

What you typed makes sense for Riot-Web.  But I don't see that on Riot-'droid.  And, this is the issue tracker for Riot-Android.

**Comment by sabrinaj** [comment]
That issue is most likely about riot-web so I close
