### ISSUE TITLE
Default to single-line chat messages

### ISSUE THREAD

**Issue by inducer** [vector-im/riot-android#1070]
By default, the bottom-right key on the software keyboard inserts a newline. IMO, that's not as useful, because (in my world) multi-line chat messages are somewhat rare, but chat messages with emoji (the button relegated to being behind long-press as it stands) are frequent. I'm writing to request relegating the newline button to the behind-long-press role.

**Comment by MilkManzJourDaddy** [comment]
Certainly in a world where all messages consist of a series of "wut lol" messages, yeah.  

But there are many different groups who use Matrix-Riot, some who are have serious, scientific, and literary backgrounds.  Not all are drinkers of Brawndo.  They are aware of a concept that evolved over thousands of years in language, and that even Markdown like CommonMark holds; the Paragraph.  

There is talk of bringing "threaded" messaging to Matrix, like Reddit.  And those, most definitely have "multi-line" paragraphs.  

You know, not all devices seem to have this long-press to pop up emojiis, and you have to search for old-school emoticon keys.

For this sub-set, app's like Conversations for XMPP, there is an option to swap the \<enter\> key "↵" for a \<send\> key, or "Enter is send", "show enter key"/"change the emoticons/emojii key to an enter key", et cetera.  

But, one can use an alternate keyboard app' like the Hacker's Keyboard, on F-Droid.  The rest of us, while on Desktop, will still do \<shift\>+\<enter\> to "multi-line", and look for a way to make that default.  

Now if you talk about constricting the area of the send key, enclosing it in a bordered-box, with a clearly defined border that only is the area of the send-arrow, and that uses contrasting colors, distinguished from the text-box...  NOW we're talking.  IDK how many times I've accidentally sent, when trying to press/drag-edit, in the text box.

**Comment by PaulFreund** [comment]
I think offering users a way to customize the default behaviour is a good idea most of the time. Depicting other ways of communication as stupid seems rather rude to me. I can imagine the enough users would benefit from this to justify an additional option 👍

**Comment by bmarty** [comment]
Fixed by #3019
