### ISSUE TITLE
Highlight phone numbers, email addresses, etc.

### ISSUE THREAD

**Issue by fegul** [vector-im/riot-android#1077]
When sending messages, I noticed that Riot doesn't make phone numbers clickable. Is it possible to leverage [Linkify](https://developer.android.com/reference/android/text/util/Linkify.html) to make this possible?

It would make a life a lot simpler when sending contact information to other Riot users if they could just click on the specific parts of the message with the details (similar to how if you receive an SMS with a phone number in it, it automatically highlights it like a link and opens up the dialer if you press on it)

**Comment by jeangb** [comment]
Validated in 0.6.10-dev (639650f)
