### ISSUE TITLE
The message sent with QuickReply is not added to the room history if the dedicated room activity is opened

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1080]
Steps to reproduce
1 -Open a room 
2- put the application in background
3- receive a message in the opened room
4- Enter a quick replay from the notification
5- Debackground the application

The sent message is not displayed. It is only displayed if the room activity is opened again.

**Comment by ylecollen** [comment]
@krombel 
It is the issue you describe in the unknown devices PR.

**Comment by krombel** [comment]
Good you found the issue :)
The procedure taken is the same as describes above.
So a fix for that should fix my issue as well 😎

**Comment by jeangb** [comment]
Validated in 0.6.10-dev (3bd86cc)
