### ISSUE TITLE
Add option to terminate the app and listener in a clean way

### ISSUE THREAD

**Issue by vbrandl** [vector-im/riot-android#1087]
Since I have an old mobile phone and riot uses lots of power when running, I often want to terminate the app and the listener process to safe some power. Since the app doesn't have a way to quit in a clean way, I always need to kill the process. I think it would be great to have a button that shuts down the listener and termiates the app

**Comment by wincak** [comment]
Any news? This is especially an issue for F-Droid version where polling for messages eats more battery. Having a quit button instead of killing the application each time would be a significant improvement in user experience.

**Comment by Matrixcoffee** [comment]
I believe this is implemented as per #1955.

**Comment by wincak** [comment]
It looks that way! But It will take some time before I can test and confirm it, F-Droid in still on version 0.7.03 (from October) :(

**Comment by bmarty** [comment]
"Exit" in the main menu has been implemented
