### ISSUE TITLE
Room topic in #android:matrix.org is outdated, contains dead link

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#1091]
The room topic is out of date and needs some thoughtful attention. The last update predates the name change from Vector to Riot.

Most especially, the link to https://matrix.org/blog/project/matrix-console-android is dead (404).

**Comment by mnemonicflow** [comment]
Working link: https://matrix.org/docs/projects/client/matrix-console-android.html

**Comment by vurpo** [comment]
>Working link: https://matrix.org/docs/projects/client/matrix-console-android.html

Shouldn't the link to Matrix Console be replaced with a link to Riot anyway, instead of just being replaced with an up-to-date link?

**Comment by Matrixcoffee** [comment]
Most likely.
