### ISSUE TITLE
New direct conversations created under "Rooms" instead of "People"

### ISSUE THREAD

**Issue by moritzheiber** [vector-im/riot-android#1102]
I'm not really sure if this is a bug, or just a UX difference.

When using Riot online or on my desktop I have two distinct categories of chats:

- People
- Rooms

People are one on one conversations I have with a single user. Rooms are conversations I have with >1 users. When I initiate a one-on-one conversation on Riot web/desktop it's "properly" shown under the "People" category.

Using Riot for Android however, every new conversation is a room that's created, and it's also showing up under the "Room" category, especially on web/desktop.

Now I know, "people" category conversations are technically probably just a fancy way of saying "this is a room with just two people in it", but the different categorization is useful and helps sort out larger room directories.

On Android there is no such distinction at all, everything is a room. New one-on-one conversations are always created as rooms. And they show up under the "Rooms" category on web/desktop.

My expectation would be:

1. Conversations under the "People" category on web/desktop are also showing up under a "People" category on Android
2. Newly created conversations, initiated by the Android client, are sorted in the "People" category

Let me know if this makes sense, or whether that's a unique design choice the web/desktop people went after, or even whether this is a design consideration you've already made up your mind about. For me, it was too large a design disparity to not write an issue about :blush:

**Comment by ylecollen** [comment]
It is the expected behaviour on the mobile clients.
We plan to have a new UI later to make the difference.
