### ISSUE TITLE
failed upload restarts in loop

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1120]
Vurpo reported that an upload which failed started again the upload in loop.

It should stop after the first failure.

**Comment by ylecollen** [comment]
from his logs
04-12 14:10:18.892 205993 D/MXMediaUploadWorkerTask: doInBackground : totalWritten 180191 / totalSize 180191
04-12 14:10:18.905 205985 E/MXMediaUploadWorkerTask: doInBackground ; failed with error class java.net.ProtocolException - unexpected end of stream

The upload started again 2 seconds later.

**Comment by ara4n** [comment]
People seem to be reporting this more and more - e.g. https://github.com/matrix-org/riot-android-rageshakes/issues/3011.

**Comment by bmarty** [comment]
From Rageshake log:

```
08-27 21:13:22.550 23164 27144 E MXMediaUploadWorkerTask: MXMediaUploadWorkerTask mark/reset not supported
08-27 21:13:22.550 23164 27144 E MXMediaUploadWorkerTask: java.io.IOException: mark/reset not supported
08-27 21:13:22.550 23164 27144 E MXMediaUploadWorkerTask: 	at java.io.InputStream.reset(InputStream.java:348)
08-27 21:13:22.550 23164 27144 E MXMediaUploadWorkerTask: 	at org.matrix.androidsdk.db.MXMediaUploadWorkerTask.<init>(MXMediaUploadWorkerTask.java:178)
```

**Comment by bmarty** [comment]
This two issues has been fixed
