### ISSUE TITLE
Room name calculation doesn't match riot-web

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-android#1124]
I'm in a room with a couple friends (and several bots). On riot-web the room name is "Ayeso and 5 others", however on riot-android (v0.6.9-1866137) the room name is "Giphy and 5 others".

The spec for the room name is here: http://matrix.org/docs/spec/client_server/r0.2.0.html#calculating-the-display-name-for-a-room

(send me a message on Matrix (`@travis:t2l.io`) for the room member list)

riot-web:
![image](https://cloud.githubusercontent.com/assets/1190097/25022026/9536a246-2051-11e7-900b-52a81fe4ce53.png)

riot-android:
![image](https://cloud.githubusercontent.com/assets/1190097/25022168/26f86cbe-2052-11e7-88a9-ea9bbae221d4.png)

Other members of the room are seeing "TravisR and 5 others" despite there being someone with characters before mine. This bug is specific to the room name being different from riot-web, although riot-web also gets the name wrong, apparently (more investigation required).

**Comment by bmarty** [comment]
This should be fixed by work done on LazyLoading on Room members
