### ISSUE TITLE
show only active and idle members

### ISSUE THREAD

**Issue by krihsna** [vector-im/riot-android#1131]
in room details, please show only active and idle members.

please remove or don't show offline members.

**Comment by ylecollen** [comment]
they are already sorted by presence.

**Comment by krihsna** [comment]
please excuse, i should have provided screenshot and better reasoning.

the members list seems to be sorted in hours, there is an idle member between offline.

example: if there are hundreds of members, the person is idle, i cannot scroll down indefinitely. if i search for people, it does not show in which room or channel person is idle.

screenshot from mozilla nightly channel:

![tmp_9039-riot1521031958](https://cloud.githubusercontent.com/assets/22496610/25302466/5ebf4e5e-275c-11e7-8673-c6545079f439.png)
