### ISSUE TITLE
Numbers are too much linkified

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1140]
To reproduce:

1. Numbers are linkified in strings like this in a room:
- qq3333qq
- 3333
![yzfjsjbyvuxmrldhfxeexccp](https://cloud.githubusercontent.com/assets/22364949/25142045/da65f80e-2465-11e7-91f4-e951f9479373.jpg)

Numbers are linkified as soons as there is at least 4 of them. I don't think it's necessary to linkify numbers in such strings, more if these numbers are surounded with letters. iOS and web don't do that.
I think it dates from https://github.com/vector-im/riot-android/issues/1077.

Plus it can lead to visuals like theses in search layouts: 
![hnftutpizuskpaschdhufpfe](https://cloud.githubusercontent.com/assets/22364949/25142063/e7e06000-2465-11e7-9814-60d158f42f14.jpg)
![zvcgctaskelluphbdxdihqzq](https://cloud.githubusercontent.com/assets/22364949/25142069/ecc9ca66-2465-11e7-8186-7ca4e8eabbda.jpg)

**Comment by BillCarsonFr** [comment]
FTR, this happens on older android devices (i have it on kitkat but not on N)
