### ISSUE TITLE
Mobile number not receiving verification token

### ISSUE THREAD

**Issue by balogic** [vector-im/riot-android#1143]
I recently installed `riot-android` from **Play Store** and when I tried to enter my number for registering I did not receive any verification token to my mobile number. I can't verify my mobile without the token. Need help.

**Comment by ylecollen** [comment]
Could you tell us which country is it ?

You can also create an account without phone number and add it later.

**Comment by balogic** [comment]
@ylecollen The country is **India +91** and I created my account with my email ID and after creation also I tried to add my mobile number and I didn't get the verification token there too.

**Comment by ylecollen** [comment]
Could you send a bug report ?
i will have more details to provide to the server team.

thank you

**Comment by balogic** [comment]
Now I got the verification code. I tried yesterday and I didn't get it. May be some server issues yesterday. Now I have added my mobile number and verified it. Thank you for the help. This issue can be closed.
