### ISSUE TITLE
Cannot login when the device language is set to turkish

### ISSUE THREAD

**Issue by fatih-asici** [vector-im/riot-android#1148]
I am able to login using riot web and tensor. But Riot Android gives this error: "invalid username/password". I have installed the application from F-droid. I am sure that the username/password is correct.

Similarly, cannot login with Matrix Console application either. It crashes after pressing login button.

**Comment by ylecollen** [comment]
Do you have your own homeserver ?

**Comment by fatih-asici** [comment]
I am trying to connect to matrix.org. I didn't paste the username/password. I have also tried a simpler password. The result is same; but I have just changed my phone's language setting from Turkish to English. It works now.
