### ISSUE TITLE
Start app at boot

### ISSUE THREAD

**Issue by rodrigoaguilera** [vector-im/riot-android#1152]
I just started using the f-droid build of riot and I'm probably missing something but I am not able to start the app when the devices boots up.

Am I missing something or should I start manually the app everytime?

**Comment by ylecollen** [comment]
we have a PR to start the application at device launch (it is not yet merged).

By default, you will have to launch it manually.

**Comment by rodrigoaguilera** [comment]
Sorry I didn't search for the right keywords nor the PRs.
Thank you!

**Comment by seanf** [comment]
For anyone else who was wondering, it looks like the PR was https://github.com/vector-im/riot-android/pull/838 but it was superseded when https://github.com/vector-im/riot-android/commit/2ea7205195de12899572766d5d401294e0598fc1 was merged (although I don't know where the "Start on boot" option is hiding in the settings).

**Comment by Matrixcoffee** [comment]
"Start on Boot" is only visible in the F-Droid flavour. The Google flavour is automatically started by FCM when a push is received.

**Comment by seanf** [comment]
Thanks @Matrixcoffee I must be having some problem with Xiaomi MIUI's permissions then. It offers a lot of control, but sometimes it's incredibly hard to find all the settings.
