### ISSUE TITLE
Stopped notifications. Then. Loading Forever. 

### ISSUE THREAD

**Issue by ranmaru90** [vector-im/riot-android#1153]
The client from Google Play runs for a while on Samsung Galaxy Note 4 with Android 6.0. But leaving the app, after a while I stopped receiving notifications. When I run the app again I realized that there is an ongoing notification that says "Listening for events".

**Comment by ranmaru90** [comment]
I realized that after connecting to wifi, all that suddenly stopped and riot.im was working as usual again. How much bandwidth does Riot.im need to stay stably connected and send/receive messages? 

Could it really be just a bad network connection? I wonder about this because before I connected to wifi I could send messages through Facebook Messenger and WhatApp, but not riot.im.

**Comment by ylecollen** [comment]
"Listening for events" means that the GCM registration failed : it is the fallback mode.

It might happen when there is a bad network connection or a server issue.
Open the application again triggers another GCM registration if it failed.

Without a bug report, i cannot tell what was wrong.
