### ISSUE TITLE
Auto correction does not work for all keyboards

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#1160]
When typing in a message the badge for autocorrection does not get showed.
Although when typing a search string the badge gets showed

[RW](https://matrix.to/#/@cAkwNLHysr:matrix.org) mentions [here](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$14928790041072239XVuUq:matrix.org) and [here](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$1493134079229414Wwlmj:matrix.org) that the same behaviour exists on AnySoftKeyboard as well

#### My Environment
Android 5.1 with default keyboard (Moto G)

[Here a Link](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$1492859925177flqfE:msgs.tk) to the depending chat in riot-android

#### Screenshots
- WhatsApp how it is expected in Riot Android as well
![image](https://cloud.githubusercontent.com/assets/11167142/25393672/62041824-29dc-11e7-8c59-a7991775cdba.png)

- Riot Android - how it get showed to me
![image](https://cloud.githubusercontent.com/assets/11167142/25393721/8232f87c-29dc-11e7-9b7f-3b21c1104906.png)

**Comment by Matrixcoffee** [comment]
So the question is, what is inputType in Riot in the first place? And does it make sense to explicitly set inputType=textAutoCorrect?

What does the Android dev guide say on it?

**Comment by ylecollen** [comment]
It has been fixed on the latest develop.
