### ISSUE TITLE
F-Droid build asks for GCM/FCM permissions

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#1175]
Screenshot: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%24149337929862392RHisK:matrix.org
![hkzzgefqmhkvemrsznwjtgrj](https://cloud.githubusercontent.com/assets/21172059/26003607/b5c25df6-3722-11e7-93b7-95267c954dc4.jpeg)

**Comment by ylecollen** [comment]
Weird, only the google play version manifest was updated.

**Comment by ArchangeGabriel** [comment]
Hum, not sure “Receive data from the Internet” has anything to do with GCM/FCM.

**Comment by Matrixcoffee** [comment]
@ylecollen: Does the new build server correctly apply the F-Droid build manifest?

@archangeDaniel: This is not the regular "Full Internet access" permission. Android has weird descriptions for some of its permissions :/

**Comment by ylecollen** [comment]
It should be fixed by now.

 apply plugin: 'com.google.gms.google-services' add c2dm permissions without modifying the manifest files.
