### ISSUE TITLE
UX Rework: Move the filter option in the screen header

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#1198]
- remove the label in the header
- replace it with a search field (which corresponds to the current filter field).
- have a placeholder text in the search field which is helping the user understand in which screen they are.
Home: 'Search for rooms',
Favourites:  'Search for favourites',
People:  'Search for people',
Rooms: 'Search for rooms'

- move the current search icon in the menu with the label Search.

**Comment by jeangb** [comment]
### Test automation
- [ ] Test search filed text on the 4 tabs
Old search is already covered in tests by mobilestests_android.RiotSearchTests
