### ISSUE TITLE
Contact picker: opaque calc above the keyboard

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1221]
To reproduce:

1. Open the contact picker
2. Fill the filter with some text
3. Erase it **without** using the x button in the filter bar

There is some kind of opaque calc just above the keyboard:
![opaque calc on contact picker](https://cloud.githubusercontent.com/assets/22364949/26049330/e19f7190-395a-11e7-941f-96bc2671d049.jpg)

**Comment by sabrinaj** [comment]
Should be fixed on ux_rework branch

**Comment by jeangb** [comment]
Validated in 0.6.10-dev
