### ISSUE TITLE
Allow invite notification to be removed if cannot reject/accept (server unreachable)

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#1223]
Currently, if an invitation cannot be accepted or rejected because the server hosting the room is unreachable, the notification cannot be removed permanently thus "spams" the notification panel of the device everytime Riot app restarts. 

Maybe the notification for an invitation could be displayed only once or a third option "Ignore" could hide the invitation from the app/notifications.

**Comment by Matrixcoffee** [comment]
I believe this is now fixed in Synapse, such that the rejection is stored locally if necessary.

https://github.com/matrix-org/synapse/issues?utf8=%E2%9C%93&q=label%3Astuck-invite

Adding this to the client would be duplicate work.

**Comment by richvdh** [comment]
As @Matrixcoffee says, I think this got fixed on the server side.
