### ISSUE TITLE
Login page: when changing homeserver URL to a good one, login button is still unabled

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1227]
To reproduce:

1. Launch Riot with the login page opened and a unreachable home server url setted up
2. Hit custom server option checkbox ON
Wait that progress bar is cleared. Login button is disabled.

3. Change the home server URL to a good one.

LOG IN button is still disabled. 
User have to tap an other field to trigger the verification of the homeserver. I'm not sure this is really a clear step for him.

Note for automated test: delete workaround for this if needed.

**Comment by bmarty** [comment]
Fixed
