### ISSUE TITLE
Membership Event List Summaries (ie collapsing consecutive membership changed)

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1236]
now we have FN membership syncing this is getting really important, as fun as it is to scroll through hundreds of joins/parts

**Comment by devnoname120** [comment]
Duplicate? https://github.com/vector-im/riot-android/issues/332

**Comment by ArchangeGabriel** [comment]
@devnoname120 Yes indeed. I knew I had seen this before. ;)

**Comment by sabrinaj** [comment]
Another related issue: #1038

**Comment by sabrinaj** [comment]
See https://github.com/vector-im/riot-meta/issues/20
