### ISSUE TITLE
Suppress Join and Leave messages

### ISSUE THREAD

**Issue by gbraad** [vector-im/riot-android#1238]
It would be great to suppress join and leave messages

**Comment by gbraad** [comment]
https://github.com/matrix-org/matrix-appservice-irc/issues/443

**Comment by ArchangeGabriel** [comment]
I think a great enhancement would be https://github.com/vector-im/riot-android/issues/1236. I’m not in favour of removing them altogether, but collapsing like it’s done in riot-web/desktop would be nice.

**Comment by Matrixcoffee** [comment]
Dup #1038

**Comment by sabrinaj** [comment]
See https://github.com/vector-im/riot-meta/issues/20
