### ISSUE TITLE
Email addition failed

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1251]
reported by @joaomorenorf:matrix.org

I tried to add a new email and it didnt added. 
I clicked in the link but the app didnt changed anything 

https://github.com/matrix-org/riot-android-rageshakes/issues/166

**Comment by ylecollen** [comment]
i don't reproduce this issue even if i open the email address with a web browser or with Riot.

**Comment by sabrinaj** [comment]
It would be nice to know whether it happened during registration or when adding an email from the settings.

**Comment by joaomorenorf** [comment]
I was doing something wrong, now it's working, thaks.
You can close the issue.
