### ISSUE TITLE
Formatted message rendering is incorrect on S4/Android 4.4

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#1255]
Occured on S4 mini/Android 4.4.2.

The message is cropped or a word wrap is added. Most likely a markdown issue.

![device-2017-05-30-161105](https://cloud.githubusercontent.com/assets/8929916/26587861/e32bbf5a-4553-11e7-95f0-15703258a484.png)

**Comment by jeangb** [comment]
@sabrinaj I'm not sure how to test that, what was the text ?

**Comment by sabrinaj** [comment]
It was just something like that : 

> - A
> b
> c
> d
> ...
> y
> z
> - B

i.e. a message starting by "- " + anything

**Comment by jeangb** [comment]
Validated
