### ISSUE TITLE
Forgot password: sending the form with fake mail redirects to login page

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1266]
To reproduce:

1. Open forgot password form
2. Enters a non existing mail
3. fill the password fields with identical and valid password
4. Hit SEND RESET EMAIL

The forgot password form is closed, and users is in front of login form.
The forgot password shouldn't be closed.

**Comment by sabrinaj** [comment]
Fixed on `develop` branch.

**Comment by jeangb** [comment]
Validated.
