### ISSUE TITLE
Key exchange is not user friendly or very well documented

### ISSUE THREAD

**Issue by bkerensa** [vector-im/riot-android#1271]
It is unclear how to send or share keys in Riot while other apps like Signal and Telegram make key exchange a lot more user friendly.

I am in a few groups that are considering leaving Riot because we have users complaint they cannot see messages and get this instead:
** Unable to decrypt: The sender's device has not sent us the keys for this message. **

It is unclear how those users can share their keys and this results in only some seeing messages.

Your help page and the app gives no indication how to send a key to another user and there is no way to request keys? Key exchange should be automatic like Telegram and Signal!

**Comment by richvdh** [comment]
@bkerensa: thanks for the report. In general, "** Unable to decrypt: The sender's device has not sent us the keys for this message. **" is a sign of something going wrong, though there are a few situations in which it is expected (notably when the message is sent before you signed in on your device, or before you joined the room).

See https://github.com/vector-im/riot-web/issues/2996 for a summary of the situation here. Please do send bug-reports from the app to help us work through the situations where it doesn't work.
