### ISSUE TITLE
With an external keyboard (on Android), there's no way to send a message using only the keyboard. Ctrl-enter does nothing, enter and shift-enter both break line.

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1279]
reported by @lalomartins:matrix.org

**Comment by lalomartins** [comment]
I'm watching this, so if whoever writes a PR needs a tester, ping me.

**Comment by Matrixcoffee** [comment]
Too bad I'm only allowed to leave one thumb.

Have keyboard. Will test.

**Comment by sbts** [comment]
This is definitely a duplicate of #220 can someone mark it as such please
