### ISSUE TITLE
No Indian phone numbers accepted while signing up

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1282]
reported by @darthrider678:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/243

**Comment by ylecollen** [comment]
The indian phone numbers are not yet supported server side.

For example, +91 751 320 0000 does not work.

**Comment by sabrinaj** [comment]
They should be considered valid by the `libphonenumber` library tho. 
I filled an issue on the github page of the library.

**Comment by ylecollen** [comment]
It is not a libphonenumber issue but the matrix severs don't support the indian phonenumbers

**Comment by ylecollen** [comment]
Not an android issue
