### ISSUE TITLE
Please disable push notifications while the desktop client is in active use.

### ISSUE THREAD

**Issue by gibbousmoon100** [vector-im/riot-android#1283]
To reproduce the issue:
1. Open the Windows client.
2. Install the Android client.  Leave notifications enabled.
3. Use the Windows client to chat.  The android app will continue to push notifications through every time a friend sends a message.

**Comment by ylecollen** [comment]
It should already work i.e the notifications should not be triggered if the room is opened in the web client and the user is moving his/her mouse.

If the room is not opened on the webclient, the android client will trigger notifications because no read receipt will ne sent.

Could you tell us if the notified room is opened on the webclient ?

**Comment by gibbousmoon100** [comment]
No, it is not opened in the web client.  It is opened in the Windows desktop client.

Sorry, I thought that was clear by my description of step 1 ("Open the Windows client.").  I will edit the subject title now, to make it more specific.

**Comment by ylecollen** [comment]
i 'm afraid we have no way to detect if another client is opening a dedicated room.

You would have the same behaviour on any client (mobiles or not).
ie the notifications will be triggered  and dismissed asap the dedicated read receipts are received.

**Comment by ylecollen** [comment]
i've tested the behaviour with 3 other clients (android, IOS and a webclient)

**Comment by tliron** [comment]
This has nothing to do with dedicated rooms.

We are talking about a situation when the desktop client is opened in a room. We expect that in this case the Android/iOS clients would not be emitting notifications for every new message. Unfortunately, this is what happens. It's very annoying -- I've had several people consider disabling all Riot notifications on their phones, or even uninstall the app completely. Why chatting on your desktop, you really don't want your phone to keep buzzing.

The solution should not be about the desktop app sending read receipts before other apps -- I understand that's impossible. Instead, the desktop app should lock the room -- or possibly *all* rooms -- while it's being used.

**Comment by mdorn** [comment]
I can confirm the behavior reported by @gibbousmoon100 on the desktop client running on macOS and the mobile client on iPhone.  I receive notifications on my phone regardless of whether the client is open on my desktop with a particular room active.

Moreover (and perhaps best reported elsewhere), I've turned notifications for "Messages in group chats" completely off in my settings and I receive a notification on my phone for every message posted in the room regardless of whether I'm mentioned.

**Comment by ara4n** [comment]
This is mainly tracked at https://github.com/vector-im/riot-web/issues/469.  Agreed that it sucks, and we need to fix it.

**Comment by ylecollen** [comment]
Close in favor of vector-im/riot-web#469.
