### ISSUE TITLE
"Forgot password" flow breaks badly for users with Android installed

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1290]
> Richvdh
so... prompted by the email, hilary is valiantly trying to reconnect to riot
she has the app on her phone, but can't remember her password
she clicks 'forgot password' on the app, gives her email address and new passwords, and gets the email validation by email
she follows the link, and chooses to open it in the app, which then takes her through a captcha (!) and then wedges at a spinner
needless to say this is an unsatisfactory experience :/
rageshaking doesn't seem to work

Sounds like the app incorrectly handles email validation links, at least for the flow of 'forgot password' :(

**Comment by jeangb** [comment]
Validated
