### ISSUE TITLE
don't receive anymore notifications after updating to the 0.6.10 version

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1291]
Reported by @zottel:matrix.zottel.net
https://github.com/matrix-org/riot-android-rageshakes/issues/259

**Comment by ylecollen** [comment]
P2 because i don't reproduce it

**Comment by ylecollen** [comment]
The GCM/FCM events were received but the caught up events did trigger notifications.

**Comment by zzottel** [comment]
Happened on three devices on the same wifi network, did not happen on at least two other devices that use the same HS.

**Comment by ylecollen** [comment]
There is one case i could think : 
At application launch, the client performs a request to retrieve the notification rules.
If they are retrieved, the client does not trigger notifications.

An application cache forces the bing rules retrieval.

**Comment by ylecollen** [comment]
i have added more logs to track why the events could have been unnotified.

-> log the number of notification rules
-> tells if a message is a message is not notified because of a rule or if it is too old.

**Comment by ylecollen** [comment]
fixed in https://github.com/matrix-org/matrix-android-sdk/commit/d9d0e83e08a00d2f93e2e4b6ff94344bf72580b3
