### ISSUE TITLE
No more room after updating the application on 0.6.10 and killing it during the loading

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1292]
Steps to reproduce 
1- install the 0.6.9
2- update to 0.6.10 : the loading wheel is displayed for a long time
3- kill the application during the loading time

at next application launch, there is no more room because the initial sync was not started again.

**Comment by Valodim** [comment]
This can be fixed by clicking "clear cache" in the settings. Interestingly, clearing the cache and then killing the initial sync process does *not* reproduce this issue!

**Comment by ylecollen** [comment]
i assume there is a missing use case.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/260

**Comment by Valodim** [comment]
This actually happened to me again almost the same way after an update I think two days ago. I had sent a rageshake about that, too.

**Comment by Valodim** [comment]
nvm, got a new update just now, and it's fixed alright! :+1:
