### ISSUE TITLE
UX Redesign: Search should be case insensitive

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-android#1298]
It's particularly annoying on mobile to have to capitalize everything. I should be able to search for "ents" and see rooms for "ENTS", "ENTS: Metalworking", "ENTS: Board", etc.

**Comment by turt2live** [comment]
This has been fixed since reporting.

**Comment by Matrixcoffee** [comment]
Have a commit ID by any chance?

**Comment by turt2live** [comment]
@Matrixcoffee I don't. It was fixed between build 102 and 104.

**Comment by Matrixcoffee** [comment]
So one of:
8c6118f748fccab880edf6cccddb482373fa199b (102)
bd2f6bae72bee7aa30ff0a54d3d915934e6bd6ad (103)
96cf328cb5ee8ab571c50941a55cd75cb73e82a8 (104)
