### ISSUE TITLE
E2E new devices dialog disappears if screen is turned off by timeout : it does not reappear at next sent event

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1308]
reported by @aesgcm:matrix.org
E2E new devices dialog disappears if screen is turned off by timeout. How to reproduce - send message to encrypted room with new devices, wait for processing, get dialog but lose it due screen timeout kicking in due our wait. I've just did it, logs probably will help. Or not. At end I got cancel or resend all "links" and no dialog to verify or blacklist or send anyway.

**Comment by Matrixcoffee** [comment]
I fully reproduce this on the UX rework build 104.

* Send a message into #megolm
* Wait for the new devices dialog to appear
* Press the phone power button to turn off the screen
* Press power button again and unlock the phone
* Devices dialog has disapeared, and the unsent message appears at the bottom with "cancel" and "resend" links
* Press the "resend" link
* The message is sent, *the new devices dialog does not appear*

**Comment by jeangb** [comment]
I have a crash, how to reproduce:

1. When the new devices dialog is opened, turn off the screen
2. Put the device in landscape mode, then turn on the screen

The android keyboard only is opened, impossible to come back to the room.

3. Put the device in portrait mode.

Crash. I submitted a crash report.

**Comment by jeangb** [comment]
Validated.
