### ISSUE TITLE
cannot remove a room invitation in which i was banned

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1314]
reported by @tinfoil:waffle.tech

A long time ago, a friend made a chat, invited me to the chat, banned me from the chat, then deleted the chat. This leaves a persistent invitation to the chat with the message "Cannot join user who was banned" when trying to join or "Cannot leave user who was banned" when trying to decline the invite. This makes the invite impossible to dismiss. This persists across all devices I use Riot with.

https://github.com/matrix-org/riot-android-rageshakes/issues/308

**Comment by Matrixcoffee** [comment]
Seems to be a server issue. Should this bug be filed on https://github.com/matrix-org/synapse/issues ?

**Comment by ylecollen** [comment]
right, it is a server side issue.
