### ISSUE TITLE
The Events service is properly restarted in some race conditions

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1331]
@sorunome:sorunome.de reported us that the sync was broken after updating the application to the v0.6.10.

The application worked properly after being killed twice.

https://github.com/matrix-org/riot-android-rageshakes/issues/329

**Comment by ylecollen** [comment]
We don't know if it is a ROM issue.

**Comment by Sorunome** [comment]
It happened now again randomly :( killing the app and re-opening it "fixed" it again
