### ISSUE TITLE
Read marker: not updated when scrolling up in the "preview"

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1334]
To reproduce:

1. In a room, hit "Jump to read first message" banner
2. In the "preview", scroll up a few times to display older messages
3. Leave the preview
4. Hit again the "Jump to read first message" banner

I expect the read marker to be a bit a below the one from step 2, but it's at the exactly same place.

**Comment by sabrinaj** [comment]
Not sure I get it, did you also scrolled down at step 2 ? 
At the moment, in preview mode, we only update the read marker when the user leaves the preview or goes in background, considering what we are seeing on the screen at that moment. It means that if you scroll down in the preview then scroll up, if when you leave the preview the last visible message is older than the current read marker, it won't be updated.

I'll improve this to regularly save the read marker in the preview and not only when leaving it.

**Comment by sabrinaj** [comment]
Now, in preview mode, we also update the read marker at the end of scroll (i.e. when the user removed his finger from the screen and the scroll animation is finished).

**Comment by jeangb** [comment]
Validated
