### ISSUE TITLE
Read marker: crash when turning device just after hitting "Jump to first unread msg" banner

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1335]
To reproduce:

1. Hit "Jump to first unread msg" banner
2. Quickly turn the device in landscape or portrait mode

Crash. Try again if didn't crashed the first time.
I filled a crash report about it.

**Comment by sabrinaj** [comment]
See https://github.com/matrix-org/riot-android-rageshakes/issues/334

**Comment by jeangb** [comment]
Validated
