### ISSUE TITLE
no notifications after updating to 0.6.10

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1337]
reported by @Dorni:matrix.dorni.net
No more notifications since the update to 0.6.10

https://github.com/matrix-org/riot-android-rageshakes/issues/337

**Comment by ylecollen** [comment]
it works properly on my side.
The logs tell that there are notifications but the notified events are not displayed in the logs

**Comment by takiainen** [comment]
I have never had reliable notifications with this app. Sometimes Riot informs me of a new messages, most of the time it doesn't. I have to open the app. 

I'm also using the F-droid version, but a friend mine uses the googleplay version with same problem.

**Comment by ylecollen** [comment]
on android >= 6.0 devices, the application is suspended when the phone switches in doze mode.

The google play version issue will be fixed as soon as our server will be updated.

Do you use the fdroid version with a ROM without gapps ?

**Comment by takiainen** [comment]
I haven't installed gapps.

**Comment by ylecollen** [comment]
@takiainen 
Any feedbacks after whitelisting Riot ?
Your issue should be fixed.

**Comment by takiainen** [comment]
You're right, it indeed works. Just worried that battery takes a hit, since Riot already is high on the battery stats, right after "screen". Maybe the battery consumption improves with future development? Any ideas?

**Comment by ylecollen** [comment]
@takiainen 
There are some fdroid settings to reduce the battery draining when the application is put in background.

**Comment by ylecollen** [comment]
![file1497945583653](https://user-images.githubusercontent.com/8971031/27322682-4d1f47f0-559f-11e7-9a88-1340bdd733de.png)

**Comment by ylecollen** [comment]
Increase the delay between the syncs : it is set to 30 seconds.
Many users increase it to 300 seconds.

It defines the delay between 2 sync requests when the application is in background.
It should save your battery.
