### ISSUE TITLE
Sign out from stopped home server crashes after trying for ages

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#1347]
To reproduce:

1. Log in Riot on a local home server
2. Stop the home server
3. Sign out from Riot

Takes ages (10mn) then crashes.
I think that it crashes after waking up the device after the screen time out.

On riot-ios it's very fast.

**Comment by ylecollen** [comment]
There was a similar crash when the current device was removed from an account from another device.

The steps to reproduce
-> log to an account with 2 devices
-> put the app in background on the android device
-> delete the device from the account devices from the second device.
-> put the app in foreground on the android device.

The user session must be logged out but there was either an infinite loading wheel or a crash.

**Comment by jeangb** [comment]
Validated. Didn't reproduce any crash.
