### ISSUE TITLE
Translation "Riot Android/Riot Android (Deutsch)" was not moved from nordgedanken.de to translate.riot.im

### ISSUE THREAD

**Issue by bamstam** [vector-im/riot-android#1348]
Translation "Riot Android/Riot Android (Deutsch)" was not moved from nordgedanken.de to translate.riot.im

(Translations "Riot Web/matrix-react-sdk (Deutsch)" and "Riot Web/riot-web (Deutsch)" were successfully moved)

**Comment by ylecollen** [comment]
Could you explain us what do you mean with this issue ?
We don't understand "moved from nordgedanken.de to translate.riot.im"

**Comment by bamstam** [comment]
"nordgedanken.de" was the original Weblate instance for Riot translations, meanwhile the Weblate translation has moved to "translate.riot.im". But one subproject ("Riot Android/Riot Android (Deutsch)") was not moved there (and it seems like translations are not merged into new Android releases). The issue is primarily meant for the maintainer of the Weblate translation platform. It should also be checked if all languages are consistent and complete on the new instance.

**Comment by mytbk** [comment]
I've just got to know translate.riot.im, and I see Riot Android is not there.

**Comment by MTRNord** [comment]
@ara4n @dbkr I guess they are the one in charge about translate.riot.im :)

**Comment by MTRNord** [comment]
I think the issue can be closed. The Android repo is now on the official translation platform https://translate.riot.im/projects/riot-android/riot-android
