### ISSUE TITLE
tried to redact one message, and then another before the redaction completed. got black screen and had to tap to get the app to show again. riot shows me in no rooms

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1355]
reported by @travis:t2l.io

tried to redact one message, and then another before the redaction completed. got black screen and had to tap to get the app to show again. riot shows me in no rooms

https://github.com/matrix-org/riot-android-rageshakes/issues/384

**Comment by sabrinaj** [comment]
Has been fixed.
