### ISSUE TITLE
The jump to latest unread item doesn't always appear.

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1356]
reported by Coffee

The jump to latest unread item doesn't always appear.

Just opened #matrix which had 175 unread notifications. Surely it should show me the new jump item, but it did not appear. Happens to other rooms as well - sometimes it works, sometimes not.

https://github.com/matrix-org/riot-android-rageshakes/issues/388

**Comment by ylecollen** [comment]
the latest develop version logs the read marker updates so it will possible to track the null case.

**Comment by sabrinaj** [comment]
Has been fixed: https://github.com/matrix-org/matrix-android-sdk/pull/181
