### ISSUE TITLE
Export/Import E2E room keys operation taking too long on android versions lower than 7

### ISSUE THREAD

**Issue by shireen028** [vector-im/riot-android#1357]
Currently the export and import E2E keys operation taking nearly 30-40 seconds on Android versions lower than 7.0 whereas it completes the same operation in few seconds on Android 7.0 and above devices.

**Comment by ylecollen** [comment]
The data are encrypted so it depends in the CPU performance.

You cannot have the same behaviour on a samsung S8 and a S3.
