### ISSUE TITLE
the (+) in the home page covers some rooms 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1358]

**Comment by ylecollen** [comment]
![plus button](https://user-images.githubusercontent.com/8971031/27425688-8cfa56f8-5739-11e7-9c68-8d3cbbf28ea1.jpeg)

**Comment by Matrixcoffee** [comment]
Perhaps the (+) should only be shown if we are scrolled up to the top position.

That might still cause problems if the screen is so large or the list is so small that it fits entirely on the screen, though.

Maybe it should also not be shown if the bottom category is scrolled sideways. It could still fail but it should prevent the issue in most cases.

**Comment by ylecollen** [comment]
Sabrina has implemented a trick to fix this issue.
It should be pushed today.

**Comment by ylecollen** [comment]
Fixed on develop
