### ISSUE TITLE
Allow automatically always keeping rooms with unread messages on top 

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-android#1359]
I think that Riot Android is currently difficult to read as the rooms move around when users join/leave which I think to be especially a problem with IRC users who often move multiple channels onto the top at the same time. 

I would prefer to keep rooms with unread messages (`m.message`? maybe even `m.notice`) always on the top of their tag and when I read the unread message, the room would go under unread messages or to the point of read messages where it would belong to without this. 

I am requesting for an option as I think there are people who wouldn't agree with me on this and not even Riot Web does this (where I would also like to see a similar feature).

**Comment by Matrixcoffee** [comment]
FYI, the new main screen behaves as you want. Notified messages sort to the left, before all other rooms.

**Comment by ylecollen** [comment]
duplicate of https://github.com/vector-im/riot-android/issues/1368
