### ISSUE TITLE
the "Matrix contacts only" filter status should not be lost after switching to another screen

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1360]

**Comment by jeangb** [comment]
It works but it has an impact on the global search.
Once you hit the "Matrix contacts only" filter, when you will open the global search, the **People** tab will always be open instead of the **Rooms** tab before.

**Comment by ylecollen** [comment]
@jeangb 
it was the same behaviour than before.
The global search is opened to the people tab when it is started people view.
Else, the rooms search is opened

**Comment by jeangb** [comment]
Ok. Validated.
