### ISSUE TITLE
Home tab: add options to pin (or not) missed notifications and unread messages

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#1368]
Add two options to let the user decide about pinning or not the missed notifcations and the unread messages.

- The two options are: 
  * **Pin rooms with missed notifications**: if enabled, rooms with a badge will be displayed first
  * **Pin rooms with unread messages**: if enabled, rooms with unread messages (name in bold) will be displayed first
If both are enabled, rooms with badge will be displayed before rooms with unread messages.
- Both should be disable by default.
- These options should be added in the setting screen.
- The values for these options are cleared when the user signs out

**Comment by jeangb** [comment]
Validated.
