### ISSUE TITLE
The send button is too close to the keyboard

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#1387]
Especially the backspace key, so sometimes when I try to correct a mistake, it instead sends the half-finished sentence including mistake.

It is also sometimes difficult to place the cursor at the end of the text, because the end of the text is too close to the send button.

Please consider designs which place the send button further away from the keyboard and the text. E.g. many apps place the send button in the top right corner, as part of the header.

**Comment by bmarty** [comment]
On nearly all the messaging applications, the send button is here... On some Keyboards (including GBoard), you can move the cursor by swipping the space key. Some keyboards also add a toolbar above the letters, so it makes the send button further from the letters
