### ISSUE TITLE
Tapping on a permalink just sends me to the main screen without opening the room and without any error.

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#1389]
Reported by @Matrixcoffee.

https://github.com/matrix-org/riot-android-rageshakes/issues/455

**Comment by sabrinaj** [comment]
It's  an issue with the server hosting the room. I only get an error `504 Gateway Time-out` when I check my logs and when I try from Riot web, it's same result: the room is not accessible.

**Comment by Matrixcoffee** [comment]
Please reopen. Riot should at least show an error message if the room couldn't be opened. It should not leave the original room and jump to the main screen, either.

**Comment by sabrinaj** [comment]
A toast message is shown. Note that when it's an error 504, we retry 3 times so there is a delay before displaying it.

I agree, it'd be better if we wouldn't leave the original room but for now, only the home screen is able to handle permalinks (which implies closing the original room). That's something that should be improved in the future.
