### ISSUE TITLE
Android system often warns of high battery usage of Riot

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1391]
reported by Mikaela
https://github.com/matrix-org/riot-android-rageshakes/issues/472
https://github.com/matrix-org/riot-android-rageshakes/issues/463
https://github.com/matrix-org/riot-android-rageshakes/issues/441

**Comment by ylecollen** [comment]
This user's device receives a lot of notifications while the application is background.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/477

**Comment by ylecollen** [comment]
There are two cases in theses issues
1- the users received a lot of notifications (several hundreds per hour) : the application  starts a caught up for each notifications so it might drain battery

2- Google play versions only
on versions <= 0.6.12, if the events thread service is killed while the application is backgrounded, it is automatically restarted but it used the fallback mode to trigger the sync requests : a new one is triggered each 10s. It was happened because the GCM registration was not checked. So, it used to drain battery until the application was opened.

On version 0.6.13, if a GCM registration token has been retrieved,  we assume that the GCM registration has been done (might be true in most of the cases) so the sync/ requests will be triggered when a notification will wake up the app.

**Comment by mehturt** [comment]
I have this problem even with 0.6.13
