### ISSUE TITLE
unexpected 'mention only" notification when the user name is disambiguoused

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1392]
when several users have the same display name, the clients appends their mxid to disambiguous them.

The mention only notification should check with the displayname in the room.

for example, if there are two john in a room names john(@john1:matrix.org) and john(@john2:matrix.org), a message with John should notify nobody

**Comment by Matrixcoffee** [comment]
Since Riot-Web apparently already behaves this way, it would be good to look at the algorithm it uses.
