### ISSUE TITLE
Getting notifications for unrelated messages

### ISSUE THREAD

**Issue by pferreir** [vector-im/riot-android#1407]
I noticed that I get notifications for many messages I have nothing to do with. I suspect it's because of my nickname (`ub|k`) containing a regex special character.

![screenshot_20170704-154542](https://user-images.githubusercontent.com/2699/27834766-7e7f10c0-60d8-11e7-850b-0d19571a3279.png)

**Comment by sabrinaj** [comment]
Indeed, it is because your nickname contains a special character. Should be fixed on branch develop.

**Comment by pferreir** [comment]
Thanks!
