### ISSUE TITLE
crash when the mark all response is received whereas the user switches to another fragment

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1410]
Steps to reproduce

- Select "Mark all as read" on the home menu with many unread messages and on a slow network
- Switch to another home tab
----> the app used to crash when the response was received

https://github.com/matrix-org/riot-android-rageshakes/issues/515
https://github.com/matrix-org/riot-android-rageshakes/issues/519

**Comment by sabrinaj** [comment]
Fixed on develop.
