### ISSUE TITLE
Wrong logo on the login page

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-android#1415]
Unfortunately we've had a few versions of the new logo floating around, some using slightly wrong fonts :(

For the next release, please change the login page logo to the riot.im logo available here: https://github.com/vector-im/logos/tree/master/riot

The key difference - in the wrong version of the logo, the .IM is in a very slightly different font (meaning the I has square corners rather than the round corners it should have).

**Comment by sabrinaj** [comment]
I updated the logo on branch `develop`.
