### ISSUE TITLE
Feature request collapsible user status messages like webapp

### ISSUE THREAD

**Issue by muzirian** [vector-im/riot-android#1423]
It would be so helpful to have collapsible user join/left messages like the webapp have.It would save lot of screen space on fone and make it easier to read messages, esp in irc bridged groups, which will  be flooded with these status messages.
TY

**Comment by sabrinaj** [comment]
It's already planned so I close this issue.

See https://github.com/vector-im/riot-meta/issues/20

**Comment by muzirian** [comment]
ty
