### ISSUE TITLE
claims to send encrypted messages, sends unencrypted

### ISSUE THREAD

**Issue by azrdev** [vector-im/riot-android#1427]
We have a test room with encryption enabled. In riot-android 0.6.13 to see the messages and send encrypted ones, I have to enable E2E encryption in the settings.

However, as long as the app does *not* have encryption enabled, it will send out my messages unencrypted, despite marking the room as encrypted (in room icon and room details page), and while the background of the input-field reads "send encrypted message".

Especially the latter seems dangerous to me. It should be corrected, also, a clear indication seems useful that one has to enable encryption in the app settings before being able to use it.

**Comment by ylecollen** [comment]
@azrdev 
The encryption is enabled for each new account (and for a while).
Only, some former accounts did not enable e2e.

but, you're right we should update the "send encrypted message" text in this case
