### ISSUE TITLE
"mark as read" in notifications

### ISSUE THREAD

**Issue by Valodim** [vector-im/riot-android#1447]
The current behavior of notifications in regard to marking as read feels off: When I dismiss a notification the message isn't marked as read, which makes the same notification pop up again some time later. The only way to acknowledge the message is to actually open riot.

Is there a reason not to mark messages as read if the notification is dismissed? And if there is, can we get a "mark as read" action on it as an alternative?

**Comment by bmarty** [comment]
Done in Riot 0.8.26
