### ISSUE TITLE
UX request: load previous messages before reaching the top of currently loaded scrollback

### ISSUE THREAD

**Issue by jfrederickson** [vector-im/riot-android#1452]
I was comparing Riot Android and Riot iOS recently, and I noticed that the iOS app actually starts loading scrollback before you reach the oldest currently loaded messages. This makes scrolling back feel much smoother, so long as you're not scrolling fast enough to hit the top of your local message view. IMO Riot Android should do this too.

**Comment by ylecollen** [comment]
it also does it.
