### ISSUE TITLE
Messages not marked as read anymore

### ISSUE THREAD

**Issue by Linuxine** [vector-im/riot-android#1459]
On version 0.6.14, and apparently since the 0.6.13, when using simultaneously riot-web and riot-android, the messages are not marked as read by the Android client, as long as they are not read in the web client. 

If a contact send me 2 messages, I get a correct notification, I can read them in my Android, but the "2" icon on the contact name will stay (and also on the Riot icon). I will also always have the "jump to first unread message" menu, and using it will change nothing. I have tried the "mark all as read" menu as well, it does nothing. The only way to get these message to be considered as read by the android client is to read them again in the web client (which, by the way, also displays them as unread before reading them in it). It seems that the Android client does not sent the "read" notification to the server anymore ? 

I am hosting my own matrix and riot. My matrix-react-sdk version is 0.9.7. The web Riot version is 0.11.4, and the bug is reproduced on various Android 6 and 7.

This is not critical, but quite annoying, the unread messages counter can quickly increase depending on the room activity.

**Comment by ylecollen** [comment]
Do you have a custom home server ?

**Comment by Linuxine** [comment]
I have used the master version from synapse, my version is {"server":{"version":"0.20.0","name":"Synapse"}}. I just realized this is not the last one, could it be related to a mismatch between Riot and Matrix versions ?

**Comment by ylecollen** [comment]
@Linuxine 
Could you send a bug report after opening a room with unread messages ? 

thank you

**Comment by Linuxine** [comment]
I have juste sent one, with the description "the messages are not marked as read". What is  strange is that when going on a room, reading the message, then going back to the room list, at first, the messages are marked as read. Then, if I interact with another room, and goind back to the room or contact list, then there seems to be a kind of reset, and all messages not read on the web are displayed as unread again.

**Comment by ylecollen** [comment]
07-25 16:33:40.649Z 1 D/RestAdapterCallback: ## failure(): [sendReadMarker : roomId !ckCdEKRZskcEdlkbBC:linuxine.net - rmEventId null -- rrEventId $15010002138166SNrGI:linuxine.net] with error 400 Bad Request

**Comment by ylecollen** [comment]
@Linuxine 
Your server does not seem up-to-date.

**Comment by Linuxine** [comment]
Okay, I try to update it and let you know, thanks !

**Comment by ylecollen** [comment]
Entre francais, on peut bien s'aider :)

**Comment by Linuxine** [comment]
Merci ! ;)

I have now the last version of the homeserver, and I have not reproduced the issue for now. I will wait a few hours to make sure before closing the tickets, since yesterday I though the bug was gone with the new Riot version and I was wrong ^^

Thanks a lot for the help anyway !

Last question, since the update, Riot works fine, but I seems to have make something wrong, my homeserver is literaly vomiting logs saying : 
`2017-07-26 13:27:42,613 - twisted - 131 - CRITICAL - - Unhandled Error
Traceback (most recent call last):
  File "/home/matrix/synapse/lib/python2.7/site-packages/synapse/app/homeserver.py", line 461, in in_thread
    reactor.run()
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
  File "/home/matrix/synapse/lib/python2.7/site-packages/synapse/metrics/__init__.py", line 151, in f
    ret = func(*args, **kwargs)
--- <exception caught here> ---
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
    protocol.connectionLost(reason)
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/protocols/tls.py", line 403, in connectionLost
    ProtocolWrapper.connectionLost(self, reason)
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/protocols/policies.py", line 125, in connectionLost
    self.wrappedProtocol.connectionLost(reason)
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/web/http.py", line 2190, in connectionLost
    self._abortingCall.cancel()
  File "/home/matrix/synapse/lib/python2.7/site-packages/twisted/internet/base.py", line 99, in cancel
    raise error.AlreadyCalled
twisted.internet.error.AlreadyCalled: Tried to cancel an already-called event.
`

I have just stopped the server, made the update then restart it ; should I had done something else ? Flush some connection or something ?

**Comment by ylecollen** [comment]
@Linuxine  
I don't know how the server works.
You could ask it in Matrix HQ (#matrix:matrix.org)

**Comment by Linuxine** [comment]
Updating my matrix server did resolve the issue, so I close this ticket. Thanks a lot for your help !
