### ISSUE TITLE
Rotating the device while an image is uploading inserts the image twice

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-android#1467]
Steps to reproduce:
1. Take a photo
1. While it's uploading change the device orientation
1. When the upload completes there are two images inserted to the feed

That's a pure UI bug, rotating the device again after that gets rid of the duplicate.

**Comment by ylecollen** [comment]
@rkfg 
i don't reproduce your issue.
DO you have the issue with your dark theme branch or with the develop one ?

**Comment by rkfg** [comment]
That's on the develop branch with no additional patches applied. I take a photo in portrait orientation then while the image is semi-transparent with a progressbar below I rotate the phone to landscape orientation and wait for it to finish. Then there are two photos displayed. If I rotate the phone back to portrait it all becomes normal, only one instance is visible.

**Comment by ylecollen** [comment]
ok, i reproduce it.

**Comment by rkfg** [comment]
Also a related bug: if I rotate the phone while the image compression dialog is open it disappears and I lose the photo taken. I'm unsure if it deserves a separate issue though.
