### ISSUE TITLE
E2E import doesn't change the Device ID or Key

### ISSUE THREAD

**Issue by PC-Admin** [vector-im/riot-android#1488]
Hello!

I tried to import E2E keys on Android and the new device appears but the previous device and keys are still bold.

How do i apply the new E2E keys i have imported? How do i remove the new keys that are currently bold and unremovable?

Android version: 7.1.2
Riot Version: 0.6.14
GAPPS: No.
Matrix Address: @PC-Admin:perthchat.org

**Comment by PC-Admin** [comment]
Can delete bolded key from web ui which forces the Android client to log out.

But when logging back into Android it generates a new key instead of adopting the one i was trying to import. Trying to import a second time fails in the same way.

**Comment by krombel** [comment]
The option to import E2E room keys is not intended to change the device id.
You are only importing keys to **decrypt previously send messages**. The import/export is not meant to do more.

All messages are meant to use the new device keys and there no way to reimport previously used device keys (besides hacking into the device as root)

The feature you might want to have is mentioned in vector-im/riot-web#4104

**Comment by PC-Admin** [comment]
Okay, that was very informative thank you. :)
