### ISSUE TITLE
In calls, all audio is routed into the top speaker. My Bluetooth earphones with mic that I use to answer normal calls stop working during riot calls. I haven't tested with normal earphones but I doubt it's different.

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1493]
reported by @Ace:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/768

**Comment by Masteris** [comment]
Have same issue. I have a Parrot Zik connected in BT but when I receive a call, to goes to the phone speaker.
