### ISSUE TITLE
need new riot animated splash graphics

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1494]
RIOT.IM branded, and capable of looking okay on dark theme

**Comment by Mikaela** [comment]
Does the splash need to be animated? I think it's annoying as if I don't lock Riot in recent apps, I see it multiple times a day for minutes. I also cannot think of any other app which I use where there is a splash screen that makes me feel annoyed or look somewhere else.

**Comment by bmarty** [comment]
I think it's done.
