### ISSUE TITLE
Android Riot app should set our presence to idle when it goes to the background

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-android#1509]
At now if user logging in to Matrix via Android Riot app, it always have Online status. But Matrix support idle status, so Android Riot app should set the flag in `/sync` which says 'make me idle' when app goes to background. Same issue on Riot-web: https://github.com/vector-im/riot-web/issues/4813

**Comment by richvdh** [comment]
In general, the android app doesn't call `/sync` when its in the background, so it's not as simple as that.

**Comment by krombel** [comment]
The app triggers `/sync` when a GCM/FCM push gets received and "background sync" is enabled.

Currently in that case `set_presence=offline` is not set (which causes synapse to not reset the "online timeout")

So it might be possible to just send `set_presence=offline` in this case.
Currently the only situation when sending offline is defined [here](https://github.com/matrix-org/matrix-android-sdk/blob/c4efe34675a68105212148537e36e245950fa46d/matrix-sdk/src/main/java/org/matrix/androidsdk/sync/EventsThread.java#L499). So when the app is in background (so not online) `offline` is not set AFAICS

**Comment by MurzNN** [comment]
App can listen event when it goes from foreground to background, and send last 'idle' event, this is like Rocket.Chat do: when I hide app - I immediately show away status, when open - immediately go online.

**Comment by krombel** [comment]
The problem is the "multi device" scenario...

**Comment by MurzNN** [comment]
This problem must be correctly solved at server-side, server must accumulate presence info from all clients and show actual info based on all devices.

**Comment by MurzNN** [comment]
But now it also must work normally: if I close mobile app, it sends to server last 'idle' event. But if I have any other app with active state, it will rewrite this presence to 'online' via `/sync` events, so users will see only short jump online-away-online.

**Comment by krombel** [comment]
My PR should especially fix this (latest mentioned) issue

**Comment by ylecollen** [comment]
https://github.com/matrix-org/matrix-android-sdk/commit/a40f38b43f24453c1484b71fde4987eaaaddb161
