### ISSUE TITLE
Camera activity has no ability to activate flashlight

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#1511]
Currently there is no way to activate the phone's back LED light from the Camera activity.

There was an issue created for this earlier (#425), but it was closed by the author.

This has not yet been fixed.

**Comment by ylecollen** [comment]
the current design does not include a button to enable / disable the flashlight.
Many other features are not available (red eyes filter, cropping....)
It won't be fixed until it is decided to replace our custom camera activity by the native one.
