### ISSUE TITLE
'Resend or Cancel all' dialog should not appear after cancelling a file upload

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#1512]
Currently a redundant 'Resent or Cancel all' dialog in red appears after canceling a file upload (I've only tested with an image thus far, but I believe it's likely the same on all files).

The image sending message should just be deleted as we already ask the user with a pop over message whether they want to cancel or not.

**Steps to reproduce:**
1. Upload file
2. Cancel before it finishes uploading
3. Select 'Yes' on the confirmation dialog
3.5 (This should be it, instead...)
4. Select 'Cancel all' on the new dialog that appears

**Comment by ylecollen** [comment]
sorry, it is the expected behaviour

**Comment by anoadragon453** [comment]
Alrighty, just seems kinda counter-intuitive is all.
