### ISSUE TITLE
Required restarting Riot.im app after each conectivity change

### ISSUE THREAD

**Issue by SkyWheel** [vector-im/riot-android#1513]
Hi all,

If I'm switching between Wi-Fi and 4G, or even between different Wi-Fi networks, Riot.im cannot connect to internet without stopping process from Developer options and then starting the app as usually.

Checked devices: Samsung Galaxy S6 with Android 7.0, Lenovo with Android 4.2.1, Google Pixel XL with Android 7.1.1

**Comment by ylecollen** [comment]
@SkyWheel 
Weird, it will but it might need a little delay : there is no way to cancel a request with the OkHttp version we use so, it should be retried after 30s or so.

could you check on your side ?

**Comment by ylecollen** [comment]
@SkyWheel 
Could you send a bug report with your devices ?
it seems working on my side. (even if it might require a delay).

**Comment by SkyWheel** [comment]
It's funny, but when I'm trying to send a bug report within the app, it can't be send due to the same connection issue...
I'll try to fetch some logcat.
As soon as my devices are non-rooted devices (unfortunately :-(  ), it will take some time to setup ADB within computer...

**Comment by SkyWheel** [comment]
Seems to be resolved in later releases.
