### ISSUE TITLE
'Enable background sync' is viewable on fdroid build preference does not have an effect

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#1514]
The setting gets evaluated only for the GCM settings [here](https://github.com/vector-im/riot-android/blob/ae6f376/vector/src/main/java/im/vector/fragments/VectorSettingsPreferencesFragment.java#L490-L509) so this setting either should cause e.g. stopping of background sync completely or (as short term solution) should not be viewable on the fdroid build

**Comment by wnereiz** [comment]
This definitely happened in my F-Droid riot client. Only occasionally the background sync worked. It is a serious problem in my point of view.
