### ISSUE TITLE
 java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1527]
reported by @anomie:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/820

Thread: FinalizerWatchdogDaemon, Activity:im.vector.activity.VectorSettingsActivity, Exception: java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:423)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
	at java.lang.Thread.run(Thread.java:818)

**Comment by ylecollen** [comment]
https://stackoverflow.com/questions/24021609/how-to-handle-java-util-concurrent-timeoutexception-android-os-binderproxy-fin/28708351

it seems quite common and triggers when GC is called.

**Comment by ylecollen** [comment]
We cannot fix it.

**Comment by DadChen** [comment]
java.util.concurrent.TimeoutException: android.os.BinderProxy.finalize() timed out after 120 seconds
We cannot fix it ，who can help me ?

**Comment by zongjiHuang** [comment]
keep you system awake。don't let is go to sleep.but has side-effect
