### ISSUE TITLE
 Riot uses ~20% of my battery (next chat app WhatsApp 1%, others not listed)

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1529]
reported by @mikaela:disroot.org
https://github.com/matrix-org/riot-android-rageshakes/issues/825

**Comment by Mikaela** [comment]
I think this is a duplicate of https://github.com/vector-im/riot-android/issues/995 which being unfixed I still haven't understood.

**Comment by ylecollen** [comment]
there are 2 issues here
-> you don't have notification when the background sync is disabled : vector-im/riot-android#1546 should be fixed
-> the application drains too much battery : nothing seems weird except that you joined large rooms

**Comment by ylecollen** [comment]
the background catchup is responsible in  your case.
nothing we can do with a new server api
