### ISSUE TITLE
Video call failed / no sound

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1531]
reported by @clem:chat.nudle.win
https://github.com/matrix-org/riot-android-rageshakes/issues/836

**Comment by krombel** [comment]
Related (if not duplicate): #1526

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/852

**Comment by ylecollen** [comment]
https://github.com/vector-im/riot-android/issues/1526
