### ISSUE TITLE
screen locked. app ended up in off state

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1545]
reported by @john:sheeplauncher.net
https://github.com/matrix-org/riot-android-rageshakes/issues/896

**Comment by mastad0n** [comment]
For what its worth, I've had this issue too, for the last 4 or 5 versions of riot.


Whenever I don't use my phone for a while, Riot turns off. 


This causes notifications of new messages to not come trough until I start Riot again.


I use Android 6.0


Battery saver is not on. Not sure if it has to do with connectivity changes as mentioned here (https://github.com/vector-im/riot-android/issues/1513)

**Comment by ylecollen** [comment]
@mastad0n 
could you send a bug report the next time you have it ?

**Comment by mastad0n** [comment]
@ylecollen yes will do!

**Comment by ylecollen** [comment]
@mastad0n 
Are you using the google play or the fdroid version ?
With the fdroid version, you need to disable the battery optimisation for Riot.

**Comment by mastad0n** [comment]
@ylecollen Thank you very much. I use the Fdroid version. I just added it to the "don't optimize" list, lets see if that fixes it. Will report back in ~3 days. I did not realize battery saver and battery optimisation are 2 different things. Let's hope this works.

**Comment by mastad0n** [comment]
Following up as promised, @ylecollen your suggestion fixed it. Thank you, and thanks for your hard work on Riot.
