### ISSUE TITLE
the typing notification is not working

### ISSUE THREAD

**Issue by bassazz2007** [vector-im/riot-android#1551]

**Comment by ylecollen** [comment]
@bassazz2007 
Could you provide us more details ?
any case ? with a custom home server ?

**Comment by bassazz2007** [comment]
yes iam using riot with home server synapse

**Comment by ylecollen** [comment]
@bassazz2007 
Custom one or with the default one (matrix.org)?
you don't receive the typing notifs or you don't send them ?

**Comment by bassazz2007** [comment]
its the default one
both I don't receive and the other device does not receive also

**Comment by ylecollen** [comment]
@bassazz2007
could you send a bug report ?
it works on my side (android vs web) with the both directions

**Comment by bassazz2007** [comment]
iam using riot for android on both devices

**Comment by bassazz2007** [comment]
where the typing notification must be displayed on screen ?

**Comment by bassazz2007** [comment]
note that iam not using rooms I use direct chat

**Comment by ylecollen** [comment]
![typing](https://user-images.githubusercontent.com/8971031/29922843-aace4d7e-8e57-11e7-8eed-5fa9e5d00a9d.jpeg)

**Comment by ylecollen** [comment]
@bassazz2007 
the typing notifs must be displayed above the text editor (like you can see on the attached screenshot)

**Comment by ylecollen** [comment]
@bassazz2007
Any feedback ?

**Comment by bassazz2007** [comment]
hi,
I tried to turn it off and on again but no luck still not working, I have android 4.4.4 and other device is 5.1

**Comment by ylecollen** [comment]
@bassazz2007 
Is one of the user posted on a custom homeserver ?

**Comment by bassazz2007** [comment]
no both using matrix synapse non custom.

**Comment by bmarty** [comment]
Hi @bassazz2007, do you still have the issue? If not I will close it
