### ISSUE TITLE
Send button has stopped working

### ISSUE THREAD

**Issue by contrapunctus-1** [vector-im/riot-android#1566]
Moto G5S Plus, Android v7.1.1

Riot v0.7.00 from F-Droid

The send button has stopped working after a day or so of use. Everything else in the application is functional. Reinstallation did not fix it. Tapping many times, in different places, did not work.

I am able to send messages from the browser client.

**Comment by ara4n** [comment]
Please can you rageshake or send a bug report from settings so we can see what's broken?

-- 
Matthew Hodgson
Matrix.org

**Comment by contrapunctus-1** [comment]
@ara4n Sent.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/984

**Comment by ylecollen** [comment]
@contrapunctus-1 
Does it work on landscape mode ?
The moto G4plus got issues with its touch screen. (i.e some parts of the screen did not work on some cases).

https://forums.lenovo.com/t5/Moto-G5-Moto-G5-Plus/Moto-G5-plus-touch-not-working-suddently/td-p/3705695 : G5 plus seems having some ones too.

2 or 3 users got such issues but it does not make sense from code side.

**Comment by contrapunctus-1** [comment]
@ylecollen no change in landscape mode.

**Comment by bmarty** [comment]
We cannot do anything on this issue
