### ISSUE TITLE
Login and Registration Button seems to be to small after translation

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#1568]
[@Keiro:matrix.org](https://matrix.to/#/@Keiro:matrix.org) mentioned [here](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$15046333301418578kvEgB:matrix.org):
>with Hungarian translation, as you can see the registration and login buttons in hungarian look pretty weird, would be nice if you could scalde down the text or scale up the buttons to fit in a single line.

Here is a screenshot: ![Screenshot](https://matrix.org/_matrix/media/v1/download/matrix.org/vzxfisqjGPsZgfGEKwjjyNmy)

**Comment by bmarty** [comment]
Fixed
