### ISSUE TITLE
Add Voice input button

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-android#1577]
At now Riot don't have voice input button so we must use external software for voice input the message. Will be good to add integrated button for start voice input, like in WhatsApp:
![](https://user-images.githubusercontent.com/1190097/30068738-e7c44432-921b-11e7-815b-9479164588f9.png)
And after start typing - it replaced to Send button:
![](https://user-images.githubusercontent.com/1190097/30068749-f1bbe0f8-921b-11e7-8123-4e5bebb78eb8.png)

**Comment by jcgruenhage** [comment]
Duplicate of #1395

**Comment by sim6** [comment]
Any progress about this?

**Comment by sim6** [comment]
Currently there is a configuration option named "Send voice message" that adds "Send voice" option on touch the clip. Thanks, but I think it needs to many taps.

**Comment by bmarty** [comment]
Duplicate of #1237
