### ISSUE TITLE
new notification sound is extremely annoying

### ISSUE THREAD

**Issue by majewsky** [vector-im/riot-android#1586]
I'm getting the client via the Play Store. There was an update this week (don't remember which day exactly), and when I talked to someone using Riot today, I noticed that there is a new notification sound which is not the standard one. The sound is high-pitched and really annoying. Everytime it plays, I twitch involuntarily and this has already cost me a few lives in the game I was playing. I looked through the Settings menu and could not see an option to change the sound. Please add such an option, or just get rid of the sound (the default one is good enough).

**Comment by ylecollen** [comment]
@majewsky 
The notification sound is the same than the webclient.
You could also disable the notification (it is only available on the webclient settings).

**Comment by majewsky** [comment]
Disabling the notification is not an option. I *want* to be notified when a message comes in, but I don't want it to happen with this annoying sound.

> The notification sound is the same than the webclient.

So it's the old question of "should we be consistent with the platform, or with ourselves on other platforms?". My money is always on "the platform" or "let the user decide". (For example, I hate WhatsApp's custom notification sound just as much. At least they only do it when the app is open, though.)

I'm trying to say this in the politest way possible, but I want to be clear at the same time: If the decision is to stay with this sound and not offer an option to reset the sound to system defaults, I will uninstall Riot (and, consequently, probably also Synapse). It's *that* annoying a sound.

**Comment by majewsky** [comment]
Thanks! Very much appreciated.
