### ISSUE TITLE
Client unable to connect on server after certificate update

### ISSUE THREAD

**Issue by Linuxine** [vector-im/riot-android#1592]
On my self hosted matrix homeserver, I use Let's encrypt certificates. When renewing the certificates, I have made sure the matrix server is restarted, and also even Apache. The web version of Riot has not issue with this process, but the Android version does not seem to be able to manage the certificate renewal : the app is not able to connect to the server, and to send or receive anything after the certificate update.

The only way I have found to solve this is to logout and login again on the Android App. This is annoying, since I have to contact my users to indicate them they have to logout, by another mean than using Riot...

I have not found a way to automatically logout all the users from the server, is there a way to do so ? Thanks for the help !

**Comment by maxidor** [comment]
@Linuxine Not necessarily a way to solve your problems, but while you are dealing with certificates, see [Recommended setup for synapse](https://github.com/matrix-org/synapse/issues/2438)

**Comment by Linuxine** [comment]
@maxidor Hi, thanks for the advice, I have changed the configuration, I was indeed using a certificate on port 8448 for the client. So I hope this will help to avoid the issue on the next certificate renewal, I will keep you posted !

**Comment by ylecollen** [comment]
Linuxine : i fixed the issue but i don't have a custom HS to test.
you should have a dialog if the SSL certificate is updated to validate it.

**Comment by Linuxine** [comment]
Great ! Thanks ! I will check on my next certificate update, then !
