### ISSUE TITLE
Connection not establishing when answering an incoming call after unlocking

### ISSUE THREAD

**Issue by dva-re** [vector-im/riot-android#1593]
I'm not sure if someone has already spoken about this problem. Sometimes, when an incoming call to a locked phone, after unlocking and trying to answer - the connection is not established, and at the same time the speaker is supposed to be turned on.

On previous version (0.7.00) I did not encounter this problem.
Only since install 0.7.01

All versions from Google Play.
Used own HS, latest from https://hub.docker.com/r/silviof/docker-matrix/ with configured TURN.

This behavior causes some problems. I have to drop the connection and call back or success accept second try of call, when phone is not locked. Pls, fix it ASAP. 

Regards.

Additional info:

Encryption in conversation: enabled.
OS: LineageOS 14.1 (Android 7.1.2)

**Comment by dva-re** [comment]
I was send bugreport from app with comment "for issue #1593"

And what on the screen after answering
![file1505296762286](https://user-images.githubusercontent.com/10573161/30371597-c431fe56-9883-11e7-9470-413586e82764.png)

**Comment by dva-re** [comment]
On previous version (0.7.00) I did not encounter this problem.
Only since install 0.7.01 

All versions from Google Play.
Used own homeserver, latest from https://hub.docker.com/r/silviof/docker-matrix/ with configured TURN.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1023

**Comment by dva-re** [comment]
But why f-droid label, if I use google play version ?

**Comment by ylecollen** [comment]
OS: LineageOS 14.1 (Android 7.1.2) -> it is not an official ROM.
LineageOS 14.1 has also some issues (even if i don't think it is a ROM issue)

**Comment by dva-re** [comment]
Ok, I will try catch this bug on official ROM on other devices of my friends.

**Comment by digititus** [comment]
I can confirm this behavior on Android 6.0 and 5.0 devices with Riot from Play Store
