### ISSUE TITLE
F-Droid 0.7.01 does not ring promptly

### ISSUE THREAD

**Issue by michaelschefczyk** [vector-im/riot-android#1604]
Trying to place (video) calls in encrypted rooms between different android and desktop clients, I find F-Droid 0.7.01 to ring reliably only if it is active in the foreground, ideally shortly after a fresh start. If the app is not running in the foreground, it is either not ringing or it will ring with substantial delay and sometimes even beyond the caller hanging up.

I was glad that you did include autostart at boot, which I did enable hoping that the devices would then not only alway show "Riot.im Listening for events" but also always ring if called.

This is tested on Oneplus3, Galaxy S4 and Nexus 7 each running LineageOS 14.1-201708xx. The result does not depend on using matrix.org or my homeserver. 20 second sync request delay is set and automatic battery optimization disabled. In general, I find the Nexus 7 to be a slightly more reliable "ringer", but nevertheless, ring reliability/delay is too low with all devices. The least reliable seems to be the Oneplus3 - while it has the most powerful hardware.

I am also unable to specify the notification sound / vibration in detail. While all devices have "Beryllium" as the notification sound and "Orion" as the ring tone, they do behave differenty upon being called - if they do ring: The S4 only vibrates while the Oneplus 3 and the Nexus 7 make a sound which is neither Beryllium nor Orion but rather the same ringtone that the desktop app produces.

It would be really good if this could be resolved.  Users of the F-Droid version on LineageOS are likely those who want to get themselves away from WhatsApp. To compensate for a smaller network, more functions could be a key.

**Comment by springbov** [comment]
I've been experiencing the same thing on my set up. I'm on lineage-14.1-20170906-nightly-kiwi-signed. I'm using a Huawei Honor 5x. My lineage os version is comparable to android 7 (nuget)
I've only tested the fdroid build to fdroid build calling. I've found it to be not responsive (in the same manner as @michaelschefczyk had described.

In addition, i've noticed it with normal voice calls too. The encryption didn't seem to affect it from what I remember of testing.

**Comment by ylecollen** [comment]
@michaelschefczyk 
I already asked you to send a bug report when it happens.
I don't have the same devices with the same OS on my side.

**Comment by michaelschefczyk** [comment]
Thank you very much for looking into this!! If I can provide more detail, logfiles, a testcall, a test via a development version or whatever, I will be glad to do so.

**Comment by ylecollen** [comment]
@michaelschefczyk  
Please, send a bug report after getting the issue : in the sliding menu (home page), you have an option to send a bug report : please use it !

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1067

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1068

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1068

**Comment by ylecollen** [comment]
@michaelschefczyk 
@springbov  

Everything seems ok on your logs side i.e the delay between syncs is really about 20s.

The sync between delay defines the maximum delay to get the incoming call event when the server receives it.

There is no push mechanism on the fdroid version so it explains the delay you have.
You should not have such issue with the google play version.

**Comment by springbov** [comment]
@ylecollen I respect your decision on this but I want to make it clear the reason I use the fdroid version is because I don't have google play services on my phone. And I don't have any intentions of changing that.

**Comment by michaelschefczyk** [comment]
I agree, but I will try to generate examples where that does not work. A further issue is the called side not stopping to ring.

Von: Yannick LE COLLEN [mailto:notifications@github.com]
Gesendet: Donnerstag, 21. September 2017 17:09
An: vector-im/riot-android <riot-android@noreply.github.com>
Cc: Prof. Dr. Michael Schefczyk <michael@schefczyk.net>; Mention <mention@noreply.github.com>
Betreff: Re: [vector-im/riot-android] F-Droid 0.7.01 does not ring promptly (#1604)


@michaelschefczyk<https://github.com/michaelschefczyk>
@springbov<https://github.com/springbov>

Everything seems ok on your logs side i.e the delay between syncs is really about 20s.

The sync between delay defines the maximum delay to get the incoming call event when the server receives it.

There is no push mechanism on the fdroid version so it explains the delay you have.
You should not have such issue with the google play version.

**Comment by hhassey** [comment]
I don't know why this is closed, I have the same problem, no ring on an Version 0.8.8 (F-4c323337)
in a samsung galaxy s6 

It really sucks, do I have to go to google to download their version?

**Comment by springbov** [comment]
@hhassey much later after this issue was closed I found that there was a setting (under background synchronization) that controls how frequently it checks for things like calls and messages. when i was on 7.01 the default setting was 600 seconds, after i changed it to 60 i was actually able to receive calls. I think it's supposed to default to 30 seconds between sync requests now. Try messing with that and see if you can get calls working.

If that doesn't help, try making a bug report through the app.
