### ISSUE TITLE
 'add integrations'  has no effect in the "add integrations" windows

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1609]
reported by @lazz:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1076
somehow when I tap on 'add integrations' in the new widget implementation on riot fdroid develop the add integrations window does not appear. the button gets marked in blue (see screenshot), but the screen does not change. it should open window where the available widgets to be added are shown

**Comment by ylecollen** [comment]
i got this behaviour once but i don't reproduce it.
https://github.com/vector-im/riot-android/commit/a5300be1408e797928729ed79e1b3241c7076550 should help to track it.

**Comment by bmarty** [comment]
not reproduce with new scalar version
