### ISSUE TITLE
Search field is dissapeared 

### ISSUE THREAD

**Issue by vladare** [vector-im/riot-android#1625]
Search field is dissapeared after the encryption mode enabled for a room

**Comment by ylecollen** [comment]
because there is no way to search a pattern server side (as the room is encrypted).

**Comment by vladare** [comment]
Does the search on client side is not  applicable as some alternative?

**Comment by ylecollen** [comment]
Only the latest messages are kept in device store.

If a message is not found, someone will yell that he has got the message one week before.
As it was deleted, it would not be found.

It seems safer to disable the search.
