### ISSUE TITLE
Update targetSdkVersion to android-26

### ISSUE THREAD

**Issue by parmegv** [vector-im/riot-android#1633]
Hi!

 Android Oreo is out there, and I was wondering if there is any problem with updating the targetSdkVersion to android-26.

 Thank you very much

**Comment by ylecollen** [comment]
i will do after the next release.

**Comment by parmegv** [comment]
Cool, thanks! Do you have a public webpage where I can check what are the release plans?

More concretely, do you know when will be the next version released?

**Comment by ylecollen** [comment]
i assume we will make a new release next week.

**Comment by ylecollen** [comment]
Why do you need the targetSdkVersion udpate ?
it already works on Android 8 device.

**Comment by parmegv** [comment]
Three reasons:

1. I want to have only the latest version of the SDK installed, storage is sometimes a problem for me and I want to have only one AVD created.
2. I think keeping up to date with library and platform versions is good for apps. Now, for instance, with android-26 we only need the intel atom image so I suppose they have done the work to make sure dropping the old ones is OK. And that's good, it reduces the testing space. 
3. If you check the developer documentation, all the information is for the latest version. If the target SDK is lower, it is possible that some new functions or best practices are not available (I haven't checked if it is the case with Android 8, though), and that is not good for the quality of the code.

I think updating the SDK version is not a big issue, but I may be wrong.

Thanks again!
