### ISSUE TITLE
long beeps (dial tone) in parallel with the conversation

### ISSUE THREAD

**Issue by dva-re** [vector-im/riot-android#1638]
Outgoing call. The screen turned off and was locked by timeout during long beeps. If at that moment the called user answers my call, then I hear long beeps in parallel with the conversation. And they do not disappear until I turn on the screen and unlock the phone.

**Comment by ylecollen** [comment]
@dva-re 
Which application version ?
It might be notification sound.

**Comment by dva-re** [comment]
I tested it just now on develop build 1646.
The problem is still here. It is dial tone (which means that the called user has not yet answered the call)

**Comment by dva-re** [comment]
Tested on develop build 1649. Thank you, it is fixed.
