### ISSUE TITLE
killed bluetooth headphone, can't play music or voice call in other apps after using voice/video call in riot

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1639]
reported by  @tleydxdy:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1178

**Comment by dva-re** [comment]
I also encounter such behavior. As a workaround, it helps to remove the application from the list of recently used applications to make music work.

**Comment by tleydxdy** [comment]
and Bluetooth headphone in riot voice/video call isn't working either; the app uses the speaker.

**Comment by dva-re** [comment]
@ylecollen 
This again happens, after refactor_call_management
Please reopen this issue.

**Comment by tleydxdy** [comment]
I don't think this patch in a release yet?
