### ISSUE TITLE
Video calling with iOS client doesn't work

### ISSUE THREAD

**Issue by clxcoltz** [vector-im/riot-android#1649]
Android client seems to have trouble video calling against others, voice worked fine. Applies to both F-droid and Play Store clients, video will go on for up to a minute then cut off/freeze frame while voice still works fine. 

Tested combinations, all of them latest "release" version on various platforms' store or repos:

Android (7.0 Nougat) <-> iOS : Video freezes after a minute or so. Voice works fine. iOS client seems to be able to see Android's cam fine.
Android <-> MacOS (Sierra): Same as above.
Linux (Fedora 26, 0.12 via taw copr) <-> MacOS: Video works fine.
Linux <-> iOS: Video works fine.
Windows 10 <-> iOS: Video works fine.
Windows 10 <-> MacOS: Video works fine.

**Comment by ylecollen** [comment]
The video / voice call lib has been replaced on version > 0.7.01.
@clxcoltz could try with the develop version ?

**Comment by clxcoltz** [comment]
I assume the development version will need to be sideloaded, will it has push notification?

**Comment by ylecollen** [comment]
@clxcoltz 
you will need to remove the app before installing the develop version.

**Comment by ylecollen** [comment]
@clxcoltz
A new google play release has been published. Could you check with it ?
thank you

**Comment by clxcoltz** [comment]
Tested and confirm fixed. Thank you!
