### ISSUE TITLE
Quoting uses more newlines than needed

### ISSUE THREAD

**Issue by nvbln** [vector-im/riot-android#1663]
As an example, when I type:

```
> test

Test
```

The following will happen:

![file1507809859542](https://user-images.githubusercontent.com/20875906/31495142-aea0eafe-af56-11e7-948e-81ecf409d2ec.png)

As you can see in the image, instead of one newline, it will create three newlines (one extra inside the quote and two outside the quote).

**Comment by bmarty** [comment]
this issue is fixed now
