### ISSUE TITLE
cannot join #Furnet_#S:spydar007.com

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1678]
reported by @mikaela:disroot.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1320

0-16 08:26:28.156Z 1 D/Room: Join the room !lONoDsVhriUeRDHnBr:spydar007.com with alias #Furnet_#S:spydar007.com
10-16 08:26:28.156Z 1 D/RestAdapterCallback: Trigger the event [joinRoom : roomId #Furnet_#S:spydar007.com]
10-16 08:26:28.259Z 1 D/RestAdapterCallback: ## failure(): [joinRoom : roomId #Furnet_#S:spydar007.com] with error 404 Not Found
10-16 08:26:28.260Z 1 E/Room: join onMatrixError Room alias #Furnet_#S:spydar007.com not found

**Comment by Mikaela** [comment]
Background information:

Furnet bridge is private as it doesn't have I-line yet. Joining everywhere happens by `!join #S` in private where `#S` is the channel.

I have been in the room previously, but left, and AFAIK the room alias in question never existed and is not supposed to exist, so I have no idea where Riot Android takes it.

If I understood @Spydar007 correctly, the same issue has affected Riot iOS, but has been fixed.

On Riot Android, I was able to accept the exact same invite.
