### ISSUE TITLE
background sync is frequently triggering after update

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1686]
reported by @ishitatsuyuki:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1279

**Comment by ishitatsuyuki** [comment]
Wait, wasn't that resolved with an update?

**Comment by ishitatsuyuki** [comment]
I mean, a3b52f0.

**Comment by ylecollen** [comment]
"Listen for events" does not means the background sync is enabled.
So, we misunderstood each others.
