### ISSUE TITLE
Don't recieve notifications if smartphone is in doze mode.

### ISSUE THREAD

**Issue by Nostradamos** [vector-im/riot-android#1694]
Even not when it get's waked up again. Have to open the app to see if i got new messages.
At the same time i recieve all whatsapp/telegram notifications.

**Comment by ylecollen** [comment]
@Nostradamos 
Google play or fdroid version ?
Could you send a bug report ?

**Comment by Nostradamos** [comment]
Google play, sent a bug report some days ago, but can send one again. Will do so as soon as this error occurs again.

**Comment by Nostradamos** [comment]
Okay maybe it's worth to note that i own a huawei phone.
It's possible that this is the problem:
https://medium.freecodecamp.org/why-your-push-notifications-never-see-the-light-of-day-3fa297520793

**Comment by Ramaraju1992** [comment]
@Nostradamos have you managed this issue? if so, please let me know how you have done...
