### ISSUE TITLE
Vector camera app only autofocus when taking the picture

### ISSUE THREAD

**Issue by saintger** [vector-im/riot-android#1704]
The native camera app continuously autofocus, which allow to take the picture only when things are in focus.
The Vector camera app only autofocus when taking the picture, which introduce a small delay before the picture is taken.

It would be better to have the same behavior as the native camera app.

Tested on Motorola G5S with Android 7.1.1 and riot-android v0.7.03

**Comment by ylecollen** [comment]
it would be better to use the device camera app.

**Comment by bh-e** [comment]
Another thing I noticed is , there is no option to on/off flash in riot native camera.

**Comment by ylecollen** [comment]
the riot camera app is limited to the minium functions set.
you have to use the device camera app to have all of them : it manages many other features
