### ISSUE TITLE
Calls on sony tablet don't have sound from other device

### ISSUE THREAD

**Issue by ASMfreaK** [vector-im/riot-android#1709]
I have a Sony SGP312 and it does not play soun from other devices when called. The sound from mic from the tablet is going nicely though.
I tried attaching heaphones with no result whatsoever. Normal playback from other apps works as expected (tested on youtube).

**Comment by ylecollen** [comment]
@ASMfreaK 
could you test the latest develop version ? i improved the calls management.

**Comment by ASMfreaK** [comment]
Latest release from Android market fixed this bug.
