### ISSUE TITLE
Eats battery after video call

### ISSUE THREAD

**Issue by inducer** [vector-im/riot-android#1715]
On version 0.7.03 from F-Droid. After I complete a (single-party) video call, Riot starts using lots of power, to the point of easily leading the Android battery stats.

I'm on LineageOS 14.1 on a OnePlus 5 on the November 6 2017 nightly build.

**Comment by ylecollen** [comment]
@inducer 
i don't have such issue on my side : could you send a bug report the next time you have it ?

**Comment by inducer** [comment]
Will do.

**Comment by inducer** [comment]
Just submitted an in-app report with logs referencing this issue. Here's a screenshot of the Android battery stats blaming Riot for 36% of battery use:

![screenshot_20171113-002927](https://user-images.githubusercontent.com/352067/32712372-cfca5ff0-c809-11e7-94d6-3794080ac40b.png)

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1498

**Comment by ylecollen** [comment]
11-12 20:10:52.739Z the call is started
11-12 20:29:01.773Z the call is ended
11-12 20:30:37.974Z 16683 E/Memory usage: -----------  app suspended -----------------
11-12 20:30:39.836Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorSettingsActivity@d72481d -----------------
11-12 20:33:19.277Z 16730 E/Memory usage: -----------  app suspended -----------------
11-12 20:36:33.370Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorSettingsActivity@d72481d -----------------
11-12 20:36:49.131Z 16747 E/Memory usage: -----------  app suspended -----------------
11-12 20:36:49.949Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorSettingsActivity@d72481d -----------------
11-12 20:38:03.778Z 16758 E/Memory usage: -----------  app suspended -----------------
11-12 20:38:21.971Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorHomeActivity@be9090 -----------------
11-12 20:38:49.618Z 16768 E/Memory usage: -----------  app suspended -----------------
11-12 20:48:51.575Z app is killed

11-12 20:49:56.351Z app is restarted
11-12 20:50:48.299Z 744 E/Memory usage: -----------  app suspended -----------------
11-12 20:51:21.966Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorSettingsActivity@fcfc610 -----------------
11-12 20:51:29.357Z 752 E/Memory usage: -----------  app suspended -----------------
11-12 22:58:18.361Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorSettingsActivity@fcfc610 -----------------
11-12 22:58:33.168Z 875 E/Memory usage: -----------  app suspended -----------------
11-12 23:04:21.046Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorRoomActivity@d121b1 -----------------
11-12 23:04:44.197Z 903 E/Memory usage: -----------  app suspended -----------------
11-13 00:13:19.771Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorRoomActivity@fd5302d -----------------
11-13 00:13:29.079Z 953 E/Memory usage: -----------  app suspended -----------------
11-13 01:04:41.539Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorRoomActivity@fd5302d -----------------
11-13 06:24:08.215Z 1320 E/Memory usage: -----------  app suspended -----------------
11-13 03:03:15.585Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorRoomActivity@c023a16 -----------------
11-13 03:03:56.958Z 1118 E/Memory usage: -----------  app suspended -----------------
11-13 03:16:39.489Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorRoomActivity@c023a16 -----------------
11-13 03:16:45.452Z 1129 E/Memory usage: -----------  app suspended -----------------
11-13 06:24:02.396Z 1 E/Memory usage: -----------  app resumed with im.vector.activity.VectorRoomActivity@c023a16 -----------------
11-13 06:24:08.215Z 1320 E/Memory usage: -----------  app suspended -----------------

**Comment by ylecollen** [comment]
@inducer 

do the foreground / background times make sense ? you have to do -6 to have your local time.

Is it the first time your have this issue ?

**Comment by ylecollen** [comment]
-> The 10s delay between sync requests seems kept (ie there is no sync without this delay).
-> the call seems properly hang up : the webrtc call objects are properly released.

i have no idea.

**Comment by inducer** [comment]
Any ideas as to something I could observe (alive threads? Increased log levels?) when riot is in this state? It seems pretty reproducible.

**Comment by ylecollen** [comment]
i don't reproduce it on my side.

**Comment by ylecollen** [comment]
@inducer 
Do you have a device with an "official" ROM ?

**Comment by inducer** [comment]
No, [sorry](https://www.androidcentral.com/oneplus-responds-data-collection-concerns). That said, LineageOS is a generally high-quality AOSP derivative with strict [code review and quality control](https://review.lineageos.org/). I have a high degree of confidence that the OS does the right thing. I can try and test on a Samsung S3 with Lineage though.

**Comment by inducer** [comment]
Another possible difference is that I do not have Google Mobile Services ("GMS") installed on any of my devices.

**Comment by ylecollen** [comment]
@inducer 
could you try the latest develop version ? 
you can find the latest build at https://matrix.org/jenkins/job/VectorAndroidDevelop/.
You will need to uninstall your app before installing the develop one.

I fixed 2 issues which might explain your battery draining issue
https://github.com/matrix-org/matrix-android-sdk/commit/6028b1db9f60d8ed9cba8cd9d79d5d384224d728
https://github.com/matrix-org/matrix-android-sdk/commit/77536ea62dd1b24a1a119b75885963551c3e100c

**Comment by inducer** [comment]
Thanks for looking into this! Installed the dev build (thanks for that, too) and made a test video call. Will let you know if I observe battery drain later today.

**Comment by inducer** [comment]
Looks like that did it! Thank you very much for your help.
