### ISSUE TITLE
[query] How can I minimise data costs?

### ISSUE THREAD

**Issue by kwill** [vector-im/riot-android#1716]
**User story:** I am an everyday user switching to Riot/Matrix for all my messaging. I want to run Riot Android over mobile data (when wifi is not available), so I can receive Matrix messages whenever I would normally be able to receive smses.

**Query:** The idea of leaving a mobile data app running all the time sounds expensive. How can I minimise data use, while still receiving messages wherever I am?

**Comment by ylecollen** [comment]
@kwill 
there is a data save mode but it cannot be switched according the network

**Comment by kwill** [comment]
Clarified the wording of the user story (it's not meant to imply switching modes based on network).

I can't find the data save mode :man_facepalming: how do I enable it?

**Comment by Nostradamos** [comment]
@kwill 
> I can't find the data save mode :man_facepalming: how do I enable it?

You can find it in settings in the experimental section. It's where you can also activate jitsi/matrix apps.

**Comment by kwill** [comment]
Ah, now I see it - thanks! :+1:

**Comment by rubo77** [comment]
What exactly does the data save mode do?

I cannot find a manual for Riot.

**Comment by rubo77** [comment]
I got an answer in the matrix "Riot Android" chat by FAQBot:

> Data save mode applies a specific filter so presence updates and typing notifications are filtered out. You will no longer see typing notifications. It does not affect notifications.
> 
> You can generally expect Riot to consume less data in this mode. How much is something you'll have to measure and exeriment with yourself. To achieve further data savings, you can also disable the sending of typing notifications in settings.
