### ISSUE TITLE
crashed while selecting a notification sound

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1731]
reported by @alphapapa:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1436

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1446

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1447

**Comment by alphapapa** [comment]
Well, that's handy.  That's me, if you need any more info.

**Comment by ylecollen** [comment]
@alphapapa 
could you provide me the steps to reproduce ?
1- you tap to select a notification sound
2- a window is opened
3- you select one
4- the window is closed
5- the app is crashed ?

**Comment by alphapapa** [comment]
I just tried it again and it didn't crash.  The only difference I can think of is that, at the time, I was trying to add new notification sounds to the filesystem so I could use them in the app, and they hadn't shown up in the list yet, so I was killing the app and restarting it several times in a row, hoping they would show up.

Maybe it was a fluke.  I'll report again if it happens again.  Thanks.
