### ISSUE TITLE
Go offline without signing out

### ISSUE THREAD

**Issue by kwill** [vector-im/riot-android#1741]
**User story:** I am an everyday user. I don't want to take any messages or calls right now. Later I want to launch Riot again and have it pick up where I left off (including receiving messages/notifications from while I was away), so that my user experience is seamless.

**What I tried:** I picked "hamburger menu" then "sign out". But when I launched Android Riot later, I had to enter my credentials again and I had a new Device ID, so I had to re-establish trust with my contacts and other devices. Luckily I don't have many friends.

**Proposed solution:** Make an explicit option to simply terminate the process. Separate this from the decoupling procedure (flushing credentials and device ID). This could be implemented as:

* "Sign out" terminates the process, "Decouple" performs the decoupling, or
* "Go offline" terminate the process, "Sign out" performs the decoupling (current behaviour)

**Proposed solution 2:** Have a "Mute" option, where the process continues to run in the background but does not alert the user when new messages/calls arrive, and doesn't do anything to indicate to the caller that the callee is available. Would also need an "Unmute" option.

**Workaround 1:**
* Switch off the phone
* ...not suitable if there are other things I want to do

**Workaround 2:**
* Visit Android menu
* Long hold Riot icon
* Drag Riot icon onto "App info"
* Select "Force stop"
* ...not suitable for an everyday user

**Comment by ylecollen** [comment]
@kwill 
you can disable the notification on your device only.

**Comment by kwill** [comment]
Thanks. I found the options to disable notifications "for this account" and "for this device" which seem to achieve the effect I want. These functions are important enough that I'd suggest that they are made more immediately accessible (at the same level as "Settings", not within "Settings").

**Comment by ylecollen** [comment]
we plan to have a simpler design for the settings
