### ISSUE TITLE
"URL must start with http[s]://"- forcing an identity server?

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-android#1743]
Hi,

setting up an account without identity server I get "URL must start with http[s]://" and can not log in without providing at least "https" in the `Identity Server` field.

Would you consider to change this behaviour so that one can set up an account _without_ providing an identity server without getting errors?

Thx!

**Comment by ara4n** [comment]
this is a thinko on our side - you should absolutely be able to use Riot without specifying an IS.

**Comment by saljut7** [comment]
Great, I will try again after the next riot update.

**Comment by zwieberl** [comment]
I also ran into this issue. Any updates on this?

**Comment by trillerpfeife** [comment]
It's anoying but you can just enter https:

**Comment by bmarty** [comment]
Should be fixed now (#2357 )
