### ISSUE TITLE
images inserted via `![](mxc://<hs>/<cid>)` are not displayed

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#1753]
When you insert an already posted image via a `![](mxurl)` it gets rendered on riot-web as expected but android does not show anything. As reference: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$151065487645gfRnn:msgs.tk

**Comment by Matrixcoffee** [comment]
For security reasons, external images are not shown inside messages. However, if the image url starts with mxc:// it is actually safe to load and display.

**Comment by walle303** [comment]
#1733 covers this

**Comment by ylecollen** [comment]
duplicate of #1733
