### ISSUE TITLE
Key exchange issues 

### ISSUE THREAD

**Issue by Nostradamos** [vector-im/riot-android#1760]
When i updated Riot Android over Google Play, i somehow lost all my e2ee keys so i couldn't read the encrypted messages. Normally the key exchange window should popup, but it didn't or I accidentially dismissed it. However i couldn't force reopen it, not by clicking on a "unencryptable message" nor over settings or something. Also whenever i sent a message from my mobile, all other riot clients didn't recognize the device, they just said "unknown device".
However I did a logout and logged in again, the keyexchange window popped up, exchange worked like a charm and now everything works. Still want to report this.

**Comment by ylecollen** [comment]
@Nostradamos 

-> as i explained in Android room
If you dismissed the dialog, it won't be displayed anymore.

-> However i couldn't force reopen it, not by clicking on a "unencryptable message" nor over settings or something
The dialog is opened on the requestED side not the requestER one.
There is no mechanism to manage the requests from a device. (the pending ones are stored).

->  all other riot clients didn't recognise the device, they just said "unknown device".
i don't understand this issue. It is not related to the keys exchange.

The UI will be updated to reduce the number of dialogs and simplify the UX.

**Comment by Nostradamos** [comment]
> The dialog is opened on the requestED side not the requestER one.

This clarifies a lot, thank you :)
