### ISSUE TITLE
Video Conference UI

### ISSUE THREAD

**Issue by webcluesdev** [vector-im/riot-android#1761]
I am using the custom server of Matrix.

I want to integrate Jitsi in it like Riot's new version does.

Is there any change required on the server side?

I am able to make a call from default matrix SDK but I want to change UI of Video conference call. 

Is it possible to change UI of Jitsi's default layout for video conference?

Thanks in advance...

**Comment by ylecollen** [comment]
1- change on server side : i don't know

2- Is it possible to change UI of Jitsi's default layout for video conference?
We use JitsiMeetView which has its own UI (the camera switch buttons ...).
You will need to ask to https://github.com/jitsi/jitsi-android to find the way to customise it.
