### ISSUE TITLE
Implement intent filters or react to links to matrix.to / riot.im

### ISSUE THREAD

**Issue by kaiyou** [vector-im/riot-android#1766]
Most people will use matrix.to or riot.im links when referencing Matrix channels on other channels.
It would be interesting if the Android Riot app could react to the related intents, parse the link and open the proper channel in Riot directly.

There is some documentation about intent filters at the following uri: https://developer.android.com/guide/topics/manifest/data-element.html

**Comment by ylecollen** [comment]
@kaiyou 
it should work with matrix.to links. Did you test it with the latest release ?

see https://github.com/vector-im/riot-android/blob/master/vector/src/main/AndroidManifest.xml#L314

**Comment by kaiyou** [comment]
It does, sorry about my poor testing.
