### ISSUE TITLE
Username autocomplete is not consistent with desktop

### ISSUE THREAD

**Issue by impala2** [vector-im/riot-android#1767]
Followup to #1018

On riot-web, using `@` to autocomplete only fills in the username, while on riot-android it fills in the full username+server which is uncomfortably long on mobile devices with small screens. This is strictly only about same-server, unfederated contacts. I guess this behavior can stay for remote contacts. Backspacing after autocompletion is suboptimal.

Expected:

    @username

Getting:

    @username:matrix-server.com

**Comment by ylecollen** [comment]
we need the @username:matrix-server.com to manage the link.
The webclient manages a feature them as "Pill".
It is a planned feature on the mobile clients.

**Comment by impala2** [comment]
Excellent, thanks.

**Comment by bmarty** [comment]
pills are now supported on Riot Android
