### ISSUE TITLE
Jitsi integration with existing server

### ISSUE THREAD

**Issue by webcluesdev** [vector-im/riot-android#1768]
Hello,

I make a custom server of Matrix on my server. Now I want to add Jitsi support for video calling.

I tried with Riot application when I use matrix.org server then it redirects me to Jitsi's calling UI and when I use my custom server then it redirects me to traditional UI of the Matrix.

I need some help on the following question:

1) How can I add Jitsi to my custom server?
2) I need to change some code of my existing server or it will work without it?
3) Is there any way to integrate Jitsi into my application without launching new update?
4) If I need to change my server code then in which file I need to make a change?

Thanks in advance..:)

**Comment by ylecollen** [comment]
3- jitsi URLs are hard coded because it still in dev.

**Comment by webcluesdev** [comment]
Thanks for the comment.

**Comment by enannos** [comment]
Hello,

I have almost the same question and there seems to be not a complete docu explaining some details and providing some Infos.

Matrix Server is installed but I cannot find a way to implement the Jitsi videobridge.
I also run an Openfire Server which has the Jitsi implemented.

Thanks

**Comment by Radnik** [comment]
@webcluesdev 
Please post the solution, you mentioned it has been solved in `https://github.com/vector-im/riot-android/issues/1775`

Thanks,
Ivan
