### ISSUE TITLE
Use custom Jitsi server in application

### ISSUE THREAD

**Issue by webcluesdev** [vector-im/riot-android#1775]
Hello,

I am using custom Matrix server and want to use custom Jitsi server.Like "https://scalar.vector.im" sever is used in it.

I want to change the following line with my custom URL but not able to do.

`String url = "https://scalar.vector.im/api/widgets/jitsi.html?confId=" + confId + "&isAudioConf=" + (withVideo ? "false" : "true") + "&displayName=$matrix_display_name&avatarUrl=$matrix_avatar_url&email=$matrix_user_id";`

Is it possible?

Is any other installation required without Jitsi for this change?

which step should I follow to achieve this function?

Thanks in advance..:)

**Comment by ylecollen** [comment]
@webcluesdev 
We hard-coded the value because it was our only jitsi server.

You could make your own fork.

**Comment by webcluesdev** [comment]
Thank you. I found the solution.

**Comment by Radnik** [comment]
@webcluesdev

can you share the research + solution?.
we are up to have our own Jitisi meet server

Ivan

**Comment by wjhtinger** [comment]
@webcluesdev Can you share your solution?

**Comment by wjhtinger** [comment]
@webcluesdev Can you share your solution? And how to you set up your own Jitsi server？
