### ISSUE TITLE
Confirm that you actually want to make a call, before making a call.

### ISSUE THREAD

**Issue by jcgruenhage** [vector-im/riot-android#1778]
It easily happens that you accidentally hit the call button, so having an alert dialog to confirm this before actually placing the call would be great.

**Comment by ylecollen** [comment]
https://github.com/vector-im/riot-android/commit/e1ba4a62bd409e99a8d7d1cb46f9685c25e9ea7b

**Comment by Matrixcoffee** [comment]
It looks like this has regressed, or was consciously backed out. Please reopen.

**Comment by jcgruenhage** [comment]
I've just checked the source code for the current develop branch, afaict, this warning still exists.
