### ISSUE TITLE
Riot android is smashing the battery #1 consumer!

### ISSUE THREAD

**Issue by wsdookadr** [vector-im/riot-android#1779]
Battery levels plunging at a rate of 1% every 2 min on my phone because of the riot android app.
I tried switching more channels to the low priority section, I only use about 8-9 channels.

In `Settings > Battery > Consumption level` riot-android wins  `#1` place in terms of battery usage, with 13.98% , it's just smashing the battery, at this rate I would expect the battery to die after less than 60min.

Obviously, I would prefer the app to consume as little as possible so I can follow some channels and
conversations throughout the day (not new, has been [discussed here before](https://github.com/vector-im/riot-android/issues/616#issuecomment-323143938)).

Maybe you could try using [battery historian](https://developer.android.com/studio/profile/battery-historian.html) or other battery profiling methods can be used to find ways to reduce battery consumption.

Thanks!

**Comment by richvdh** [comment]
dup #616
