### ISSUE TITLE
F-Droid version gets killed

### ISSUE THREAD

**Issue by BuZZ-dEE** [vector-im/riot-android#1782]
Hi, the F-Droid version gets killed after some time on my One Plus 3. The "listening for events" message is gone and then I get the splash screen again, if I restart the [app](https://matrix.org/jenkins/job/VectorAndroidDevelop/1772/). ["Run in background"](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%2415095379432445342FdOos:matrix.org) is [allowed](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%2415095379432445342FdOos:matrix.org).

**Comment by nidico** [comment]
Note that F-Droid still contains the outdated version 0.7.3. So your issue might be fixed once updated to 0.7.4.

**Comment by BuZZ-dEE** [comment]
I also tried https://matrix.org/jenkins/job/VectorAndroidDevelop/1772/

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1617

**Comment by ylecollen** [comment]
There is nothing in the logs which tells that the service is killed (i.e the "listen for events" notification).

**Comment by ylecollen** [comment]
BgDetect is a part of OxygenOS.
It kills background service but it seems also killed foreground services.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1385

**Comment by BuZZ-dEE** [comment]
I have another app (Delta Chat), which runs in foreground and it is not killed. What is the difference?
