### ISSUE TITLE
opt out of analytics

### ISSUE THREAD

**Issue by 4nd3r** [vector-im/riot-android#1798]
it's my personal problem, but because current default is opt-in, i choose to opt-out. sorry.

app should ask user confirmation for that on first launch or when there are change in anonymous analytics (similar how syncthing project is doing it). also there is not even a way to preview "anonymous analytics".

**Comment by ylecollen** [comment]
@4nd3r 
We use piwik which is really anonymous thing (more than google analytics).

**Comment by 4nd3r** [comment]
doesn't matter who "owns" collected data.

problems here are default opt-in without warning and no data preview.

**Comment by ylecollen** [comment]
About "opt-in without warning", i will ask.
There is no way to have data preview.

**Comment by ara4n** [comment]
we are shifting to opt-in for fdroid, at least. i'd prefer to avoid it for google play, given having usage stats are absolutely vital in terms of understanding how folks are using (or failing to use) the app - as well as helping us justify funding if there's as much stats as possible about the size of the userbase (including those not using the matrix.org HS).

In terms of what it tracks: https://github.com/vector-im/riot-android/blob/f8cea1c50d994bd3a4ab062df04f6a635b6d3927/vector/src/main/java/im/vector/VectorApp.java#L1255-L1290

**Comment by ArchangeGabriel** [comment]
@ara4n I’m perfectly fine for keeping it opt-out in Google Play (I mean if your using Google Play in the first place, you shouldn’t be worried about _internal_ analytics of an app), but do you have any ETA regarding switching to opt-in for F-Droid version? I’ve not seen a commit for this currently.

**Comment by bmarty** [comment]
Opt-in for every body thanks to GDPR since 0.8.9 :)
