### ISSUE TITLE
Riot often chokes on messages

### ISSUE THREAD

**Issue by jean** [vector-im/riot-android#1799]
Very often I see messages getting stuck without being sent. 
When I kill and restart Riot, I'm prompted "resend or cancel". 
When I resend, some messages make it out. Sometimes I need to kill and restart many times before all the messages have been sent. 
Is this a known issue? 
![screenshot_20171210-212436](https://user-images.githubusercontent.com/84800/33805815-3e1d6004-ddf1-11e7-9213-ca60870d5e9a.jpg)

Riot version 0.7.05

**Comment by ylecollen** [comment]
@jean 
it is not a known issue.
When an event sending failed, we try to resend it 3 times (with delay between the requests : it can require more time you could expect. 
Please send a bug report the next time you have this issue : i will be able to tell you what was wrong.
We might have an edge case we did not think about.

**Comment by jean** [comment]
Here's one that's stuck at the moment, is there other info I should include? 
![screenshot_20171212-180043](https://user-images.githubusercontent.com/84800/33881234-bc46bd6a-df66-11e7-9ad2-78388d719b1a.jpg)

**Comment by jean** [comment]
.. and subsequent messages too, until I kill/restart/resend.

**Comment by ylecollen** [comment]
@jean 
the message is encrypting so it might required several long.
a bug report would really help (there is an entry in the home sliding menu)

**Comment by jean** [comment]
Ah a bug report through the app, not here!
I didn't realize there's a menu entry for that.

> the message is encrypting so it might required several long.

Well, yes, but this message and all subsequent messages don't send, even if
I wait for hours, but they send immediately if I kill, restart, and hit the
resend button.

I'll send a bug report through the app next time.

-- 
jean                                              . .. .... //\\\oo///\\

**Comment by RX4NT9UP** [comment]
I'm also having this issue. I tried to submit the requested bug report and got a 500 error. It might be relevant that I don't get great reception at work, though other messengers seem to send reliably and I was able to (slowly) use the web right afterwards.

![screenshot_20171214-132117](https://user-images.githubusercontent.com/34555085/34015213-9ecf025c-e0d2-11e7-9c4a-25f8a772d1c7.png)
![screenshot_20171214-132026](https://user-images.githubusercontent.com/34555085/34015218-a2a095b2-e0d2-11e7-882f-2d80fe6a413a.png)

**Comment by ara4n** [comment]
@RX4NT9UP this is really weird. We see no HTTP 500 errors in the rageshake server logs. Are you sure your wifi was working at all? (e.g. could it be stuck on an access point which is trying to prompt with a login page?)

**Comment by RX4NT9UP** [comment]
It was accessing directly through metropcs (T-mobile network). wifi is off, I don't even have it here. I was able to send a bug report on another attempt, but it wasn't after unsent messages. I will have to do some more tests to see if that has something to do with it. I agree, weird.

**Comment by ara4n** [comment]
bug reports contain at least a few hours of logs typically, so hopefully the later one will be sufficient.

**Comment by ylecollen** [comment]
12-14 21:11:41.249Z 1 D/RestAdapterCallback: ## failure(): [downloadKeysForUsers] with error 500 Internal Server Error
12-14 21:11:41.250Z 1 E/MXDeviceList: ##doKeyDownloadForUsers() : onMatrixError Internal server error
12-14 21:11:41.252Z 1 E/MXDeviceList: ## refreshOutdatedDeviceLists() : ERROR updating device keys for users [haskinsem@gmail.com, @brightstar:matrix.org, @maxrunner:matrix.org] : Internal server error

**Comment by ylecollen** [comment]
i suspect that haskinsem@gmail.com triggers the internal error.

**Comment by ylecollen** [comment]
The bug report error was triggered by a "Timeout error".
The default error message is "internal error".

**Comment by jean** [comment]
What was the conclusion here?
I get these stuck messages on fast work WiFi too.

**Comment by ylecollen** [comment]
@jean 
could you test our develop version ?
it seems there is at least one email address in the members list.

**Comment by jean** [comment]
Sure, I'll install the dev version. Where do I get it, I didn't see on Play
Store or F-Droid.

**Comment by ylecollen** [comment]
@jean 
https://matrix.org/jenkins/job/VectorAndroidDevelop/
you will need to uninstall your application before installing this one.

**Comment by RX4NT9UP** [comment]
I have no idea how that email got in there. I have never added it and in fact they don't have riot/matrix. I'm not even sure how I would get it in there. I am testing the develop version but since the problem was intermittent I will have to report back.
