### ISSUE TITLE
Expected status header not present

### ISSUE THREAD

**Issue by nja0087** [vector-im/riot-android#1802]
Update to 0.7.06 today causes issue "Expected ':status' header not present. Previous version is fine. Log submitted via app

Edit: In the meantime is there an easy way to get the older version back? It's not on APK mirror

Edit2: Error still occurs after clearing data/cache and going to the main screen. Can't even log in.

**Comment by ylecollen** [comment]
@p0087 
see https://riot.im/app/#/room/#riot-android:matrix.org/$151274623520TiZVU:msgs.tk

it seems that  nginx 1.13.6 is not compliant with Riot.

**Comment by p0087** [comment]
I fail to see how nginx is at fault of the error occurs on the login screen, and was fine on the previous version. A similar issue happened to davdroid a couple months back and was rectified by updating okhttp iirc

**Comment by p0087** [comment]
To your edit: this regression makes riot unusable presently. Can you provide an apk of the previous version?

**Comment by ylecollen** [comment]
@p0087 
you could also use nginx 1.13.5.
else you have our jenkins https://matrix.org/jenkins/job/VectorAndroid/

**Comment by ylecollen** [comment]
We know we need to update OkHttp / retrofit but we don't have enough hands to do everything :
It implies to refactor many many things.

Some users requested an update to manage http/2 servers (+ ssl issues fix), so i updated the OkHttp lib to manage it.

**Comment by krombel** [comment]
The issue is tracked in the nginx bug reports [here](https://trac.nginx.org/nginx/ticket/1397)
Currently it is possible to use the current stable of nginx (1.12.2). That version has not yet implemented the feature that breaks OkHttp

**Comment by p0087** [comment]
I strangely still get the error disabling http2 on the server.

I know the jenkins builds are unsigned, but I can't install them, with an error about possible corrupt apk. What's causing this?

**Comment by ylecollen** [comment]
@p0087 
Another user @cg:matrix.dust-puppy.net disabled http2 on his server and it work on his side.

**Comment by p0087** [comment]
Yeah I checked the responses after removing the http2 directive, was still delivering http2 responses. It seems that nginx applies http2 not just for singular server blocks - https://superuser.com/questions/1094187/nginx-http-2-switch-to-http-1-1-testing. Infeasible for me to disable http2 on the server globally, so I'm without Riot until a new release.

**Comment by ylecollen** [comment]
@p0087 
you could use the version 1.12.2.
i don't think the next release will fix this nginx issue.

**Comment by storrgie** [comment]
I was unable to get nginx-mainline to work by removing the `http2` directives from _all server blocks_. Instead I had to move to nginx (1.22.2). It would be nice if we didn't have to drop back like this.

**Comment by ylecollen** [comment]
@storrgie / @p0087 
You are welcome to join our beta testers.
We don't know all the server configurations used by the matrix users.
It might avoid having such issue.

**Comment by p0087** [comment]
Is that via play store beta program? 
And yeah I fully understand running into unforeseen issues - I just wish I could download an older (signed) apk.

**Comment by storrgie** [comment]
@ylecollen I am in the beta program from what I can tell. The play store has a banner stating so. Was there a survey floating around for homeserver operators to respond to about what they are proxying with?

**Comment by krombel** [comment]
> Was there a survey floating around for homeserver operators to respond to about what they are proxying with?

@storrgie There is [this strawpoll](https://www.strawpoll.me/14605107) which got created after it seems that there might be more people affected. I think you are referring to that one

**Comment by ylecollen** [comment]
@storrgie / @p0087 / @krombel 
The release 0.7.07 uses the older OkHttp version.
it will be kept until we have time to upgrade OkHttp to the latest version.

**Comment by storrgie** [comment]
@ylecollen thanks! Is 0.7.07 only in the beta channel, or is it stable? I'm unsure of how to tell what channels there are from the play store interface.

**Comment by storrgie** [comment]
@ylecollen thanks! Is 0.7.07 only in the beta channel, or is it stable? I'm unsure of how to tell what channels there are from the play store interface.

**Comment by krombel** [comment]
@storrgie The current stable release on the play store is 0.7.07 so I expect it to be on the stable channel (as well)

**Comment by storrgie** [comment]
@ylecollen I appreciate the change. I've moved back to my original configurations.
