### ISSUE TITLE
Option to disable notifications for low priority rooms

### ISSUE THREAD

**Issue by sim6** [vector-im/riot-android#1807]
Please, could you add an option to disable notifications for low priority rooms?

**Comment by koo5** [comment]
this goes for the web ui as well

**Comment by koo5** [comment]
i just realized what the trick is, notification settings are under a "..." icon next to each room in the room list

**Comment by sim6** [comment]
@koo5 also long tap to rooms in home screen. But I mean a general setting for all rooms in low priority and maybe also for other tags.

**Comment by bmarty** [comment]
Long tap on Room to change notification behavior
