### ISSUE TITLE
there is a "synchronizing" task stuck in my Android notification area. It only goes away when I force kill the app and reappears with a hour or so :/

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1816]
reported by @luto:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1738

Reported on an android 8.1 device.

**Comment by ylecollen** [comment]
I suspect this foreground notification is never dismissed because the app is killed before having time to perform a sync.

**Comment by luto** [comment]
Hi there, I am that @luto ;)

In case I can supply any further information to debug this just ping me. I am also comfortable with using adb or similar tools, if necessary.

**Comment by ylecollen** [comment]
https://github.com/vector-im/riot-android/commit/e72bc5616b002bf753bdb680c11f319be6876b9d

**Comment by luto** [comment]
@ylecollen thank you very much! :)

**Comment by ylecollen** [comment]
@luto 
it might also happen when the application is restarted in background (it was your use case in few times)
the "synchronizing" notification is displayed while it is restarted but it should not be displayed for a long time.
Since android 8, this notification cannot be hidden.
