### ISSUE TITLE
F-Droid version build process

### ISSUE THREAD

**Issue by Bubu** [vector-im/riot-android#1829]
Thanks for the build scripts @ylecollen, this improves things immensely. There are still a few more points to solve:

* https://github.com/matrix-org/matrix-android-sdk/issues/227
* adapting the scripts to not use the matrix-sdk/libs/*.aar files
* making the scripts a bit more controllable on where it finds the source code for each dependency and NDK, etc.

-> The last two points I have mostly done locally Just need to clean this up and I can submit this as a PR.

What I'd like to discuss as well is dependency versioning. I guess right now the dependency versions for matrix-sdk and olm are always latest released version as of $date-of-release of the riot version to be build? Can you encode this somewhere? This would make updating the f-droid version much easier and less error prone. (btw. while we are on this, the matrix-sdk repo seems to be missing the last two or so tags?)

And what about the jitsi dependency? Which version to use there? I guess if they have nothing else a commit hash of the version you built will do.

**Comment by ylecollen** [comment]
@Bubu 
the android SDK issue is fixed on our develop branch.

**Comment by ylecollen** [comment]
@Bubu 
* adapting the scripts to not use the matrix-sdk/libs/*.aar files
If you don't wan't to compile the matrix SDK libs, you could use "set_debug_env.sh".
This script adds the matrix sdk project to the riot workspace.

**Comment by ylecollen** [comment]
@Bubu 
* About the lib versions
The application and the olm SDK versions are displayed in the application settings page (at the bottom).
The SDK version is only tracked in the bug reports.

* about jitsi, we use the latest one (with new issues of course)

**Comment by mytbk** [comment]
Can the jitsi support be dropped temporarily?

**Comment by shiftee** [comment]
@Bubu Just a reminder about this issue. Can you please clarify the "making the scripts a bit more controllable" point, and mention if the solutions to the other issues are satisfactory? Thanks

@ylecollen  Is it possible to provide non-gcm apk files for new releases until this issue is fixed?

**Comment by Bubu** [comment]
@shiftee I'd consider this issue solved for now. What I did in the fdorid metadata can be seen here: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.vector.alpha.txt#L265

There is certainly improvement potential but right now the assumptions made by @ylecollen's scripts and fdroid are quite different such that unifying them needs some more coordination.

I'd like to try it out like this for a while and see if it the build recipe changes too often I'll try to push certain things here. I.e. the list of jitsi related files to copy around might be such a thing.

**Comment by shiftee** [comment]
@Bubu Very good, thanks

**Comment by shiftee** [comment]
F-Droid builds seem to be flowing again, does that invalidate this issue?

**Comment by Bubu** [comment]
I'll close for now.
