### ISSUE TITLE
Riot-Im, Google play version 0.7.07 Accelerometer use

### ISSUE THREAD

**Issue by angrierhorse** [vector-im/riot-android#1830]
I have riot 0.7.07 installed on an MT6572 device.  I am seeing battery drain associated with Riot polling the accelerometer (I can see this with the "better battery stats" application).  As far as I can tell the only thing Riot needs the accelerometer for is the rather silly "shake to submit bug report"  feature.

Apart from this why would Riot need to access to the accelerometer?  Screen rotation is handled by the OS. 

How do I disable Riot accessing the accelerometer?  This is a needless "feature" that is wrecking my battery life!

**Comment by wsdookadr** [comment]
FWIW, I fully agree with this. Riot, a chat app, should only use the sensors it needs to, and should make judicious use of battery.
