### ISSUE TITLE
Feature Request: Support Split-screen mode

### ISSUE THREAD

**Issue by yookoala** [vector-im/riot-android#1832]
It would be really handy for an IM app to support split screen mode so user may use it at the same time as using browsers or other apps.

Since that Android feature came out, I found me using it all the time with half screen of IM app (e.g. WhatsApp) and half screen browser / YouTube. It saves time to switch to-and-from other apps while pending chat responses or looking for information to enhance the chat contents.

**Comment by bmarty** [comment]
FTR:
Check that camera integration still work when screen is split

**Comment by sindelar-fr** [comment]
This is intentionally disabled since v0.7.01. See #1557.

**Comment by bmarty** [comment]
I reactivate the feature. Note that if some Activity crashes, we can still disable this only for the related Activity

**Comment by bmarty** [comment]
One year later, it's finally back in the next release!
