### ISSUE TITLE
Background of textinput is green 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1836]
reported by @monkz:synapse.monkz.de
https://github.com/matrix-org/riot-android-rageshakes/issues/1760

Jolla device (Sailfish OS)

**Comment by monkz** [comment]
Occurence is non-deterministic
(btw. that is my rageshake report - thanks for creating a issue from it)

**Comment by bmarty** [comment]
@monkz do you still observe this strange green issue?

**Comment by bmarty** [comment]
Not reproduced

**Comment by monkz** [comment]
sorry the notification about this issue was lost in a wave of other mails.
I don't observe this issue anymore
