### ISSUE TITLE
Android Voice Chat clients only ever connect to Jitsi, can lead to two simultaneous voice conversations in same channel

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-android#1847]
I've been doing some testing of Riot on Linux (desktop), Web, and Android.

When I have a conference call via Linux and Web, all people involved join the same voice chat (Jitsi widget disabled in this case). We can all hear each other just fine.

When I then log onto my Android Riot app, join the same channel, and try to join voice only, it then adds the Jitsi widget (without asking), and starts a Jitsi conference, instead of joining the existing voice conference (is it freeswitch? I'm not sure).

This effectively leads to fragmentation of voice conferencing, in that two simultaneous voice conferences are existing for the same channel, and are not bridged whatsoever (they cannot hear each other).

Furthermore the Android app, most of the time, by default starts a VIDEO conference when VOICE was tapped on. This is really annoying, and not working as intended.

Riot Mobile v0.7.07 (G-3de8811d)
Android 7.1

Riot Desktop 0.13.3, Ubuntu 17.10

**Comment by BloodyIron** [comment]
Also, when a user does not have widget permissions, and they try to join voice on Android, they get the error "You need permission to manage widgets in this room". Effectively making it impossible for non-admins to do ANY voice or video conferencing in a channel without the jitsi widget enabled. There are cases where I want to disable video conferencing, but allow voice conferencing for a channel, so this is a pretty substantial breaker.

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1800

**Comment by BloodyIron** [comment]
I don't have access to that rageshake, but I suspect it might be from me? ;) Does closed mean it's fixed? I am confused here, since the link 404's for me. (I suspect lack of access for me)

**Comment by BloodyIron** [comment]
@ylecollen can you add some more context here please? I don't have access to that rageshake.
