### ISSUE TITLE
Need a way to quit the android app nicely

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-android#1848]
Right now I need to force stop the riot app to close it without signing out. It's quite good at running in the background and giving me notifications, but there are times I want to just completely quit it for the time being.

However, I am not seeing a nice way to do that. Can we get a "Quit" menu option please? :)

**Comment by Matrixcoffee** [comment]
I believe this is implemented as per #1955. Also, dup of #1807.

**Comment by BloodyIron** [comment]
No, this isn't a dupe of #1807 as I also want the app to not consume my battery in that scenario, hence exit.

But yeah, looks like it might be coming in, yay!

**Comment by Matrixcoffee** [comment]
I am a dumb and typo'd the above message. 1087 instead of 1807. (Edited to fix.)

**Comment by BloodyIron** [comment]
LOL okay! Yeah, I see that now :D

**Comment by bmarty** [comment]
"Exit" in the main menu has been implemented

**Comment by BloodyIron** [comment]
Thanks for all involved! :D
