### ISSUE TITLE
Need a way to set "loud" notifications per-room on android, not just web

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-android#1849]
I'm testing some of the finer points of notifications in the riot ecosystem.

On Web/Desktop I can set a room to "All messages (loud)", and a few other settings. But I can't find settings like this on Android.

One thing I do like is that I set a channel to "loud" on Desktop, and my Android app reflects that, so cool! So if we could get a way to set "loud" on Android too, I think that would be really helpful for refining notification settings. Plus, I think most people won't realise that the desktop/web settings will persist to android.

**Comment by Bubu** [comment]
I think this is fixed in https://github.com/vector-im/riot-android/releases/tag/v0.8.1 now.

**Comment by BloodyIron** [comment]
@Bubu sure looks like you're right! :D
