### ISSUE TITLE
Push completely broken in f-droid version

### ISSUE THREAD

**Issue by paskalito** [vector-im/riot-android#1854]
this most likely have happened already some versions ago but only now i got eneugh time for testing as well as another device.

on the new device. (s3 original software) i installed riot enabled sync and start at sys start. and even despite i got the "waiting for events" banner in the notification drag down thinggy now message and no call was delivered.
only if you opened the app.

same for my s3 Android 7 lineageos nothing ever gets delivered (or sent if i send stuff offline ( which i usually do)) in the background. i alsways need to open the app. which draws it close to useless for me.

on the other phone  i reinstalled it from playstore with google push it seems to work very well. i dont have that possibility on my phone.

and all these thing worked when i started using riot and tested everything out...
 

riot 0.7.03 as it is the most recent one in fdroid

**Comment by emixam150** [comment]
I confirm all this behavior on Nexus 5X android 8 with f-droid version 0.7.03.

**Comment by ArchangeGabriel** [comment]
AFAIK, the F-Droid version does not have GCM and thus push support (they would have to implement a replacement for GCM, which is possible but not done here, still AFAIK).

**Comment by ylecollen** [comment]
@paskalito @emixam150 
as @ArchangeGabriel said, there is no push mecanism like GCM.

Every 10 mins, there is a sync to retrieve the unread messages to trigger notifications.

Either you install the google play version on your device + MicroG.
Or you customise the delay between syncs

**Comment by paskalito** [comment]
@ylecollen 
Thanks, i noticed that i have refused rights to riot to push anything to me ( android system notification wise) because i really didn't understand that system first..)
so now i get notifications ( also with delay)
2 things.
1. can we please then add a notification event for whenever someone tried to call so at least all fdroid users would get a notification that someone tried to call them?
2. since riot is ment to be decentral opensource e2e encrypted - so everything someone with human rights awareness wants. i think it would be very good to implement a directly from the server coming push mecanism. ( like imap idle or so)

tell me if i should start an issue for either of those
