### ISSUE TITLE
the capture button doesn't do anything in in-app camera app

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1866]
reported by @susurrus:matrix.org
unable to use Riot to take photos directly. I see the spinner when I try to use the camera and the capture button doesn't do anything. I can still send photos from my phone, but it's more of a PITA to use the system camera then select it in riot rather than taking the photo in Riot directly.

**Comment by ylecollen** [comment]
Notice it is already possible to use the android camera (there is a dedicated settings entry to enable it)

**Comment by Susurrus** [comment]
Where's that setting option and what's it called? I don't see anything about a camera in the overall settings menu.

**Comment by ylecollen** [comment]
![use native app](https://user-images.githubusercontent.com/8971031/34709423-8475d4e0-f517-11e7-91d5-9482735ce6de.png)

**Comment by ylecollen** [comment]
it is called "use native app".
It is available on google play version but the fdroid store one does not have it.

**Comment by Susurrus** [comment]
Okay, I'm using the fdroid version. And the in-app camera still doesn't work for me. Is there any other option I have for fixing this?
