### ISSUE TITLE
FAB menu dialog reacts without pushing OK

### ISSUE THREAD

**Issue by ishitatsuyuki** [vector-im/riot-android#1867]
The floating action button opens a dialog, and selecting items in the menu executes the action directly, despite the "OK" button there.

**Comment by ylecollen** [comment]
@ishitatsuyuki 
it is the default android behaviour.

**Comment by ishitatsuyuki** [comment]
No it isn't. You're implementing the event handlers wrongly.

As another way, you can remove the OK and cancel button.

**Comment by ylecollen** [comment]
@ishitatsuyuki 
A pr is welcome.
