### ISSUE TITLE
Feature request: add "don't erase keys" on logout

### ISSUE THREAD

**Issue by d1d4c** [vector-im/riot-android#1868]
Some people don't use cryptography on rooms due to this issue. Export and import keys file could not be strictly necessary whem you login and logout on the same device. Maybe adding a "don't erase keys" checkbox when you logout, could be a solution. Thanks!

**Comment by ylecollen** [comment]
@d1d4c 
It does not make sense for security reason.
Either you kill/leave the application to keep all the data
or you log out of the application and everything is deleted.

**Comment by d1d4c** [comment]
Thanks.

What I mean is just automate this. For example, when you login, just look for the keys file in the default dir and ask the user for its passwd. Does iit make sense to you?

**Comment by ylecollen** [comment]
@d1d4c 

the problem will be to define the "default dir" and the "default filename".

There is a pending feature to automatically backup to e2e keys server side so, at next login, the keys would be restored with the server data.

**Comment by d1d4c** [comment]
Thank you!
