### ISSUE TITLE
Swipe right on room view to act as 'back' button?

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1871]
> The only flaw in your mobile client which I would improve is absence of 'swipe to the right' gesture to get from the message dialog back to contacts list. You get so used to it in Viber and Telegram and in fact it's so intuitive! 

from email.

**Comment by Matrixcoffee** [comment]
Sounds like a dup of #1225 (current open) and #527 (implemented and backed out again).

**Comment by ara4n** [comment]
dup of https://github.com/vector-im/riot-android/issues/573
