### ISSUE TITLE
[UI] Send button not working

### ISSUE THREAD

**Issue by chevroulet94** [vector-im/riot-android#1876]
Hi there,

I experience a weird issue on many Android devices with the Riot.IM app. It's impossible to send message and/or file with the send button.

However, the only workaround I found so far is to disable the Markdown syntax in the app settings:
![markdown](https://user-images.githubusercontent.com/35290947/34762821-6d03a616-f5e9-11e7-8200-f8e087a2f066.png)

Is there any other to resolve this problem without disabling Mardown ?

Please note that I uninstalled, empty cache and trie F-Droid app several times without any success.

Thanks

Florian

**Comment by ylecollen** [comment]
@chevroulet94 
could you send a bug report ?

**Comment by chevroulet94** [comment]
@ylecollen I've already sent it ~ 1 hour ago before submitting this issue ;-) Cheers !

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1841

**Comment by ylecollen** [comment]
@chevroulet94 
it's weird : i don't reproduce your issue on my side.

**Comment by chevroulet94** [comment]
@ylecollen Yes I agree it's super weird... And like I said before the only workaround I found is to disable Markdown... BTW, you're link is not working on my side.

**Comment by ylecollen** [comment]
@chevroulet94 
The link is used to track your issue (on a private git repo).

**Comment by chevroulet94** [comment]
@ylecollen Ahhh ok I didn't know that ! Thanks for the info ;-)

**Comment by ylecollen** [comment]
@chevroulet94 
it looks like the markdown parser does not work on your device.
As we use a java -> JS bridge, it does not manage error code.

**Comment by ylecollen** [comment]
https://github.com/vector-im/riot-android/commit/98b5f3816272c96af9fc6e87f53dbac77448e3af

**Comment by ylecollen** [comment]
@chevroulet94 
Could you test our latest develop version and tell us if you still have the issue ?
thank you

**Comment by chevroulet94** [comment]
@ylecollen Of course I'll test with the DEV apk and let you know if it's better.

**Comment by chevroulet94** [comment]
@ylecollen Seems much better with this APK. It's working.

**Comment by ylecollen** [comment]
@chevroulet94 
could you send a bug report with this new APK ?
thank you

**Comment by chevroulet94** [comment]
Done ! Thanks in advance

**Comment by ylecollen** [comment]
@chevroulet94 
did you enable the markdown ? it does not seem being enabled.

**Comment by chevroulet94** [comment]
@ylecollen 
Yes Markdown is enabled (see below)
![dkkfqxbszgcjzajdsnfksskc](https://user-images.githubusercontent.com/35290947/34772940-2cbd1dfa-f60a-11e7-8e47-967f17c537b7.png)

**Comment by ylecollen** [comment]
ok, thank you
