### ISSUE TITLE
Tapping on Android Notifications for the Riot app does not take me directly to the relevant room.

### ISSUE THREAD

**Issue by BloodyIron** [vector-im/riot-android#1889]
When I get notifications for channel activity, and then I tap on the notification, it takes me to the channel select, not directly to the channel the notification is for.

This is really annoying, as I then get an extra notification (makes the noise twice), stating that the channel has stuff for me to read.

I would prefer it just took me directly to the relevant channel.

**Comment by ylecollen** [comment]
@BloodyIron 

It should go to the channel only if the notification could only one room events.

If you have (expanded notification)
XX unread messages in ...
YY unread messages in ... 

it only opens the rooms list

**Comment by BloodyIron** [comment]
Well, that's not the experience I've been having. Although I'm not sure if a recent update addressed this.

For the last while (bunch of weeks?), I've only had notifications for one channel. So this behaviour I'm describing is not when multiple channels have notifications for me at the same time.

**Comment by ylecollen** [comment]
" it takes me to the channel select, not directly to the channel the notification is for."

I assume i misundertood your expectation : the channel is opened to the latest message not to the notified message.

is it your expectation ?

**Comment by BloodyIron** [comment]
@ylecollen please re-read what I wrote and what you wrote.

1. It takes me to the CHANNEL SELECT, not the CHANNEL itself.
2. What I want it to do is take me directly to the CHANNEL.

This is in the scenario where only one channel has notifications for me.

As it behaves now, I tap on the notification, and I need to tap again on the channel (since I'm now in the view where I select which channel to go to). Instead I want it to just take me directly to the channel which the notification is for, NOT to the select channel part (which is what it is doing).

**Comment by ylecollen** [comment]
@BloodyIron 
sorry, but, i don't reproduce your issue.
 
 With your use case and when i tap on the notification, the notified room (what you call channel) is properly opened.

**Comment by BloodyIron** [comment]
This literally happened to me every single time today. Which is at least 15 times. So I really don't understand why it's not reproducible for you.

And yeah, I suppose I should have used slightly different language in the title, whoops!

**Comment by BloodyIron** [comment]
@ylecollen ummm, isn't that literally what I am doing right now? I suspect you mean you want me to do something more than this... so... what exactly would you like me to do differently from what this github issue is doing right now?

**Comment by ylecollen** [comment]
@BloodyIron 

In the application home sliding menu (when you tap on the hamburger icon ), there is an entry named "bug report".

This bug report will contain some logs which might help me to understand your issue.
The logs are posted on a private repo.

**Comment by BloodyIron** [comment]
@ylecollen I filed a shake report that I think should fit the parameters you seek. :) Not sure where shake reports go, I don't think I have access to them...

**Comment by ylecollen** [comment]
https://riot.im/bugreports/listing/2018-01-20/021134/logs-0001.log.gz

**Comment by ylecollen** [comment]
D/VectorRoomActivity: Displaying !SFCORkMnMNXhpoHJhF:matrix.org (i cannot have the room name).

It seems the application is opened with this room.
Did you send the bug after tapping on the notification ?

**Comment by BloodyIron** [comment]
I tapped the notification, went into the channel, back to channel selection, filed bug. I had thought it would give you enough info to trace that action, but I guess not?

When I get an alert next, and it takes me to room selection, I'll file another report then. Whoops!

**Comment by dephiros** [comment]
I am a recent user of Riot. Me and my family encounter this bug as well. Tapping on the notification always take me to the room list view not specific conversation

**Comment by splitowo** [comment]
The behavior seems to depend on the notification privacy setting. In my case, the notification opens the relevant room directly only when the privacy is set to "Normal".

@BloodyIron @dephiros 
If you could specify which setting you are using, this would help devs in fixing the issue. It is located at: Settings > Notifications > Notification privacy

**Comment by BloodyIron** [comment]
Notification privacy is set to "Normal".

**Comment by bmarty** [comment]
Fixed in Riot 0.8.26

**Comment by BloodyIron** [comment]
@bmarty woot! How soon before this hits Google Play? :D

**Comment by bmarty** [comment]
It's live!
