### ISSUE TITLE
Cannot anymore download images over federation

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1890]
reported by @rghvdberg:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/1857

"errcode":"M_NOT_FOUND","error":"Not found ['matrix.gosicks.com', 'DuUEoyQzNxDWHKblXNcFLyyQ']

**Comment by ylecollen** [comment]
Seems being a federation error.

**Comment by ylecollen** [comment]
01-13 12:12:45.113Z 1447 D/MXMediaDownloadWorkerTask: The download org.matrix.androidsdk.db.MXMediaDownloadWorkerTask@bb698a1 failed : mErrorAsJsonElement {"errcode":"M_NOT_FOUND","error":"Not found ['matrix.half-shot.uk', 'dhZjamerCYKQCSmqJwAsibDm']"}

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1867

**Comment by ylecollen** [comment]
https://riot.im/bugreports/listing/2018-01-14/104228/

**Comment by ylecollen** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/1870

**Comment by krombel** [comment]
Is that probably related to a bug in synapse develop?
I had that issue as well and it did not reappear after applying the patch which closed the issue.
For reference: matrix-org/synapse#2776

**Comment by ylecollen** [comment]
fixed by a server update
