### ISSUE TITLE
unexpected message indentation

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1898]
reported by @nathan:vanbeelen.org
Some messages do not display properly (see the indented message and also the message that has a name right above it instead of the usual avatar-name combination). 

https://github.com/matrix-org/riot-android-rageshakes/issues/1881

**Comment by ylecollen** [comment]
Expected behaviour : Coffee updated his displayname so the indentation makes sense.

**Comment by nathan** [comment]
@ylecollen Wrong @nathan, I think.
