### ISSUE TITLE
PTT button during call or jitsi conferencing

### ISSUE THREAD

**Issue by josephtocci** [vector-im/riot-android#1905]
During a call, it would be nice to be able to mute the microphone and hold down the headphone button to unmute the microphone until I let go. In this way I can be doing something with my hands and have my phone in my pocket and simple press the headphone button to talk on a conference call.

**Comment by BloodyIron** [comment]
VERY YES!

**Comment by ylecollen** [comment]
You can already mute/unmute the call with the dedicated button.
But, you're right the headset mute button is not managed.

**Comment by BloodyIron** [comment]
Why was this closed exactly? I would like to see this feature in riot-android...

**Comment by t3chguy** [comment]
@josephtocci what you described is actually impossible, whilst you have the headphone inline control button held the Mic line of the cable is pulled to GND, rendering it impossible for the microphone to function.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/35106794-15d041b8-fc67-11e7-8a6d-eaafdc36cb61.png)

**Comment by BloodyIron** [comment]
Well that's both tragic and informative! Yikes.

**Comment by josephtocci** [comment]
Hmm, looking at the apps that I'm aware have this feature they do it a few different ways:

Option 1: With headphones, pressing the button toggles the microphone mute. I prefer open source stuff and no-one I know is on Mumble so I didn't know about this, my apologies. This is what Zello does with headphones.
Option 2: Zello also has some wireless hardware buttons.
Option 3: And the way Voxer does it is it overrides the volume buttons for PTT. Some walkie-talkies and ham radios will have to PTT buttons, a low power one and a full power one. For an app I could see this as listening to two different channels and being able to talk to one or the other. But I don't think that would work for Riot.

My recommendation is option 1, it's the least work and people who use PTT apps moving to Riot would be at home already. It wouldn't be a hold down PTT like everyone likes but it would actually be more helpful in situations where you are doing something with your hands. Your hands would be free the entire time you are talking you just would need to switch it on/off for a second at the begining and end. It's a far better option for hand's free operation.
