### ISSUE TITLE
sending message via enter key: hardware keyboard not detected

### ISSUE THREAD

**Issue by Flexmaen** [vector-im/riot-android#1914]
I'm using a Blackberry Keyone and it seems that sending messages via enter key is not possible, although it was added to earlier versions of Riot.

Used version: 0.7.09 G-#117

**Comment by d1d4c** [comment]
Can you link that commit?

**Comment by Flexmaen** [comment]
After a discussion in the Matrix channel I think:
- That commit I was referring to seems to detect external keyboards, and accept the enter key for sending messages
- But the Keyone is using its keyboard as replacement for the onscreen touch keyboard.

As far as I understand this means, that Riot will need an option for sending messages with using the "normal" onscreen enter key. Do you think I'm right here?

BTW, if you add this, it might be also useful to have a choice between "normal enter" or "shift + enter".

**Comment by bmarty** [comment]
Should be fixed by #3019 (Riot 0.8.24)
