### ISSUE TITLE
Embedded images must be restricted to mxc: URIs

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#1921]
Right now img tags are allowed arbitrary linking, which is a security issue!

**Comment by ylecollen** [comment]
https://github.com/vector-im/riot-meta/issues/133

**Comment by ara4n** [comment]
yes, this is a security issue - and has been mistriaged. @giomfo presumably this is a trivial fix?

**Comment by manuroe** [comment]
The security regression was added with https://github.com/vector-im/riot-android/pull/1900 where the `<img>` tag has been added without a check on its `src` attribute value.
