### ISSUE TITLE
There is absolutely no indication that I received a group/community invite

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#1923]
Only when I open the communities screen do I see that I've been invited to a new community.

**Comment by ylecollen** [comment]
@Matrixcoffee 
It is a server design issue : 
1- the group events are not synced
2- the clients must trigger 

--- a request to retrieve the joined groups list
--- a request to retrieve the invited groups list
---- requests for each group to have the description.

So, if i set a timer to refresh them once per minute (for example), you will complain that the app uses too much data.

**Comment by Matrixcoffee** [comment]
@ylecollen: I asked about this in [#matrix-dev](https://matrix.to/#/#matrix-dev:matrix.org) and according to @dbkr the group invites should come down the sync.

Looking at https://github.com/matrix-org/matrix-js-sdk/blob/master/src/sync.js#L743 should be helpful.

**Comment by Matrixcoffee** [comment]
I can confirm that this information definitely appears in the sync stream unprompted. This is what it looks like:

```
{
        "groups": {
                "join": {
                        "+fdroid:matrix.org": {},
                        "+polynomial-supporters:matrix.org": {} },
                "leave": {},
                "invite": {
                        "+silly.bot.committee:t2bot.io": {
                                "profile": {
                                        "name": "Silly Bot Committee",
                                        "avatar_url": "mxc://t2bot.io/VsAdTQMSZxnVjXIREXWfCQjv" },
                                "inviter": "@travis:t2bot.io" },
                        "+serious.bot.committee:t2bot.io": {
                                "profile": {
                                        "name": "Serious Bot Committee",
                                        "avatar_url": "mxc://t2bot.io/4acfa78c31c60b21d8bfaed7f7789629" },
                                "inviter": "@travis:t2bot.io" } } }
}
```
