### ISSUE TITLE
Can not preview and join an empty room by clicking on a room pill of a room I am currently not part of.  The badge I see is: It is currently not possible to rejoin an empty room.

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1938]
reported by @krombel:msgs.tk
https://github.com/matrix-org/riot-android-rageshakes/issues/1914

**Comment by ylecollen** [comment]
it's known issue : the inviter dismissed the invitation.
the left room is not synced

**Comment by krombel** [comment]
I was never invited to that room (AFAIK)
I tried to open a room where was never in or I have left some time ago.
It would be bad when I cannot have a look at rooms I have been a member of in the past...

**Comment by ylecollen** [comment]
it seems being a server side issue.
The android client cannot retrieve such room.
