### ISSUE TITLE
Riot is still using the accelerometer at nearly 100%

### ISSUE THREAD

**Issue by angrierhorse** [vector-im/riot-android#1964]
Previously I reported that riot was polling the accelerometer 100% of the time.  This was addressed on a previous build with a race condition being identified.  This has still not fixed the issue.  I am running the latest riot (google play version) on android 4.4.  Better battery stats reports my processor never goes to sleep and is awake 100% of the time.  Under the sensors tab of better battery stats I can see that riot is accessing the accelerometer 100% of the time.  I know this is not a false positive as when I disable riot the processor is able to go to sleep.  I have already chosen the disable shake to submit bug "feature".

Please.  I'm begging you.  Just remove the shake to submit bug code.  Riot does not need to even know about the device accelerometer, screen rotation is dealt with by the OS.

**Comment by ylecollen** [comment]
@angrierhorse 
Which version are you using ?
The accelerometer issue has been fixed on the develop code

https://github.com/vector-im/riot-android/blob/develop/vector/src/main/java/im/vector/util/RageShake.java#L122
