### ISSUE TITLE
Suppress Riot-Android device notifications if detected activity in other device

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-android#1968]
At now Riot-Android play sound notifications always on new messages, so if I actively use desktop Matrix client - my device rings very often, so I must turn notifications off, and give back to on when I go away from desktop computer.

For solve this problem - will be good to have mode in Riot-Android to detect user activity on other linked device in account, and temporary auto suppress notifications on this device if activity on other device is detected some time ago.

**Comment by MurzNN** [comment]
Seems this must be done also in Matrix server API, so I created issue https://github.com/matrix-org/matrix-doc/issues/1119

**Comment by richvdh** [comment]
https://github.com/vector-im/riot-android/issues/1283 / https://github.com/vector-im/riot-web/issues/469

**Comment by richvdh** [comment]
btw: 

~at now~ currently
~Riot-Android play sound notifications~ Riot-Android play**s** sound notifications
~for solve~ to solve
~will be good to~ it would be good to
~temporary auto suppress notifications~ temporar**ily** auto suppress notifications

Hth :)

**Comment by MurzNN** [comment]
Sorry for my English :(
