### ISSUE TITLE
Re-enable rageshake?

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-android#1971]
So I disabled the rageshake reporter a while ago and now want to enable it back to report the bug with a screenshot. I suppose if I use the "Bug Report" from the side menu it doesn't take a screenshot of the room I'm currently in because I have to move out of it to reach the menu. How do I re-enable shake detection? Couldn't find it in the options and don't want to reinstall the app just because of that.

**Comment by manuroe** [comment]
FTR, there is a "Rage shake to report bug" button on riot-ios. We could have it on riot-android too.
