### ISSUE TITLE
f-droid: the "start at boot" option is not supported on some devices

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#1978]
The "start at boot" option added in https://github.com/vector-im/riot-android/issues/412 seems ignored on some devices

see: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$151792196912TpHjZ:vnti.de

**Comment by lugino-emeritus** [comment]
Thx for writing this issue (I'm Blue Ghost), but after a bit more testing and having a look into the logs of riot, it not seems to be a "start at boot" problem: Riot is shown in the notification area and the new message is shown in the logfile of riot. But I miss the notification sometimes.

It seems to be a crazy problem on my phone 🤔. E.g. when the phone is plugged in everything works fine. So from my side you could close this bug.

**Comment by giomfo** [comment]
Thx @lugino-emeritus for the feedback
