### ISSUE TITLE
F-Droid version is still on 0.7.03

### ISSUE THREAD

**Issue by Sorunome** [vector-im/riot-android#1979]
`Version 0.7.03 (70301) - Added on 2017-10-20 `
That is more than three months old and the latest version on the play store is 0.7.09

**Comment by ArchangeGabriel** [comment]
https://gitlab.com/fdroid/fdroiddata/issues/1058

**Comment by shiftee** [comment]
Just got 0.7.09 via F-Droid so this can probably be closed

**Comment by Sorunome** [comment]
Yes, can confirm, so i'll close this now
