### ISSUE TITLE
Registration with phone number failed for Nigerian phone

### ISSUE THREAD

**Issue by gutzygwin** [vector-im/riot-android#1983]
#### Expected behavior
Upon log in on the Riot chat app, it's expected to run a sequence of registering procedure which the log in app and thereafter make use of the app

#### Actual behavior
Currently, the Riot app register button has been malfunctioning of late.  While registering, after including your username and desired password as shown on the image below.
![Screenshot_20180204-233053.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517785825/dkvv17yq70sjwgza8fmg.png)
The error occurs after the inclusion of the email address or phone number is inserted. The images below displays the error occured while logging in using both the email address and using mobile number. 

![Screenshot_20180204-233235.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517786428/rsvhaoffvkupswahaknx.png)
Using the email address 

![Screenshot_20180204-233118.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1517786462/aoeg7sqbmv6wlnbdq0iv.png)
Using mobile number. 
After displaying this, the app doesn't log in and stays like this for as long as it can take. 

#### How to reproduce
• Download the riot.im chat app from playstore
• Register on the app as a new user
• Include your username and desired password 
• Input mobile number into required space and click register just as the images above. 
• Bug found. (you can also alternate and use the email address for tests) 

* Browser: Google Chrome and Riot.im app
* Operating system: andriod 7.0

Infinix note 4

#### Recording Of The Bug
https://youtu.be/nlqMd3GCscM
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gutzygwin/bug-on-riot-chat-app-log-in-sequence-not-working">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by giomfo** [comment]
@gutzygwin: registration with phone number is supposed to be supported for Nigeria.
It seems we've had unresolvable sketchy connectivity.

**Comment by bmarty** [comment]
Registration with phone number is now disabled on matrix.org
