### ISSUE TITLE
After enabling e2e, riot keeps crashing on startup

### ISSUE THREAD

**Issue by nagua** [vector-im/riot-android#1986]
Hello,

I installed Lineage OS 14.1 on a Samsung Galaxy S2 Mini yesterday including google apps. After installing Riot.im (and trying to recover with Titanium Backup) I noticed that E2E was turned off. So I enabled E2E and Riot crashed. Now whenever I try to open Riot.im it keeps crashing.

You can find device_info and logcat output here: https://gist.github.com/nagua/deef1f2733c6335715ed75345ced5a0e

The relevant crash info seems to be here:

```
02-10 00:42:40.684 E/OlmManager(17524): Exception loadLibrary() - Msg=dalvik.system.PathClassLoader[DexPathList[[zip file "/mnt/expand/45953ded-4516-464c-88ad-c1794a88988b/app/im.vector.alpha-1/base.apk"],nativeLibraryDirectories=[/mnt/expand/45953ded-4516-464c-88ad-c1794a88988b/app/im.vector.alpha-1/lib/arm, /mnt/expand/45953ded-4516-464c-88ad-c1794a88988b/app/im.vector.alpha-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libolm.so"
```

**Comment by hrj** [comment]
It's not finding the `olm` library which might be due to a bug with the install or recovery process. Perhaps you could try installing the app again, without using any backup tools.

(Disclaimer: I am not a riot-android developer)

**Comment by nagua** [comment]
It was not possible to install riot via backup. So I first installed from play store. After that I tried data recovery that worked a bit but also had the e2e enabling bug. So I deleted the app data and tried clean. The logs are from the clean install/login.

**Comment by Matrixcoffee** [comment]
What you did does not work, by design. The crypto is _specifically_ designed to resist this, so that even if an attacker manages to clone your device, they can't impersonate you or decrypt new messages.

**Comment by nagua** [comment]
But why doesn't it work after I deleted all appdata and then logged in normally?

**Comment by Matrixcoffee** [comment]
Good question. A clean install and login _should_ work. The logs suggest it can't find/load (some part of) the OLM library. Which is weird, because it's clearly working for others. I'm afraid you're on your own here :/

**Comment by nagua** [comment]
Somehow this was resolved with either updating or reinstalling the application. So I will close this now.
