### ISSUE TITLE
[feature request] Option to compress a media file when sharing it

### ISSUE THREAD

**Issue by hrj** [vector-im/riot-android#1988]
When attaching a media file (image especially) from within the app, a dialog from the app asks whether user wants to compress the file to a smaller size with lower quality.

However this dialog is not shown when sharing the file from an external context. (Gallery -> View image -> Share -> Riot app) and the file is uploaded with full resolution.

This behaviour consumes more bandwidth on the client side and increases the load on the home server.

**Comment by Matrixcoffee** [comment]
It doesn't? That's odd... Has always done that for me, for images of sufficient size.

**Comment by hrj** [comment]
Oh "images of sufficient size" was the key! I had probably tried a smaller image before. I tried it now with a large image + version 0.8.1 and the dialog does pop up.
