### ISSUE TITLE
Why using piwik ?

### ISSUE THREAD

**Issue by 2Belette** [vector-im/riot-android#1994]
Hi,

First of all many thanks for the App I really like it!
I am using the F-droid flavor, and wondering why do you use piwik and what type of statistics are you generating ?

Many thanks and long life to riot!

**Comment by 4nd3r** [comment]
dup #1798

**Comment by ara4n** [comment]
We're using piwik (now called matomo) to keep track of how many people are using the app, how often, and which screens they use. This is vital in terms of both justifying to folks funding Matrix that we actually have users on the network (and that the network is growing), and that their $ is worthwhile: and it's also vital to see which bits of the app are working and which aren't and where we should be investing time to make the app better (or less buggy).

#1798 has more details.
