### ISSUE TITLE
Persistant 'Synchronising' Notification since v0.8.1

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#2004]
We've been getting a persistent "Synchronizing" notification from Riot on Android 8.0.0 since Riot v0.8.1. This is on the Google Play version of Riot, with Google Play Services installed.

After closing Riot from the recent apps list, the notification will appear and be undismissable. This does not happen if the app isn't closed from the recent apps list.

If Riot is opened, it disappears and syncs instantly. Very annoying for people who keep their recent apps list clear.

Other cases of people having this issue:

**@fodder:matrix.org:**

> yes. The most I can do for your issue atm is add a "me too", albeit on Android 6, running over Tor, and with some Xposed modules restricting different types of access
mini Vector does the same thing. Now that I think of it, it WASN'T happening until a recent upgrade. Maybe try downgrading through F-droid or something and see if that changes anything?

**@hpmaennicke:matrix.org:**

> I have had the same on Android 7.0.
But after restart my mobilphone all is runnung well.
For testing I have two more instances on my phone. (I cloned the Android app)
...

![img_20180222_092501_241](https://user-images.githubusercontent.com/1342360/36527629-47544d4a-1767-11e8-9cb8-74b7fc38b8ad.jpg)

> Yes coming back

**@ajya:matrix.org:**

> Hey, just fyi, I have the same synchronizing notifications appearing. I think I got the update last night.

Discussion here: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$15192709409SHONK:amorgan.xyz

Edit: Riot deleted and redownloaded, with issue persisting.

**Comment by hrj** [comment]
Might be related:

Latest version: firebase-core:11.8.0
Version used in riot-android: firebase-core:11.6.2

**Comment by BloodyIron** [comment]
I too am getting the synchronizing notification that won't go away. Android 7.1, and got it from Google Play official source. It was not a thing with 0.7.9, and only started when I upgraded to 0.8.1.

**Comment by Tyuoli** [comment]
duplicated of https://github.com/vector-im/riot-android/issues/2012
