### ISSUE TITLE
Search for communites text is green; background is blue.

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-android#2010]
![image](https://user-images.githubusercontent.com/1922197/36542304-5d562f16-17d8-11e8-93ee-4a85ff502c42.png)

**Comment by lukebarnard1** [comment]
It's also wrong for favourites and people

**Comment by benmcnelly** [comment]
The green on purple ins't unreadable on he favorites section, but its not pretty to most, and its not good at all on the people and communities search tabs. 

I have changes the primary hint text color to a slightly off (muted) white, so it looks good over any of the tab backgrounds, as those are not impacted by the light/dark themes: but also has some contrast to the full white you get when actually entering text.

https://github.com/vector-im/riot-android/pull/2419

**Comment by bmarty** [comment]
Fixed by #2419
