### ISSUE TITLE
Complaints that the "Synchronizing" notification appears too often

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-android#2012]
A few people have complained since the `0.8.1 (G-#123)` release that they are seeing the "Synchronizing" notification very often. I've asked them to submit rage shakes.

I'm also seeing this quite often.

**Comment by Tyuoli** [comment]
reported by @BloodyIron:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2033

**Comment by Tyuoli** [comment]
Notice that the "Synchronising" makes sense when the application is automatically restarted (after being killed by the user or the system).

 But, it should disappear after few seconds.

 The auto restart is required to manage the incoming calls asap.

**Comment by Tyuoli** [comment]
reported by @ithildim:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2032

**Comment by Tyuoli** [comment]
reported by @so_:tang.ents.ca
https://github.com/matrix-org/riot-android-rageshakes/issues/2030

**Comment by Tyuoli** [comment]
reported by AustenG:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2028

**Comment by Tyuoli** [comment]
reported by @jlath:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2021

**Comment by lalomartins** [comment]
It doesn't disappear at all for me, and can't be dismissed. It only goes away when I open the client.

**Comment by BloodyIron** [comment]
Same!

**Comment by Flexmaen** [comment]
The problem is that this sync-message seems to cause that my notification LED flashes on my phone, although no one messaged me. This LED only goes off after I open the Riot app.

**Comment by BloodyIron** [comment]
Yeah we really need an update released to fix this! The notification mechanism is broken for me. I don't even get notified now when I should, the old notifications get in the way! :/

**Comment by MuntlagarDracha** [comment]
I have the same problem. It is truly annoying and the real notifications only come randomly through. On more than one occasion i missed an important messages because of those notifications.

**Comment by BloodyIron** [comment]
So when are we going to get a release for this bug? This is seriously turning a lot of people off of riot. This is not a small deal here.

**Comment by ylecollen** [comment]
A release should be pushed at the end of next week

**Comment by anderspitman** [comment]
Thanks for working on fixing this. I have several friends who I convinced to use Riot over Discord and this has really been annoying them.

**Comment by BloodyIron** [comment]
So, any word on a release? Any chance we could see milestones for things like this? As an outsider it's hard to tell how the release cycle works around here.

**Comment by manuroe** [comment]
Our sprint ended last week as Yannick said above. We are doing some polishing to make the release.
We should be able to make a beta tomorrow and a play store release by the end of the week if things go right.

**Comment by Flexmaen** [comment]
This still seems to exist in the new release...

**Comment by BloodyIron** [comment]
I still see it, but it goes away after a few seconds. When I commented on this earlier, it wasn't going away at all. @Flexmaen is it going away for you at all?

**Comment by mehturt** [comment]
I agree with @BloodyIron it works fine now, the "Synchronizing" notification appears for me only when I don't have internet connectivity (e.g. I turn off mobile data and wifi), when all is connected I rarely see the notification.

**Comment by turt2live** [comment]
If you're still having issues with the notification, please open a new issue instead of re-using this one.
