### ISSUE TITLE
Matrix Apps: Enable them by default

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2022]
~~and remove the setting from Settings > LABS~~ <- no more required because of this [comment](https://github.com/vector-im/riot-android/issues/2022#issuecomment-371811467).

**Comment by Matrixcoffee** [comment]
I hope you meant: **move** the setting out of LABS. I would be very sad if it became impossible to disable Matrix Apps.

**Comment by manuroe** [comment]
The initial plan was to remove them to be aligned with riot-web and riot-ios.
But we may be able to find a place for this setting elsewhere.

**Comment by manuroe** [comment]
Currently, there is no good section in settings to host this setting, so it will stay in LABS until we reorganise this long settings page.
So, the only required change is to enable them by default so that people will be no more surprised to not find their widgets.
