### ISSUE TITLE
Active area for the send button is too big.

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#2041]
Perceived touch area:
![Image of perceived touch area](https://matrix.org/_matrix/media/v1/download/matrix.org/MrSwMpZvlrpzKcmgcSDcOVRe)

Expected touch area:
![Image of expected touch area](https://matrix.org/_matrix/media/v1/download/matrix.org/bZhCnXVxtsLPIMFHjwNUZCML)

Related issue: #1387

**Comment by ylecollen** [comment]
When it was limited to the send icon size, many users yelled.
When it has the same height than the text edit, people yells.....

**Comment by bmarty** [comment]
Send button is now anchored to the bottom and with clickable area around the button (since 0.8.9)
