### ISSUE TITLE
Black borders on 18:9 phone since 0.8.1

### ISSUE THREAD

**Issue by bovine3dom** [vector-im/riot-android#2063]
Relatively recently, black borders have appeared around the top and bottom of Riot on my 18:9 phone. I believe this was introduced in 0.8.1; before that, the application worked as expected, using all of the screen.

![screenshot_20180310-114155](https://user-images.githubusercontent.com/6505246/37241873-2f65a654-2458-11e8-86bd-d10080ae6656.png)

Interestingly, the screenshots I take of Riot are squashed vertically, which could be related to the issue. No other application produces squashed screenshots in this manner.

Thanks!

**Comment by BloodyIron** [comment]
Would probably be a good idea to post the resolution of your screen on here.

**Comment by bovine3dom** [comment]
@BloodyIron it's 1080x2160.

**Comment by bovine3dom** [comment]
I'm still seeing this in 0.8.15 - how can I help debug?

**Comment by BloodyIron** [comment]
Quite the curious scaling issue. I thought it was reactive/responsive scaling in the app? Hmmm.

**Comment by bovine3dom** [comment]
In case I wasn't clear earlier: "squashing" only happens in screenshots; it is not squashed outside of them. I still get the black bars.

**Comment by bovine3dom** [comment]
This might have been PEBKAC. I found an area in my phone's settings called "Full screen mode" where there was a list of all the applications on my phone. Almost all applications had it enabled, but Riot mysteriously did not.

I flipped the switch and Riot seems to be working in full screen without any issues.

So I guess the question is - did I accidentally flip the switch (I really don't think I did), and if I didn't, how do you tell my phone that "Full screen mode" works fine?

Generally, the applications that seem to have it disabled are banking applications such as Yolt, Nationwide and share.com.

My phone is a DOOGEE Mix 2.

**Comment by bmarty** [comment]
Maybe application which has been installed without the full screen support stay in disabled mode when they are upgraded with FS support.
Let's close the issue for now.

**Comment by bovine3dom** [comment]
The setting resets to 16:9 with borders every time Riot is updated, so I think something is still broken somewhere.
