### ISSUE TITLE
Invite an user by email displays with unread marker when the user joins the room

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#207]
Steps to reproduce
1- invite an user by email (the email is not linked to a matrix account)
2- the invitee creates an account and joins the room
3- the inviter recents displays the room with a stuck unread marker (left view)
even if the room is opened / closed.

I suspect there is an event which is not acknowledged. (room visibility one?)

**Comment by sabrinaj** [comment]
Not reproduced.
