### ISSUE TITLE
Settings: background sync setting stays disabled

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2075]
if you disabled the background sync.

Reported at https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$15210192563891182JfTqC:matrix.org.

The reason was found by @hrj in https://github.com/vector-im/riot-android/issues/2044#issuecomment-373009853.

**Comment by impala2** [comment]
This is happening to me on F-droid riot. Started after most recent update (0.8.5 to 0.8.7). The rage shake option has no effect.

**Comment by impala2** [comment]
Nevermind, this is better described in #2196
