### ISSUE TITLE
Remove the puzzle strings

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#2085]
Reported by @SafaAlfulaij https://github.com/vector-im/riot-android/pull/1934#issuecomment-373441599

**Comment by SafaAlfulaij** [comment]
Too many!

https://github.com/vector-im/riot-android/blob/bfe8b9ca6178a87d5d9686716b71917930a3d470/vector/src/main/java/im/vector/util/VectorUtils.java#L955

Btw, in that comment some are also plural.

**Comment by SafaAlfulaij** [comment]
String directory_search_room to be deleted (not used anymore)
