### ISSUE TITLE
MalformedJsonException on image reception

### ISSUE THREAD

**Issue by inducer** [vector-im/riot-android#2093]
When I receive an image from my home server (on synapse 0.26, I run my own), I often (but not always) get a blank entry, and after a while a toast with the following error message pops up:

![screenshot_riot im_20180318-102812](https://user-images.githubusercontent.com/352067/37568887-473f1844-2aa9-11e8-9434-292ec93430b2.png)

Other clients (Riot web, Riot iOS) seem to have no issue.

I'm on Riot 0.8.1 from FDroid, using LineageOS 15.1. As far as I recall, the issue started appearing after the upgrade to 0.8.1.

**Comment by thomas-profitt** [comment]
I've had the same issue. It happened a day or two ago. I'm also using Riot 0.8.1 from F-Droid, and haven't seen a similar problem with the same images on Riot Web, but I'm on LineageOS 14.1.

**Comment by ara4n** [comment]
interesting. one thing that could cause this is a server issue that was fixed in 0.26.1 - so please upgrade to that if you are on 0.26.0.  otherwise, please can you send a bug report (aka rageshake) from the app so we can see precisely which request is failing?

**Comment by inducer** [comment]
Going to 0.26.1 seems to have resolved this. I'll close this for now. Thanks for the speedy response!

**Comment by Matrixcoffee** [comment]
Weird that going to 0.26.1 fixed it. I have my account on matrix.org, and I cannot load images in rooms anymore. I see the same JSON error, including the line 1 column 9 path $ bit.

**Comment by inducer** [comment]
Actually: agreed. This recurred today. I'll try to remember to "rage-shake".

**Comment by manuroe** [comment]
@inducer, what is your device android version?

**Comment by manuroe** [comment]
matrix.org was moved to a new server few days ago with a default TLS config accepting only TLS1.2, which does not work (yet) on old devices (https://github.com/vector-im/riot-android/issues/2017).

Server has been updated to support TLSv1.0 and images can be loaded now (https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$1521625111192817MRYpS:matrix.org) but there is still this JSON error toast.

**Comment by manuroe** [comment]
https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$1521628996238305BaVxu:matrix.org indicates there is no more JSON error.

**Comment by inducer** [comment]
My device is on Android 8.1 via LineageOS 15.1. For that reason, I doubt that the issue has anything to do with old TLS libraries.

I just submitted a "rageshake" referencing this issue number. And i can confirm that the problem is definitely not gone with synapse 0.26.1.

**Comment by inducer** [comment]
I'm observing that (even) on rooms on my homeserver that are unfederated (i.e. have only local users), images are taking a very long time to load, even on riot-web.
