### ISSUE TITLE
 Wrong translation into Polish : report an error

### ISSUE THREAD

**Issue by Tyuoli** [vector-im/riot-android#2094]
Błędne tłumaczenie : zglosoić błąd

![screenshot](https://user-images.githubusercontent.com/36439413/37586225-fb7730be-2b5b-11e8-8789-20ae6e40ff69.png)

**Comment by manuroe** [comment]
SOS sent at https://matrix.to/#/!OYyXUbcTKVsDBUniNn:matrix.eclabs.de/$15214533011810170bkpcB:matrix.org.

**Comment by bldrzzy** [comment]
Assuming the context is send_bug_report_alert_message, I've already fixed it.

**Comment by manuroe** [comment]
Thanks @bldrzzy!
