### ISSUE TITLE
 Add the "ok" option on the pop-up that opens via the floating action button

### ISSUE THREAD

**Issue by Tyuoli** [vector-im/riot-android#2096]
![fab_popup](https://user-images.githubusercontent.com/36439413/37588852-ca9f87e0-2b63-11e8-9131-5c7c7919e446.png)

**Comment by ArmenApresyan8** [comment]
What about just having these 3 options without "OK" and "Cancel" buttons, and without radio buttons, so the user just has to click the one that he likes?

**Comment by ArmenApresyan8** [comment]
Alternatively, we can have a floating action menu with our three options.
![floating-action-menu-material-design1](https://user-images.githubusercontent.com/18738136/37589834-c833533a-2b7f-11e8-92ce-f6ec466bf3b5.jpg)

**Comment by ylecollen** [comment]
funny : there was one : i've got some users which complained about this 'ok' button

**Comment by neverfox** [comment]
Agreed. This violates what I consider basic UX/UI principles, as radio buttons are for setting an option not triggering an action (i.e. they shouldn't be attached to a clickable item). I definitely endorse the idea of the floating action menu as the best alternative, in keeping with Material Design. Barring that, just drop the radio buttons, which should imply more strongly that a touch/click is expected.

**Comment by bmarty** [comment]
Done in #2335 and #2404
