### ISSUE TITLE
Notification dot reversed

### ISSUE THREAD

**Issue by natrius** [vector-im/riot-android#2104]
**Cellphone:** 
OnePlus A3003 (=Oneplus 3)

**Android:** 
8.1.0

**System:** 
LineageOS 15.1-20180319-NIGHTLY-oneplus3

**Riot-Android:** 
0.8.3 (F-ddcba936)

**Problem:** 
The notification bubble (badge?) is reversed. So when there is a bubble, there is no new message. If the bubble disappeares, there are new messages.

**Expectation:**
New messages = bubble there.
No new messages = no bubble.

If further information is needed, just ask :)

**Comment by natrius** [comment]
Updated today to 0.8.13 (F-04edbf9c) and its still reversed.

**Comment by bmarty** [comment]
Hi @natrius ,

Thanks for update. Could you add a screenshot with the issue please?

Thanks

**Comment by natrius** [comment]
I try not to salty or something, but you want a Riot-Icon with a bubble on top right (the same that is there for signal, silence, conversations and whatever other messenger-app is out there? Even Firefox has this bubble) and one without?
If yes - okay, will deliver gladly :)

**Comment by natrius** [comment]
Actually, i'm wrong, sorry. The bubble is all the time there.  2 Screens, one with unread messages, second one all messages read. 
![1](https://user-images.githubusercontent.com/7243447/44033179-ddc55420-9f09-11e8-8c75-51ee0a151751.png)
![2](https://user-images.githubusercontent.com/7243447/44033180-dddfa564-9f09-11e8-804e-4be773375bd7.png)

**Comment by bmarty** [comment]
Not sure this dot comes from the application itself...

**Comment by bmarty** [comment]
Maybe #2534 will help fixing this issue...

**Comment by natrius** [comment]
Of course not from the application itself, the badge is a "new" Android thing beginning with 8 as far as i know. 
https://developer.android.com/guide/topics/ui/notifiers/notifications see "App icon badge". For more informations https://developer.android.com/training/notify-user/badges 

As i have no clue about programming at all, i hope what i searched is usefull.

**Comment by bmarty** [comment]
Android 8 badges are not implemented in Riot, i.e. not any API from https://developer.android.com/training/notify-user/badges are used. So I think the system itself decide to display the badge, maybe if an upgrade of the application is available in the store or for any other unknown reason

**Comment by natrius** [comment]
But its strange, its just happening with Riot. Every other Messenger App i know displays it correctly or not at all. At least disable it and everything is fine :)

**Comment by bmarty** [comment]
What do you want me to disable?

**Comment by natrius** [comment]
Uhm... The badge? As its obviously somehow present in the f-droid version. https://developer.android.com/training/notify-user/badges#disable
I don't know whats happening or why it seems that nobody else does have it. 

Btw. since the last update its persistent. Does not matter if there is a new message or not, its all the time there. 
I will try it today with another cellphone with the google-version and ask someone else about the f-droid version.

**Comment by bmarty** [comment]
Ok, I will do that
