### ISSUE TITLE
'Join as voice or video' does not have a clickable text when translated e.g. to german

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#2112]
In german only 'video' is clickable. You can see an example in this screenshot: ![](https://matrix.org/_matrix/media/v1/thumbnail/msg-net.de/qWfjOmeKZlZCtWModPGXPQJm?width=800&height=600)
It seems to work correctly in the other languages I checked btw (not all)

It is not clear [on weblate](https://translate.riot.im/translate/riot-android/riot-android/de/?checksum=bb919d4706a91c74) how that string should be translated to show the expected behaviour

**Comment by manuroe** [comment]
The code looks for the 2 next strings in weblate (`ongoing_conference_call_voice` and `ongoing_conference_call_video`) in this string to add links to it.

`ongoing_conference_call_voice` value should be `Sprach` or `Sprach-Chat` instead of `Sprache` currently.

**Comment by bmarty** [comment]
Fixed by #3031
