### ISSUE TITLE
Upgraded to Riot.im Play Store version to 0.8.4, gcm not active?

### ISSUE THREAD

**Issue by gradinaruvasile** [vector-im/riot-android#2123]
I upgraded Riot.im to 0.8.4 from Play Store and gcm doesnt seem to work anymore, it falls back to the polling mechanism (just like  the FDroid version). Version reported in client is 0.8.4 (F-#129).
There were 2 other things that happened - there was a pop up on Play Store asking for Instant apps opt in (forced) when i wanted to update it. 
I also upgraded my synapse server to 0.27.2.
Is this change intentional?

This happened on 2 phones, different models.

**Comment by gradinaruvasile** [comment]
I assume that is 0.8.5
Yes that works fine.

BTW the GCM-less version works surprisingly well if i set timeout to 3s and sync time to 30s. Got me thinking...

**Comment by Midek** [comment]
>GCM-less version works surprisingly well
except it drains batery like crazy, at least on my phone
