### ISSUE TITLE
Change icon to remove a widget and improve alert when removing a widget

### ISSUE THREAD

**Issue by sim6** [vector-im/riot-android#2129]
Please, could you improve the alert when you click the red cross on widget banner, saying that this widget is removing for everybody?

Moreover, I think the cross should be changed by a trash icon.

These changes were done in web version.

Thanks!

**Comment by bmarty** [comment]
Done

**Comment by sim6** [comment]
Thanks, but I cannot see it in Versió 0.8.21 (F-610fc121d).

**Comment by bmarty** [comment]
It will be visible in 0.8.22. Please be patient :)

**Comment by sim6** [comment]
OK, thanks again :)
