### ISSUE TITLE
Share issues.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-android#2140]
There are multiple share bugs.  #1990  #1748  #815  #451. Some or all may be dups.

Only track's title (without url) is shared from soundcloud to riot. The workaround is to share to clipboard and then insert it into riot. It doesn't depend on markdown setting. The full buffer from soundcloud is:
```
Listen to Skeewiff Ft Bam (Jungle Brothers) - Somebody's Watching Me ***FREEDL*** by Skeewiff #np on #SoundCloud
https://soundcloud.com/skeewiff/skeewiff-ft-bam-somebodys-watchin-me
```

**Comment by jcgruenhage** [comment]
I've had people tell me that this same issue also happens with Pinterest, only the title but not the URL is shared.

**Comment by erdnaxeli** [comment]
My idea is that riot cuts the text after the first "\n".

**Comment by 14mRh4X0r** [comment]
My guess is that the Intent has both a title/description and a message/content, and that Riot shares the former instead of the latter.

**Comment by 14mRh4X0r** [comment]
Confirmed my guess by sharing a message with my email app and by inspecting it with an intent debugger. What Riot shares is the subject instead of the text, because of matrix-org/matrix-android-sdk#284.

**Comment by bmarty** [comment]
Fixed thanks to https://github.com/matrix-org/matrix-android-sdk/pull/285
