### ISSUE TITLE
[Security] Escape nicknames starting with a forward slash `/` in mentions

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#2146]
So you can't be tricked into sending malicious commands. Related: #658 for making it possible to escape the slash in the first place.

**Comment by ara4n** [comment]
@bmarty i think this issue has slipped through the cracks - it should be a trivial fix; can you have control please? :)

**Comment by bmarty** [comment]
Ok, fixed in Riot 0.8.15
