### ISSUE TITLE
Save your license, guys. Maybe it's not issue, sorry =)

### ISSUE THREAD

**Issue by vishnyakov-aleks** [vector-im/riot-android#2157]
Recently, the news slipped that the company "Crimea technology" launched its own (according to their statements) messenger. Project: https://im.krtech.ru their android app for the basis project source code riot-android. The developers expect from users feedback and comments at im@krtech.ru.

**Comment by manuroe** [comment]
Thanks for the info. 
We just hope that the server is open for federation in order to increase the matrix ecosystem.
