### ISSUE TITLE
logo for Riot

### ISSUE THREAD

**Issue by damahboy** [vector-im/riot-android#2162]
hii .. my graphic designer ,, my name is damahsyari, i intend to ask permission to give you a new logo for RIOt

**Comment by manuroe** [comment]
Hi @damahboy,

Design is a sensitive thing. You can post your logo ideas here or at [#designUX:matrix.org](https://riot.im/app/#/room/#designUX:matrix.org). We will see how we can integrate it.

Also, keep in mind we have 3 Riot apps (android, ios and web).
