### ISSUE TITLE
GIFs don't play

### ISSUE THREAD

**Issue by zzottel** [vector-im/riot-android#2168]
On my wife's and my borther-in-law's phone, GIFs won't animate even when tapped. My wife has a Samsung Galaxy S5 mini, my brother-in-law a Samsung Galaxy S7 (Android 7.0).

Another GIF sent earlier this week played on my wife's phone. A new one from today didn't. Since then, the earlier GIF doesn't play anymore, too.

Deleting media cache lead to the device displaying only a black screen when I tapped on the GIF in the chat stream. Deleting cache afterwards made it display the full screen GIF again, but still without animation.

It seems to work without problems (yet) on my BQ Aquaris X5 plus and on my mother's Samsung Galaxy J5.

**Comment by einhander** [comment]
Same on xiaomi redmi note 3 mtk with Android 5, gifs are not playing. Google play version of riot im.
On htc one with Android 4.1 gifs plays ok.

**Comment by lsowen** [comment]
I am also having problems with GIF display (nexus 6p, Android 8.1.0, f-droid version).  The weird thing is that GIFs used to play, up until a couple of weeks ago or so.

**Comment by o0laxkilla0o** [comment]
I would agree with these statements i host a riot server for about 40 people and i have gotten several reports of gifs not working in rooms. People that haven't updated their riot android apps are still able to play the gifs people on V 0.7.07 (G-#112) can play but others on V 0.8.7 (G-#133) have issues
