### ISSUE TITLE
Oreo icon shape

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-android#2169]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by dkanada** [comment]
@bmarty would you accept a pull request to add this?

**Comment by c-e-p-x-u-o** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

looks like now it's p1 blocker bug

**Comment by bmarty** [comment]
Riot already targets API 26

**Comment by c-e-p-x-u-o** [comment]
OK (:

**Comment by bmarty** [comment]
Hello @dkanada, are you still motivated to work on this one? Else we will do it internally, please let me know :)

**Comment by dkanada** [comment]
I don't think I'll be working on this one, thanks for asking though :)
