### ISSUE TITLE
Piwik connections on opt-out until restart

### ISSUE THREAD

**Issue by licaon-kter** [vector-im/riot-android#2172]
No matter if you [ask the user for analytics approval](https://github.com/vector-im/riot-android/issues/1798) or if it's [opted out by default in F-Droid](https://github.com/vector-im/riot-android/pull/2100)... could you make the app **stop** trying to connect to `piwik.riot.im` **if** the user toggles opt-out to ON in Settings?

Thanks

Riot.im 0.8.5 F-Droid

**Comment by Matrixcoffee** [comment]
Fixed in #2176

**Comment by Bubu** [comment]
This is about a different issue tough, right?

**Comment by Matrixcoffee** [comment]
Uh, right. I think I need more coffee...

**Comment by Bubu** [comment]
Looking at the code there shouldn't be any connections when the preference is set to disabled. @licaon-kter where did you see this connection still happening?

**Comment by licaon-kter** [comment]
NetGuard

![pic](https://image.ibb.co/envgoc/Image824722464395134392.jpg)

**Comment by Matrixcoffee** [comment]
Did you confirm the setting is actually correct?

**Comment by bmarty** [comment]
PR #2100 was bugged and as been rejected, replaced with #2176 
I've check in the code and no piwik web request should be done if opt-out is on
#2176 has been merged in the new version 0.8.7 (not yet published), please retry on this new version
Benoît

**Comment by licaon-kter** [comment]
Ok I've figured it out.

The setting does not get applied right away, the user believes that toggling the switch does it (and let's be honest, I started the app to use it not turn it on and off at random), BUT the app needs to be EXITed first and then it stops connecting.

Either [modify the text](https://github.com/vector-im/riot-android/blob/develop/vector/src/main/res/values/strings.xml#L613) to say `Riot collects anonymous analytics to allow us to improve the application. (Restart needed)` or force a restart on toggle.

**Comment by zoff99** [comment]
opt-out itself is not privacy friendly. it should be opt-in in the first place

**Comment by licaon-kter** [comment]
@zoff99 use F-Droid, problem solved

**Comment by Bubu** [comment]
Pretty sure this can be closed now with the gdpr stuff present?
