### ISSUE TITLE
Remove the permanent Android Notification that says [ listen for events ]

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [vector-im/riot-android#2195]
Hey everyone, I am new here and just installed riot on android.. is there a way the notification that says [ listen for events ] could be removed. I have checked the settings but couldn't find an option to toggle that.

**Comment by Matrixcoffee** [comment]
You can install the Google Play flavour.

F-Droid rightfully does not allow inclusion of GCM libraries due to licensing. Therefore Riot has to poll in the background. In order to not get murdered by Android OS while in the background, it needs to post this permanent notification.

**Comment by LakshyAAAgrawal** [comment]
Ok got it.. can this info be included in the f droid version of the app, most preferably on the first startup, something like, "Riot will continue to display a sticky notification. Alternatively, you could install the Google play version." Or in the app description in both the app store.

**Comment by Matrixcoffee** [comment]
@LakshyAAAgrawal: You could edit https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.vector.alpha.txt and create a MR in GitLab to update the F-Droid description.
