### ISSUE TITLE
service crash and not receive messages

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-android#2225]
Riot 0.8.7
Android 6.0

Steps to reproduce:

1. Switch on "Airplane mode" before night on device1.
2. Send message to device1 from other account, on other device2.
3. Sleep 6-7 hours.
4. Switch off "Airplane mode" at morning on device1.
5. Wait messages on device1 from device2... No messages.
6. See list of running services - it is no riot there. (riot crash at night).
7. Send message to device1 from other account, on other device2 (again).
8. All messages from deivece2 showing at  device1 - service riot started (by google push serivce?).

Also 7 step may be simply start riot by hand. All messages showing after that.

This bug reproduce allways (at night). But it is not reproduce, if I switch on "Airplane mode" to 1-10 minutes - at this case all work properly and service riot not crash.

All this steps I testing with "switched off energy economy for riot" in android settings.

**Comment by progserega** [comment]
Sorry - this is no bug: my phone rebooted every morning (by task) - and it is clear all events.
All events was showing before reboot.

**Comment by progserega** [comment]
bug may be close

**Comment by giomfo** [comment]
thx @progserega for the feedback
