### ISSUE TITLE
URL previews are broken in the latest dev build

### ISSUE THREAD

**Issue by rkfg** [vector-im/riot-android#2264]
So, they don't work anymore. They worked in March I think,
<details>
  <summary>I tried to bisect to find the exact commit (long non-essential explanation)</summary>
<p>but the project is split to SDK and Riot (and I'm not sure which one is to blame) + there's a lot of broken commits (with unresolved conflicts or broken AndroidManifest) + gradle version always changes and desyncs between the SDK and client which results in lots of cryptic errors like "Cannot create variant 'android-lint' after configuration" or inability to change a now-readonly var and so on so I gave up.</p>
</details>
URL previews are very important and I consider this a major regression.

**Comment by logic** [comment]
FWIW, it looks like this remains broken in the 0.8.9 release.

**Comment by rkfg** [comment]
Yes, I installed the release version from F-Droid and indeed the previews don't work.
