### ISSUE TITLE
Riot crashing on selecting settings from the menu

### ISSUE THREAD

**Issue by LakshyAAAgrawal** [vector-im/riot-android#2267]
When Riot is opened, it is taking too much time to load( i.e., initially the Riot logo, and then in the rooms screen, the loading bar is taking forever ). When i go to menu and tap on settings, Riot crashes.
Google play version.

**Comment by LakshyAAAgrawal** [comment]
Not happening now, however, I haven't updated Riot since the issue came up.

**Comment by Currrupted** [comment]
That is very strange! The issue doesn't come up for me either. Apparently has been resolved in some way, though I cannot imagine how.

**Comment by Currrupted** [comment]
I suppose this issue can now be closed, @LakshyAAAgrawal ;)

**Comment by logic** [comment]
FWIW, this exact problem is happening to me now, as of the release of 0.8.10 (f-droid). Everything works fine, as long as I don't open settings; if I do, riot crashes, and I'm forced to log back in again (and recycle e2e keys). Completely reinstalling (also tried downgrading to an older version) does not seem to help.

Running the fdroid version, on Oreo lineageos on a Galaxy S7, against my own homeserver running synapse 0.30.0.

Bug report submitted from within the app as well.
