### ISSUE TITLE
Read up to marker / Sync read status across devices

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#228]

**Comment by giomfo** [comment]
Blocked by server API changes which are pending

**Comment by sbts** [comment]
Can someone add a link to the issue tracking the server changes so we can follow that please

**Comment by giomfo** [comment]
see https://github.com/vector-im/vector-web/issues/1159

**Comment by fblaese** [comment]
the feature was merged and released into matrix-react-sdk v0.8.9 so this can be unblocked again.

**Comment by sabrinaj** [comment]
See https://github.com/vector-im/riot-meta/issues/8.
