### ISSUE TITLE
Messages with code blocks show other HTML as plain text

### ISSUE THREAD

**Issue by tulir** [vector-im/riot-android#2280]
Riot Web:
![image](https://user-images.githubusercontent.com/4224639/40279953-d6a29128-5c54-11e8-9ccc-c9ace8ec7a71.png)

Riot Android 0.8.9-dev `G-#2115`:
![image](https://user-images.githubusercontent.com/4224639/40279954-db074ac4-5c54-11e8-8f34-56947ba80dd0.png)

Message:
```json
{
  "origin_server_ts": 1526827110060,
  "sender": "@tulir:maunium.net",
  "event_id": "$15268271104664MjwaS:maunium.net",
  "unsigned": {
    "age": 276,
    "transaction_id": "m1526827109769.32"
  },
  "content": {
    "body": "**h**<u>t</u>_m_<del>l</del>\n```\ncode block\n```",
    "msgtype": "m.text",
    "formatted_body": "<p><strong>h</strong><u>t</u><em>m</em><del>l</del></p>\n<pre><code>code block\n</code></pre>\n",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!GnEEPYXUhoaHbkFBNX:matrix.org"
}
```

Possibly related to #1973: Pills also show up as raw HTML in messages with code blocks.

**Comment by jaylik** [comment]
This problem seems to occur when `msgtype` is `m.text` but with `m.notice` (atleast `<b></b>` is working).

`<pre><code></code></pre>` seems to be broken with `m.notice`.

**Comment by jaylik** [comment]
riot-web 0.15.4:
![image](https://user-images.githubusercontent.com/586605/40574053-2e3cb49e-60d4-11e8-8453-d2f41b4d3af2.png)

Riot Android 0.8.9 (G-b137)
![screenshot_20180526-105935_riot im](https://user-images.githubusercontent.com/586605/40574060-5835e39c-60d4-11e8-9309-b8f33bb85cb1.jpg)

```
{
  "origin_server_ts": ...,
  "sender": "@...",
  "event_id": "$...:node.fi",
  "unsigned": {
    "age": ...
  },
  "content": {
    "body": "[PROBLEM] test.host.fi: Service TestLocation:\nEvent time: 2018.05.11 18:47:05\nRecovery time: 2018.05.11 19:10:04",
    "msgtype": "m.text",
    "formatted_body": "<strong><font color=\"red\">[PROBLEM]</font> test.host.fi: Service Test</strong><br /><pre><code>Location:\nEvent time: 2018.05.11 18:47:05\nRecovery time: 2018.05.11 19:10:04</code></pre>",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!...:node.fi"
}
```
```
{
  "origin_server_ts": ...,
  "sender": "@...:node.fi",
  "event_id": "$...:node.fi",
  "unsigned": {
    "age": ...
  },
  "content": {
    "body": "[RECOVERY] test.host.fi: Service TestLocation:\nEvent time: 2018.05.11 18:47:06\nRecovery time: 2018.05.11 19:10:05",
    "msgtype": "m.text",
    "formatted_body": "<strong><font color=\"green\">[RECOVERY]</font> test.host.fi: Service Test</strong><br /><pre><code>Location:\nEvent time: 2018.05.11 18:47:06\nRecovery time: 2018.05.11 19:10:05</code></pre>",
    "format": "org.matrix.custom.html"
  },
  "type": "m.room.message",
  "room_id": "!...:node.fi"
}
```

**Comment by jaylik** [comment]
`<pre><code></code><pre>` seems to be breaking other tags.

This is rendering correctly,
```
<p><strong>h</strong><u>t</u><em>m</em><del>l</del></p>\n
```

...this isnt,
```
<p><strong>h</strong><u>t</u><em>m</em><del>l</del></p>\n<pre><code>code block\n</code></pre>
```

**Comment by bmarty** [comment]
I cannot reproduce the issue with latest dev build.

**Comment by Shadow53** [comment]
Multiple users in `#Linux:matrix.org` have been able to confirm that this issue occurs on the **F-Droid** build of Riot, version 0.8.10. One user in the group did not have the issue and they were using the Play Store build.

**Comment by tulir** [comment]
Still an issue with the latest gplay dev build.

**Comment by bmarty** [comment]
https://matrix.to/#/!GzvmKcFNOiOmXzAQgi:matrix.org/%2415307825511171909ExAMV:matrix.org

**Comment by bmarty** [comment]
Issue reproduced when entering:
````
**bold**
```
code
```
````
