### ISSUE TITLE
Exported keys deleted from download dir when uninstalling

### ISSUE THREAD

**Issue by echto** [vector-im/riot-android#2289]
When Uninstalling. Why? Typo in title.

**Comment by bmarty** [comment]
https://stackoverflow.com/questions/35209375/android-6-0-external-storage-files-being-deleted-upon-app-uninstall/35257122

**Comment by bmarty** [comment]
The wording of the popup has been updated to warn the user about this annoying side effect of uninstalling Riot

Available in Riot 0.8.15
