### ISSUE TITLE
UI: Multi-row contact list for home section?

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-android#2297]
Sorry for double posting but initially I posted my suggestion in https://github.com/vector-im/riot-web/issues/2984#issuecomment-354194839 and then was asked to post it under https://github.com/vector-im/riot-android/issues/1800 which is closed now redirecting to the place were I came from.

Would you add an option to list users and rooms in home section of Riot Android/iOS not in this (current) way...

```
PEOPLE
1 2 3 4 5 6 7 8 9 10

ROOMS
A B C D E F G H I J
```

...but in this way:

```
PEOPLE
1 2 3 4 5 
6 7 8 9 10

ROOMS
A B C D E
F G H I J
```

...so that all PEOPLE and ROOMS listed in more than one horizontal line so that the user is _not_ forced to scroll horizontally?
The current way is quite confusing because users are more used to scroll vertically (as they are used to do reading a chat: scrolling vertically). 
More than one time people asked me: where are my contacts and rooms (after adding more and more contacts)?

Thx for Matrix and Riot!

Edit: just suggested https://github.com/vector-im/riot-web/issues/2984#issuecomment-392200590 which I would like to see in addition. Even a combined list for/merge of PEOPLE and ROOMS should be listed in multiple rows, not in one.

**Comment by bmarty** [comment]
Hi, #1800 has not been closed, I close this one as a duplicate then
