### ISSUE TITLE
InitialSync not possible due to malformed JSON

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#2303]
So I have an unfortunate problem. While my laptop and desktop can sync just fine with my Synapse instance, the Android client seems to fail on some malformed JSON returned by the server. Even after deleting and redownloading Riot, and signing in again, upon syncing I get a 'Network Error' toast popping up during the Riot.im loading screen.

Using `adb logcat`, I found the following logs appear:

```
05-28 10:39:27.889 16335 16349 I im.vector.alpha: Background concurrent copying GC freed 645765(21MB) AllocSpace objects, 1(24KB) LOS objects, 49% free, 19MB/39MB, paused 392us total 213.840ms
05-28 10:39:28.113 16335 16335 D RestAdapterCallback: ## failure(): [syncFromToken] with error Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 7208507 path $.rooms.join..state.events[5].content.users.@walle303:kek.community
05-28 10:39:28.114 16335 16335 E EventsThread: Sync V2 onNetworkError Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 7208507 path $.rooms.join..state.events[5].content.users.@walle303:kek.community
05-28 10:39:28.114 16335 16335 E ErrorListener: Network error: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 7208507 path $.rooms.join..state.events[5].content.users.@walle303:kek.community
05-28 10:39:28.127 16335 16335 I EventsThread: Waiting a bit before retrying
```

There's obviously some malformed JSON going on here, though I'm sure how to 1. see what exactly it's tripping on, 2. attempt to move past it.

And from your side I'm not entirely sure what the correct solution is to handle this, though somehow other clients are able to.

**Comment by ara4n** [comment]
this is probably walle303 shoving bigger than maxint timestamps in their events or similar. the way to diagnose is to run a manual initial sync with curl on your account (literally just GET /sync) and the spelunk with jq at the path where android is barfing. or just grep for walle303 membership events to find out dodgy looking ones.

**Comment by anoadragon453** [comment]
Sounds good, will do thanks.

**Comment by anoadragon453** [comment]
![screenshot_2018-05-28_12-06-38](https://user-images.githubusercontent.com/1342360/40611773-8b22adfe-622c-11e8-8524-e7afc22c8138.png)

ah.

**Comment by anoadragon453** [comment]
Yep, left the 1-1 room and now am fine. Perhaps Synapse should filter these? :)
