### ISSUE TITLE
Error while clicking on "Jump to first unread message." inside a room

### ISSUE THREAD

**Issue by anoopcs9** [vector-im/riot-android#2313]
With riot v0.8.9 on LeEco 1s with android 6.0 I noticed an error while trying to click on "Jump to first unread message". Please find the attachment for error details.
![screenshot_20180529-231613-1](https://user-images.githubusercontent.com/5623535/40701113-4a72b3ec-63fa-11e8-9ad4-f8c45fec5f46.jpg)

**Comment by Matrixcoffee** [comment]
I strongly suspect Riot is choking on an HTTP error here. So the actual bug is that it displays this nonsense instead of "500 Internal server error" or whatever the actual error is.

**Comment by anoopcs9** [comment]
Closing the issue in favour of Element.io
