### ISSUE TITLE
GDPR consent link in toasts messages are unclickable

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-android#2329]
we need some way to tell users how to go to the right link, as links in toast messages are unclickable and not copyable. If the user left the announcement room this will cause confusion

**Comment by bmarty** [comment]
Hi @mvgorcum 
Thanks for reporting.
Starting with version 0.8.9, in many cases (but not all the cases) a dialog is displayed when the consent error occurs, to nicely redirect the user to the consent screen (ex: send message to a room, create a room; etc.).
What was your use case?
Thanks

**Comment by mvgorcum** [comment]
As it turns out he was stuck on version 0.7.06 because his phone lacked to space to auto-update. Sorry to bother you :)

**Comment by bmarty** [comment]
ok
