### ISSUE TITLE
Big UI Bug in Farsi or any other RTL layout

### ISSUE THREAD

**Issue by barudaret** [vector-im/riot-android#2376]
Riot-Android version 0.8.10 (G-b139)
Android version 7.1.2

If I set riot to farsi, the layout becomes RTL.  First problem is that the textbox is unusable.  There's nowhere to click to bring up a keyboard and start entering text.  And the thing is like 10x taller than it should be lol

Next problem, messages displayed in unencrypted rooms look funny with bizarre indentation.

Then, it gets even worse in encrypted rooms because all messages just come up blank, and even one-line messages suddenly occupy a screen and a half worth of space (and again this is without actually showing any content).

It's worth noting that farsi language on miniVector keeps the LTR layout and works fine.  In truth, I'd prefer a RTL layout with farsi, but if it makes things more workable/practical/maintainable, do like miniVector and make things LTR.  The layout direction isn't so important to me, much more important to have it work.

See attached photo for what an unencrypted room looks like, and attached video for what an encrypted room looks like.

 

![Unencrypted room](https://i.imgur.com/PZwnc3J.png)

Encrypted room: https://youtu.be/MNgnlBnPje0

**Comment by SafaAlfulaij** [comment]
I say a RTL layout is a must for a RTL language, otherwise **drop RTL languages**!
This situation is a bit better than what was before (where most of the conversation is not visible).

This and #2271 are the same, we should close one as duplicate.

**Comment by bmarty** [comment]
Yes, Riot is not optimized for RTL yet. We will improve this in a near future, please switch to a LTR language in the settings for the moment
