### ISSUE TITLE
Auto completion for / command

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2384]
When user types /, it should be convenient to display the list of available commands in a popin, the same way we display completion for user name

**Comment by manuroe** [comment]
@bmarty, this is a duplicate of https://github.com/vector-im/riot-android/issues/247, no?

This is a long waiting feature...

**Comment by bmarty** [comment]
Sorry, haven't checked for any existing issue

**Comment by bmarty** [comment]
Audrey, it's maybe not long to implement, re-using the popup we already have to suggest users
