### ISSUE TITLE
[not English] app crashes when start jitsi conference or try join to jitsi conference

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-android#2412]
[android_create_conference.log.gz](https://github.com/vector-im/riot-android/files/2166349/android.log.gz)
[android_join_to_conference.log.gz](https://github.com/vector-im/riot-android/files/2166350/android_join.log.gz)
![screenshot_2018-07-05-20-42-32](https://user-images.githubusercontent.com/1297163/42320928-6b8c247a-809a-11e8-9e0d-3c13093a2c80.png)
Android 6.0.1
Riot 0.8.10 from Google Play.

Steps to reproduce:
1. Create room, add 2 users to this room (3 users at all).
2. Start video call
3. App starting jitsi... and crash.

Or if in room already started jitsi:
1. Try join to conference
2. App is crash (see screenshot).

logs create by "adb logcat"
Also I send crash reports from app...

**Comment by albeus** [comment]
I have same problem in my android device: when I try to join to a jitsi conference app crashes.

Details about my setup:

**Device Model**: Moto E LTE (2nd gen) model:XT1524
**Device OS**: LineageOS 14.1-20180126-NIGHTLY-surnia (Android 7.1.2)
**Riot App**: im.vector.alpha 0.8.12 from Google Play

**Comment by bmarty** [comment]
To investigate

**Comment by unclechu** [comment]
I had exact same issue with Samsung Galaxy SM-A520F, joining to Jitsi conference call always failing Riot. I tried to turn off Jitsi for conferences in settings but when I try to call anywhere no one see it.
Could be reproduced on latest version from F-Droid (0.8.12).

**Comment by progserega** [comment]
All my phones is configured in Russians. Now I will try on english language...

**Comment by progserega** [comment]
If I change language to English (USA) in settings of Riot - conference will success start, but on android riot will show "wait circle" on center of window:
![screenshot_2018-08-11-08-21-18](https://user-images.githubusercontent.com/1297163/43984005-2542c35c-9d41-11e8-9cfa-b8e9012878f8.png)
Web-riot not  show this circle at this conference (two active users in room with tree users).

If I change language to Russian and again start conference - it is work. But if I close Riot (back,back, go to "home screen" of android, show list of started app and close all started app) and stat it again and then will start conference - it is fail again. 

May be when mqt_native_modules success started in English - it will success work as well on Russian. When stop Riot  and start it again (on Russian) - riot try init mqt_native_modules on Russian - and Riot is fail.

**Comment by progserega** [comment]
Steps for reproduce bug:

1. Change language of Riot to Russian.
2. Close Riot: Go to "home screen" of android, show list of started app and close all started app. 
3. Start Riot again (it is now in Russian locale)
4. Try start jitsi conference
5. Riot is crash.

**Comment by croulibri** [comment]
Maybe we should change the title because this issue exists for other language than Russian.
French language is affected, maybe other too.

Thanks !

**Comment by progserega** [comment]
How I can change title?

**Comment by chuugar** [comment]
I can reproduce this bug with Riot.im 0.8.23 installed from F-Droid with language set to French.
Jitsi works as expected when language is set to English.

Device : Xiaomi Redmi Note 5
Rom : AOSP Extended

**Comment by bmarty** [comment]
I'm trying to upgrade the Jitsi libraries to fix this issue but I haven't finished yet. To be continued...
