### ISSUE TITLE
i18n request: Include Shwa font

### ISSUE THREAD

**Issue by mitchtbaum** [vector-im/riot-android#2414]
[Shwa](http://shwa.org/english.htm) is a universal alphabet for every spoken human language.  It's like IPA but made for daily usage.

[Shwa Fonts](http://shwa.org/downloads.htm) are available for devices in .otf format; the issue with distributing a keyboard for Android is that the messaging app would still need to have it included for people to be able to use.

Would you please add it to Riot?

**Comment by bmarty** [comment]
Hello @mitchtbaum ,

No, I don't think we can do that, sorry. Feel free to fork Riot and include the Font in your fork

Benoît
