### ISSUE TITLE
Phone call accept button missing

### ISSUE THREAD

**Issue by chris-je** [vector-im/riot-android#2417]
Hey,
Today I updated my Matrix client to version 0.8.12 (G-b146) on my HTC Android 6.0.1.
Since this version, i am not able to accept incoming phone calls.
The accept button doesn't exist anymore, there is just the a hang up button.

**Comment by bmarty** [comment]
To investigate

**Comment by bmarty** [comment]
(thanks @chris-je for reporting this issue)

**Comment by bmarty** [comment]
@chris-je on which screen you don't see the accept button anymore?
- The Room list (home)?
- in a Room?
- the notification?
- Somewhere else?

Thanks for this precision

**Comment by Luraktinus** [comment]
i can confirm, here a Screenshot of the "Incoming Call" screen
@bmarty 
![screenshot_20180713-102507](https://user-images.githubusercontent.com/33608674/42681384-d06d9e94-8687-11e8-8320-3c3b3c192896.png)

**Comment by bmarty** [comment]
Reproduced when the phone is in "Do not disturb" mode

**Comment by dva-re** [comment]
dev build 2258, bug still there regardless of "Do not disturb" mode @bmarty 
![image](https://user-images.githubusercontent.com/10573161/42819469-54c1e45a-89dc-11e8-82aa-9f1c43342434.png)

**Comment by Luraktinus** [comment]
can't reproduce :(

**Comment by dva-re** [comment]
I was send rageshake report with comment 'for issue 2417'

**Comment by bmarty** [comment]
https://github.com/matrix-org/riot-android-rageshakes/issues/2858

**Comment by digititus** [comment]
Confirmed on build #2278. Not able to answer voice or video calls

**Comment by dva-re** [comment]
It starts from build 2247

**Comment by dva-re** [comment]
fixed
