### ISSUE TITLE
Sometimes every message causes a noisy notification

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2420]
@richvdh reports that notifications are unusable on his phone at the moment due to all messages causing a bing

RageShake: https://github.com/matrix-org/riot-android-rageshakes/issues/2755

**Comment by bmarty** [comment]
Settings of notification was making sound in the silence channel.

**Comment by richvdh** [comment]
sorry, haven't really resolved this. I changed the relevant setting from "Make sound" to "No sound or visual interruption", but the phone still vibrates for every message.

**Comment by richvdh** [comment]
![image](https://user-images.githubusercontent.com/1389908/42698413-b94a4ca2-86b5-11e8-89af-9798f3173f11.png)

**Comment by richvdh** [comment]
(setting "silent notifications" to "off" does the same thing)

**Comment by bmarty** [comment]
Ok, let's try again when https://github.com/vector-im/riot-android/pull/2426 will be available

**Comment by BobVul** [comment]
I'm having the same issue. Long-pressing the notification shows which category it falls under; with either power-saving option it's *always* noisy, while the normal/background option uses silent as appropriate.

Unfortunately, in an active room, noisy makes notifications (beyond mention-only) basically completely unusable. It's just endless vibrations.

Device is a Galaxy S9+ on Android 8. I believe I had a similar issue on an S7 on Android 7, though the OS didn't expose settings for noisy/silent notifications.

**Comment by rjurga** [comment]
> it seems to work with "Notification privacy: normal".
> 
> before, I had 'Reduced privacy".

I can confirm that I also had the issue until I changed this notification setting to `Normal`. This happens on both of my phones: Nexus 5X on Android 8.1 and Xiaomi Mi A1 on Android 9.

**Comment by bmarty** [comment]
Should not happen anymore with #2880

**Comment by MurzNN** [comment]
I check this now and seems this is not fixed in 0.8.25, when I change privacy from Normal to Reduced - I got spam of notifications.

**Comment by bmarty** [comment]
Yes, #2880 will be in Riot 0.8.26. You may be interested to test with latest build (https://matrix.org/jenkins/view/MatrixView/job/VectorAndroidDevelop/)
