### ISSUE TITLE
Flair section title in the setting is displayed even if user has no flair

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2430]
![flair](https://user-images.githubusercontent.com/3940906/42690237-c2982af2-86a3-11e8-81c9-844e7576f3e6.png)

**Comment by manuroe** [comment]
We should do like web and displays "You're not currently a member of any communities." to invite users to use the feature. There is a screenshot or riot-web at https://github.com/vector-im/riot-ios/issues/1948.
