### ISSUE TITLE
When user bans or un-bans someone, notify that it will restart the app

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2437]
The first time I did that, I thougt it was a crash :)

Especially, as first sync can be quite long, If user is in low network coverage, he will be warned and may postpone his mute/unmute action

User can be muted in the user detail screen and un-muted in the settings

**Comment by Tyuoli** [comment]
<img width="673" alt="capture d ecran 2018-07-24 a 11 52 41" src="https://user-images.githubusercontent.com/36439413/43130970-333f8cea-8f38-11e8-9e2e-5375b247ae27.png">

**Comment by krombel** [comment]
This is especially an issue when you ban/unban sb. on e.g. riot-web. Then the app restarts without you getting an info on why.
