### ISSUE TITLE
Server Quota Notices in Riot

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2440]
https://github.com/vector-im/riot-meta/issues/213

Implement this: https://www.figma.com/file/MYGeFa5VuuB1PC7BknJE1r0j/HHS-Server-Notices-Riot-Mobile-(Android). 
It may be required to have a look at web UI: https://www.figma.com/file/G2WhEpAyGVbJ0ZQ9GgjcnbQL/HHS-Nagbar?node-id=0%3A1

- [x] Error on /login
- ([ ] Error on message send) <- skipped because we have only one banner on mobile apps (instead of 2 on riot-web). The nagbar will overlay this message
- [x] Error on /sync
    - [x] Hide text composer in that case
- [x] Recognise server notices room(s) and put them in the dedicated section
- [ ] Banner for people who haven't been locked out

**Comment by bmarty** [comment]
Replace by #2547 for the next steps
