### ISSUE TITLE
Recent develop builds crash immediately after start

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#2456]
I tried to update to build 2276 today, but unfortunately this build crashes immediately on starting. I then went to find the oldest build in Jenkins, which turned out to be 2262, tried that, and it also crashes on starting. Next I went back to the latest build I have in my archive, which is 2213, and this one works.

**Comment by mvgorcum** [comment]
2276 doesn't crash for me, running the fdroid version on lineageos 15.1

**Comment by ganfra** [comment]
Should be ok now !

**Comment by Luraktinus** [comment]
I have no crashes in build 2279

**Comment by Matrixcoffee** [comment]
I can also confirm that it no longer crashes. (build 2280)
