### ISSUE TITLE
End-to-end encryption

### ISSUE THREAD

**Issue by brunoqc** [vector-im/riot-android#246]
I saw "End-to-end encryption using Olm (https://matrix.org/git/olm)" on https://play.google.com/store/apps/details?id=im.vector.alpha.

Any progress or ETA?

**Comment by ara4n** [comment]
E2E is in alpha on vector-web - once we've got it working well there 
we'll add it on iOS & Android :)

**Comment by pganssle** [comment]
Where does one go to follow the developments in this? Should I subscribe to this thread or is there somewhere else that I can go to see if an ETA is available?

**Comment by ara4n** [comment]
matrix.org/jira/browse/SPEC-162 is the "master bug", although gets 
updated fairly infrequently relative to the work going on on the core 
e2e repo at https://matrix.org/git/olm.

ETA on Android will probably be 1-2 months away.  It's already landed on 
vector-web/develop however.

On 03/07/2016 23:46, Paul Ganssle wrote:
> Where does one go to follow the developments in this? Should I
> subscribe to this thread or is there somewhere else that I can go to
> see if an ETA is available?
>
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub
> <https://github.com/vector-im/vector-android/issues/246#issuecomment-230171556>,
>
>
or mute the thread
> <https://github.com/notifications/unsubscribe/ABO_vcK7lxhcBReykU_oKcmanawKBaKwks5qSBGIgaJpZM4I9K-R>.
>

**Comment by pganssle** [comment]
@alefteris Thanks for the information. I'm not particularly interested in the web version, but how does E2E encryption work with cross-device syncing if E2E is only implemented on the web portal? Wouldn't the encryption either be compromised by syncing plain text or the Android version would just get a bunch of gibberish synced to it?

**Comment by ara4n** [comment]
No, we support cross-device syncing of encrypted history.

**Comment by takiainen** [comment]
Any news regarding E2E ?

**Comment by florianjacob** [comment]
#627 lists the roadmap & progress regarding the E2E user interface.

**Comment by uhoreg** [comment]
Randomly came across this issue today.  It can probably be closed now?

**Comment by tuxayo** [comment]
Is it already stable on Riot Android?

**Comment by uhoreg** [comment]
I think it's still in beta, but the basic functionality is there.

**Comment by JonasDralle** [comment]
just for protocol: encryption is very stable and I have been using it for months now in various rooms without mayor issues
