### ISSUE TITLE
Bullet points look esthetically bad

### ISSUE THREAD

**Issue by freijon** [vector-im/riot-android#2462]
As discussed [here](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$1532668741230096psxNG:matrix.org) the design of markdown bullet points looks quite bad on certain Android versions.

On Android 4.4 it seems to look fine:
![Android 4.4](https://matrix.org/_matrix/media/v1/download/matrix.org/xMOIqzpYIgIPPuRfhEnUEaMl)

However, on Android 8.1 it looks quite weird:
![Android 8.1](https://matrix.org/_matrix/media/v1/thumbnail/matrix.org/EkktpsmcwTMMOWtclpamaHKJ?width=800&height=600)

In my opinion it should look like in Web or at least like in Android 4.4 in order to increase readability.

**Comment by ganfra** [comment]
Should be better now

**Comment by freijon** [comment]
I agree that it looks better, but I don't think it looks good... The vertical spacing has been fixed but not the missing space after the bullet point. Also, the bullet point is much smaller compared to how it looks like on Android 4.4
