### ISSUE TITLE
geo: URIs are treated as phone numbers

### ISSUE THREAD

**Issue by radiocane** [vector-im/riot-android#2464]
This is a bug. I'm using the FDroid version on LineageOS.
A geo: URI will be shown as two phone numbers. This is due to #1077 (I've tested by building the app with various autoLink values).
I suppose a solution could be using autoLink="web|email" (or maybe "web|email|map") and custom code to Linkify geo: and phone numbers. A solution for geo: URIs could be a custom pattern and Linkify.addlinks like in
https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/utils/GeoHelper.java
https://github.com/siacs/Conversations/blob/master/src/main/java/eu/siacs/conversations/ui/adapters/MessageAdapter.java
I'd love to do this, but I don't understand where to start: where is the code adding an incoming message to a room?
Related: #1329 #2350

**Comment by radiocane** [comment]
Also, #1140

**Comment by bmarty** [comment]
We will see what we can do to improve this
