### ISSUE TITLE
[RIOT.IM - Android] Unable to add Matrix apps

### ISSUE THREAD

**Issue by chevroulet94** [vector-im/riot-android#2466]
Good afternoon,

I have a strange issue on the Android application of Riot. 

I'm unable to add the Matrix apps from the menu. The following error message appears:

"Unable to initialise application. HTTP 403 Invalid token"

The only thing I changed recently was to migrate my reverse proxy from Windows IIS ARR to nginx. But this issue was already presents before. 

Have you already seen something similar?

Thanks in advance!

Florian

**Comment by Luraktinus** [comment]
what version are you using?

**Comment by chevroulet94** [comment]
@Luraktinus I'm using the version 0.8.12 (G-b146) 👍

**Comment by krombel** [comment]
I have that issue as well on current develop (G-b2284)

**Comment by ganfra** [comment]
Should be ok now

**Comment by chevroulet94** [comment]
Thanks for your quick answer @ganfra, but this issue is not resolved. At least not on my side ... I completely uninstall and install from scratch again without success 😞 I also tried to clear all caches before uninstalled it... Could be linked to my nginx reverse proxy ?

Thanks!

**Comment by ganfra** [comment]
To answer your question, it's not linked to your reverse proxy as Matrix apps are available from a server and not your home server.
It sounds like you are installing the app from the PlayStore and not the Jenkins builds 
 (https://matrix.org/jenkins/job/VectorAndroidDevelop/2285).
Please try with this one or wait for the app to be release :-)

**Comment by krombel** [comment]
Just to report: It works for me now (with build 2285). So it should at least work in the next release @chevroulet94

**Comment by chevroulet94** [comment]
@ganfra My bad I mixed up all the things :innocent: @krombel I confirm that with the Jenkins build version 2285 everthing is working as expected !! Many thanks guys ! Like always we can rely on an excellent devs and community ! Keep going like that :+1:

**Comment by sammrafi** [comment]
Hey, I get an error on riot app.I open riot with my homeserver .when I try to add matrrix apps .it show message failed to authenticate user .any one can help me..please also #2285 is not available
