### ISSUE TITLE
Long delay when starting camera

### ISSUE THREAD

**Issue by mehturt** [vector-im/riot-android#2467]
When starting camera to attach photo, there's about 10-15 seconds delay with green circle spinning before I'm able to actually take picture.  Is it possible to reduce this? Thanks.

**Comment by bmarty** [comment]
Hello @mehturt ,

Are you using the native camera? You can check this is the Riot's settings, in the Labs section.

Benoît

**Comment by mehturt** [comment]
Hi @bmarty ,
I'm using whatever the default is.
Checking now I guess I'm not using the native camera.
When switching to native camera, there's no delay.  Actually, when switching back (to not use native camera), it's fast as well.

**Comment by bmarty** [comment]
Mhhh.. So it seems this issue is fixed for you...

**Comment by mehturt** [comment]
Yes, I was checking this in the past few days, and it's OK now even with non-native camera.  So I guess the issue can be closed now.
