### ISSUE TITLE
Clicking on the 'reply to' link fails

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#2469]
with `Sorry, no external application has been found to complete this action.` on current develop

**Comment by bmarty** [comment]
The link is deactivated and a recent merge (not related to reply) has added the Toast.

**Comment by progserega** [comment]
Now it is in version from google play:

![screenshot_20180816-095436](https://user-images.githubusercontent.com/1297163/44179563-cb8d2480-a13a-11e8-8edd-95590ac0a82d.png)

This will be fixed?

**Comment by bmarty** [comment]
Yes, but I cannot say when :(

**Comment by bmarty** [comment]
Ok, the "In reply to" is not a link anymore (fixed in MatrixSdk)

**Comment by progserega** [comment]
Do I can hope that it will become link again and press on this link will be redirect to source message (which replying)?

**Comment by bmarty** [comment]
Yes, it's the target, but I do not know when it will be done
