### ISSUE TITLE
Disable Firebase analytics

### ISSUE THREAD

**Issue by Bubu** [vector-im/riot-android#2481]
Someone checked the traffic riot sends and noticed it reports stuff via firebase analytics: https://www.kuketz-blog.de/matrix-messenger-riot-im-play-store-mit-aktivem-google-tracking/

Some more details here, though I'm not sure how it actually get's activated: https://github.com/siacs/Conversations/issues/3041

**Comment by ara4n** [comment]
empirically this still comes up on https://reports.exodus-privacy.eu.org/en/reports/51160/ as having Firebase Analytics enabled..

**Comment by ara4n** [comment]
see also https://social.tchncs.de/@angry/101398604701463362

**Comment by bmarty** [comment]
Will be fixed along with #2205

**Comment by Tokodomo** [comment]
It is possible to remove firebase analytics classes from gradle:
https://github.com/siacs/Conversations/commit/c2067e3b56364317bc384b55e320b72326fb1de6
https://github.com/nextcloud/android/commit/0d78339bb5ed412037c5b885688bfcc2178e757a
https://github.com/signalapp/Signal-Android/commit/a6564f8f8458fa256e4b68fef65210ee0c30d518

**Comment by bmarty** [comment]
FTR, command to check dependencies:
> ./gradlew vector:dependencies

**Comment by bmarty** [comment]
FTR: https://reports.exodus-privacy.eu.org/en/reports/72513/
