### ISSUE TITLE
Improve WRITE_EXTERNAL_STORAGE permission handling

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#2483]
I have the 3 following remarks about the WRITE_EXTERNAL_STORAGE permission:

- [x] Why this permission is requested when the Home activity is resumed? This request is displayed just after the login, it is not understood by the new users. Wouldn't there be a better place to do it?

- [ ] If the user doesn't grant this permission, the export of the E2E encryption keys fails. This permission must be checked before exporting the keys

- [x] When the user wants to add an attachment in a room by taking a picture, the operation failed silently if this permission is not granted (The camera preview is launched but the taken picture is not attached). This permission must be required before launching the camera.

**Comment by shtrom** [comment]
I can confirm this is a bit confusing. I have got into the habit of only granting permissions only when I know what action of mine they are needed for. This definitely doesn't seem to be needed to display the home screen (and indeed, refusing to grant that permission at this stage doesn't result in any incorrect behaviour).

It would make much more sense to ask for this permission specifically when the user tries to add attachments or export keys.

**Comment by bmarty** [comment]
Fixed by #2518
