### ISSUE TITLE
code blocks are escaped and therefore hard readable

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#2484]
a fix to remove `<p>` from message contents somehow introduced the behavior that code blocks are now fully escaped. An example can be seen here: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$15332808485OvDAl:msg-net.de

**Comment by tulir** [comment]
The example:
![image](https://user-images.githubusercontent.com/4224639/43630624-802ee6c6-9709-11e8-8764-c608e0811e1f.png)

**Comment by bmarty** [comment]
Hi @krombel ,

thank for reporting this issue. We will have a look on it

**Comment by bmarty** [comment]
@ganfra can we close this issue then?
