### ISSUE TITLE
Implement room members lazy-loading

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2494]
vector-im/riot-meta#209.

Synapse branch: `matthew/lazy_load_messages_api`

Tasks below represent the cookbook used on iOS (https://github.com/vector-im/riot-ios/issues/1931). It may need some adaptation for Android:

- [ ] Local lazy loading (@bmarty) 
    - [ ] SDK: Make [MXRoom liveTimeline:] async
         - [ ] MXStore: Load MXRoomState asynchronously
         - [ ] MXStore: no more preload room states at startup
    - [ ] Use MXRoomSummary instead of MXRoom.state as much as possible
    - [ ] Riot: Make it build and run
- [ ] SDK: Decouple room members from MXRoomState:
    - [x] MXRoomState.displayName is obsolete now and make an heavy requirements on room members. Use MXRoomSummary.name everywhere.
    - [x] Create a MXRoomMembers object, property of MXRoomState, it will contain already lazy-loaded room members. This is list is enough to render the current timelime
    - [x] Get the full list of room members from a separate API (` -(MXRoomMembers*)[MXRoom members:]`)
        - [x] Make its access async (its methods could be async later)
        - [x] Make its access trigger a /members request if needed
    - [ ] (Have a separate storage for them)
- [ ] SDK: Have a MXSession.syncFilterId property
    - [ ] implement filters
        - [x] Create class models for filters
        - [x] create a factory to build a lazy-load filter
        - [x] Implement CS API to create filter
        - [x] Store them locally
        - [ ] write tests
    - [ ] Use them
        - [ ] `[MXSession start:]` -> `[MXSession startWithSyncFilter:]` and `[MXSession startWithSyncFilteId:]`
       - [x] store the `MXSession.syncFilterId`
       - [ ] have `MXSession.syncWithLazyLoadOfRoomMembers`
       - [x] manage fallback if the server does not support lazy-loading
- [ ] SDK: Manage new summary API (https://docs.google.com/document/d/11i14UI1cUz-OJ0knD5BFu7fmT6Fo327zvMYqfSAR7xs/edit#heading=h.qif6pkqyjgzn)
    - [x] members count
    - [x] compute fallback i18ned display name
- [x] SDK: Use a LL filter in /messages
     - [x] pass the filter according to `MXSession.syncWithLazyLoadOfRoomMembers` value
     - [x] process new `state` field in the response
- [x] SDK: Use a LL filter in /context
- [ ] SDK: Use new `at` params in` /members` 
     - [ ] Update the CS API
     - [ ] Manage race contions with /members: js does [that](https://github.com/matrix-org/matrix-js-sdk/commit/62333b3e2c01c84257469cb81f6c9a2780e51c91), ios [that](https://github.com/matrix-org/matrix-ios-sdk/pull/553) as discussed [here](https://matrix.to/#/!DdJkzRliezrwpNebLk:matrix.org/$153494717911304wGuhN:matrix.org)
- [x] /versions
     - [x] expose it in the SDK
     - [x] with `"unstable_features": {"m.lazy_load_members": true}`
- [ ] Riot: Check search display. The code must use `profile_info`
- [x] Riot: Add a setting in LABS to enable the feature
    - [x] Riot: Fallback to no LL if the user HS does not support it (/versions unstable_features above)
    - [ ]  Enable it by default. Reset it to enabled for new login/registration
- [ ] Riot: Make sure read-receipts are correctly displayed
- [ ] Room status: joined/invited
    - [x] Store this information regarding the room position in sync return, instead of looking for user membership value (RoomMember of current user is not always known with LL). 
    - [ ] Force a clear cache for next installation
- [ ] Tests
    - [ ] Write lazy-loading tests and regression tests 
    - [ ] Make them pass

New point:
- [x] reset the boolean to fetch again a /members request in case of a room gap detection during sync
- [ ] use a limit of 30 in the LL filter

**Comment by bmarty** [comment]
Done, will treat potential pb in dedicated issues
