### ISSUE TITLE
After "Send anyway" action, the message disappears

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2508]
Reported by zottel: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$15338406003tgEEX:matrix.zottel.net

Strange behavior when sending in an encrypted room: After the list of new devices was shown and I pressed "Send anyway", the message being sent was not shown at the bottom of the screen anymore, it was as if nothing was being sent. Only when I went out of the room and back in, the message currently sending was shown again.

**Comment by dva-re** [comment]
I confirm. I also have on dev-build 2330

**Comment by jo-so** [comment]
I can confirm this behaviour for 0.8.15 (F-e5478fd4).

**Comment by bmarty** [comment]
Looks similar to #2569

**Comment by bmarty** [comment]
Ok, I fixed that
