### ISSUE TITLE
Removing room from 'low priority' does not work

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#2526]

**Comment by krombel** [comment]
it somehow works for me now as well but I have to close the home view and reopen it => I assume live update fails"

**Comment by bmarty** [comment]
@ganfra, can you have a quick look please?

**Comment by bmarty** [comment]
Ok, it's the same with favorite

**Comment by bmarty** [comment]
Ok, fixed on SDK

**Comment by dkanada** [comment]
I was just about to open an issue for this, glad it has already been fixed!
