### ISSUE TITLE
Equal sign forbidden in join UI prevents joining gitter-bridged rooms

### ISSUE THREAD

**Issue by Ekleog** [vector-im/riot-android#2542]
All is in the title. This will likely be a 1-character diff, but I haven't found where the check is made in GitHub's UI :)

**Comment by bmarty** [comment]
Have you got an example of room alias with '='? The fix should be similar to https://github.com/matrix-org/matrix-android-sdk/pull/337

**Comment by Ekleog** [comment]
All gitter-bridged rooms have a '='. Example: #gitter_tokio-rs=2Ftokio:matrix.org .

**Comment by bmarty** [comment]
What we need is an exhaustive list of allowed chars for a room alias.

**Comment by Ekleog** [comment]
I've opened https://github.com/matrix-org/matrix-android-sdk/pull/344, even though I don't have an exhaustive list of allowed chars :)

**Comment by bmarty** [comment]
Ok, thanks. I've asked to the team but this list does not exist yet...

**Comment by bmarty** [comment]
https://github.com/matrix-org/matrix-android-sdk/pull/344 merged
