### ISSUE TITLE
E2E keys import should use the openFileSelection function of the ExternalApplicationsUtil class

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#2544]
Note 1: a new param should be added to the `openFileSelection` function to handle the multi-selection option.

Note 2: ACTION_OPEN_DOCUMENT intent should be considered instead of ACTION_GET_CONTENT, for Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT.
(see https://developer.android.com/guide/topics/providers/document-provider#client)

**Comment by bmarty** [comment]
Done
