### ISSUE TITLE
Riot loads white window flashing black or after data cleaning opens white screen and crashes

### ISSUE THREAD

**Issue by Mikaela** [vector-im/riot-android#2549]
The title says everything.

Riot Android Play Store Beta 0.8.13

OnePlus 3 / Android 8.0.0 / (OxygenOS beta39)I

I don't have access to adb as my phone's USB port is somehow broken only permitting normal charging.

**Comment by Mikaela** [comment]
This doesn't seem to be the case anymore.

**Comment by bmarty** [comment]
Good news...
