### ISSUE TITLE
"Agree to Terms and Conditions" in App notification is not helpful

### ISSUE THREAD

**Issue by empwilli** [vector-im/riot-android#2551]
I'm not too good with the proper terms in Android apps, but I'll give it a try to explain what I mean in here.

If you try to use the Matrix.org servers without having accepted the terms and conditions before, an in app overlay notification with a link to the agreement text and form is shown. This is well meaning, however, one may not acutally click / copy / whatsoever that link, since clicking on it removes the notification.

I understand that the shown message might be from the chosen server and not from the app itself, however, imho this really confuses users.

**Comment by bmarty** [comment]
Yes, it will be fixed in the next release. You should see a proper dialog instead of the Toast in this case
