### ISSUE TITLE
invites don't tell you what room you are being invited to

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#2555]
Either this has never worked, or it regressed when we switched from v1 to v2 API (plus the spec was wrong until today). We should be inspecting `event.unsigned.invite_room_state` for info about invites rather than `event.invite_room_state` as per https://github.com/matrix-org/matrix-doc/pull/1568 (and https://github.com/vector-im/riot-ios/issues/2010 and https://github.com/vector-im/riot-web/issues/7229)

**Comment by bmarty** [comment]
@ara4n is it supposed to be fixed ASAP?

**Comment by bmarty** [comment]
Currently nor Riot neither the Android SDK uses what is in "invite_room_state" data.
It seems that it can be useful when dealing with an invite for a Room from another HS.
I will ensure "invite_room_state" is parsed correctly in the SDK for now
