### ISSUE TITLE
'in reply to' link not working

### ISSUE THREAD

**Issue by lub** [vector-im/riot-android#2561]
Hi,

when I tap on the 'in reply to' link in a reply I get the following toast:

> Sorry, no external application has been found to complete this action.

If I copy the link from the reply's source and send it as a normal message it works as expected and jumps to the linked event. (Although I'm not entirely sure if this is actually the expected behavior for the 'in reply to' link itself)

I've also submitted a rage shake.

Version: G-b148

**Comment by bmarty** [comment]
Thanks for reporting the issue. It's fixed in the next coming release (the link has been disabled)
