### ISSUE TITLE
Message lost after "Resend all" in encrypted room

### ISSUE THREAD

**Issue by jo-so** [vector-im/riot-android#2569]
Riot 0.8.15 (F-e5478fd4)

1. enter a room with encryption
1. disable network (wifi) connection
1. write a message
  ![screenshot_20180902-212901](https://user-images.githubusercontent.com/23032146/44960023-0becf080-aef8-11e8-9986-522542131586.png)
1. enable network connection
1. hit "resend all"
  ![screenshot_20180902-212935](https://user-images.githubusercontent.com/23032146/44960024-0c858700-aef8-11e8-87cc-2b9b5bba0065.png)
1. the message vanishes
  ![screenshot_20180902-212946](https://user-images.githubusercontent.com/23032146/44960025-0c858700-aef8-11e8-90b3-5e71a265eff0.png)

**Comment by radiocane** [comment]
I lose messages after "resend all" also in unencrypted rooms

**Comment by bmarty** [comment]
Ok, the "resend all" action bug is fixed. The message still disappear but this is tracked by #2508
