### ISSUE TITLE
Play button on a video is so ugly...

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2577]
Send a video to a Room, then open it with the Riot Media Viewer.
The play button looks terrible:

![screenshot](https://user-images.githubusercontent.com/3940906/45171375-840e2b80-b202-11e8-9072-0598855bcde2.png)

**Comment by bmarty** [comment]
CC @nadonomy

**Comment by dkanada** [comment]
Side note, you mentioned using wrap width for the icon size, but now it looks way too small on my phone. I think switching it back to dp might look better.

**Comment by bmarty** [comment]
Hi @dkanada ,

Thanks for the update, I will revert to 100dp

Benoît

**Comment by bmarty** [comment]
Revert to 100dp and other suggested change by @dkanada are done in PR #2583
