### ISSUE TITLE
.well-known support

### ISSUE THREAD

**Issue by mvgorcum** [vector-im/riot-android#2582]
https://matrix.org/docs/spec/client_server/r0.4.0.html#server-discovery

**Comment by florianjacob** [comment]
As of #3001, this should already be part of 0.8.24: https://github.com/vector-im/riot-android/blob/develop/CHANGES.rst#changes-in-riot-0824-2019-03-07

**Comment by mvgorcum** [comment]
I agree, I'll close the issue.
