### ISSUE TITLE
play.google.com "coming soon"

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-android#2587]
I see this "Coming soon" for about a year!

• Add your own integrations, bridges and bots!
• Email notifications of missed messages and invites
• Screen sharing
• Login as multiple users at the same time

Looks like it should be removed.

**Comment by bmarty** [comment]
Yes, let's update the store description. @lampholder can you handle this please?

**Comment by lampholder** [comment]
I've deleted the 'coming soon' section; changes should go live shortly.

**Comment by bmarty** [comment]
Thanks
