### ISSUE TITLE
make the media adapter in the room activity less glitchy

### ISSUE THREAD

**Issue by dkanada** [vector-im/riot-android#2602]
Can I remove the WebView and replace it with something like [this](https://github.com/davemorrissey/subsampling-scale-image-view) for the images? It looks like WebView was only used to add zoom support for images, and I think replacing it might fix a lot of loading issues I have seen for gifs and images. Would also allow for some cool features like subsampling and double tap to zoom. Also, maybe we could either make a custom VideoView or implement a popular library to do the job.

**Comment by bmarty** [comment]
Yes, I was thinking of using PhotoView (https://github.com/chrisbanes/PhotoView). I do not know which one is better. Maybe @ganfra has an idea.
Also the WebView was used to display Gif and video.

**Comment by dkanada** [comment]
Was gonna move the app to PhotoView but bitmap loading is currently tied into the sdk and this probably needs some conversation on the best way to move over to PhotoView and Glide. Maybe the SDK shouldn't handle actually loading the downloaded files into views and instead just handle downloading, caching, et cetera.

**Comment by bmarty** [comment]
Yes, the Matrix Android Sdk should not even know what a `View` is. We will improve this in the future.

**Comment by zai666** [comment]
Everytime I am sent a gif I must download it to view it

**Comment by dkanada** [comment]
@zai666 that's actually the exact issue I wanted to fix with this change. Another reason was that the WebView doesn't work with transparent images, whereas glide handles them quite well.

**Comment by bmarty** [comment]
@dkanada, can we consider that this issue is totally addressed by #2731 and can be closed?

**Comment by dkanada** [comment]
The main issues were fixed, but there are still a few smaller issues. Trying to download more than one or two files at a time by swiping left or right usually breaks the adapter, and thumbnails are never shown at least in encrypted rooms, not sure about unencrypted rooms.

**Comment by bmarty** [comment]
Ok thanks, replaced with #2751
