### ISSUE TITLE
Nested replies with blockquotes are broken

### ISSUE THREAD

**Issue by tulir** [vector-im/riot-android#2612]
Replying to a message that replies to a message with a blockquote causes riot android to fail to strip the first reply fallback, which causes the new message to contain an invalid nested reply fallback. That invalid nested reply fallback will then somewhat break everything else.

I think this is caused by riot android removing reply fallbacks without using the `<mx-reply>` tag, even though the `<mx-reply>` tag was literally only added to avoid this bug.

![image](https://user-images.githubusercontent.com/4224639/45954853-df1f8b00-c016-11e8-8ff5-ea7c4252335e.png)

![image](https://user-images.githubusercontent.com/4224639/45954860-e2b31200-c016-11e8-8929-bd49a905eee1.png)

**Comment by bmarty** [comment]
Hi @tulir ,
Thanks for reporting,

FTR, the strip is done here: https://github.com/matrix-org/matrix-android-sdk/blob/develop/matrix-sdk/src/main/java/org/matrix/androidsdk/data/RoomMediaMessagesSender.java#L517

Let's investigate the special case you've reported

**Comment by bmarty** [comment]
Done
