### ISSUE TITLE
Nickname completion of displaynames is broken

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#2613]
Action:
* Type first three letters of someone's displayname

Expected result:
* After a few seconds, see a popup with possible completions

Actual result:
* Nothing happens

Affected versions:
* Latest lazyloading build
  * With lazyloading enabled
  * With lazyloading disabled
* Apparently the latest version released to F-Droid/Google is also affected

---

Completion of matrix IDs works as expected. (`@bla...`)

**Comment by tulir** [comment]
Seems to work fine for me on G-b2381 with lazyloading disabled

**Comment by bmarty** [comment]
Hi @Matrixcoffee ,
Thanks for reporting.
I'll check this
Benoît

**Comment by bmarty** [comment]
Ok, the fix is merged
