### ISSUE TITLE
missing config.json

### ISSUE THREAD

**Issue by mooo5e** [vector-im/riot-android#2631]
Desktop application has it's config.json file, where it stores some of settings.
I want to change "integrations_ui_url", "integrations_rest_url", "integrations_widgets_urls", "integrations_jitsi_widget_url" for my android application but can't find the place where I could edit it. Eny help please?

**Comment by bmarty** [comment]
Hi @mooo5e,

"integrations_ui_url", "integrations_rest_url" are defined [here](https://github.com/vector-im/riot-android/blob/develop/vector/src/main/res/values/donottranslate.xml#L12).

"integrations_widgets_urls" uses same value than "integrations_rest_url" (Cf. [here](https://github.com/vector-im/riot-android/blob/develop/vector/src/main/java/im/vector/widgets/WidgetsRestClient.java#L37))

"integrations_jitsi_widget_url" is defined [here](https://github.com/vector-im/riot-android/blob/develop/vector/src/main/java/im/vector/activity/JitsiCallActivity.java#L66).

Maybe the two last should also be present in the file `donottranslate.xml`

**Comment by mooo5e** [comment]
So those values are being hardcoded into the app on compilation and can't be modified after installing on phone?

**Comment by bmarty** [comment]
Yes, I think it's the same than for Riot-web
