### ISSUE TITLE
back paginating in a room with LL makes some avatars to vanish

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2639]
They also vanish at first access to a room, when we fetch all the members.

**Comment by progserega** [comment]
In room with me and one user - at end screen user have avatar and nick, at begin screen - it have only mxid.

LL enabled
Android 6.0.1
Riot 0.8.16 (gplay)

![screenshot_20181009-185437](https://user-images.githubusercontent.com/1297163/46665521-708e2000-cc07-11e8-9ac9-a7e300015e59.png)
