### ISSUE TITLE
E2E Key Backup

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-android#2642]
Part of https://github.com/vector-im/riot-meta/issues/222

- [ ] Read the [proposal doc](https://github.com/uhoreg/matrix-doc/blob/e2e_backup/proposals/1219-storing-megolm-keys-serverside.md) for context
- [ ] Maybe read the [associated Google doc](https://docs.google.com/document/d/1MOoIA9qEKIhUQ3UmKZG-loqA8e0BzgWKKlKRUGMynVc/edit#heading=h.u2mqa2o4v294) if the proposal doc leaves anything unexplained
- [ ] Port everything from [@dbkr's E2E backups js sdk branch](https://github.com/matrix-org/matrix-js-sdk/tree/dbkr/e2e_backups)
- [ ] Port the placeholder UI from [@dbkrs E2E backups react sdk branch](https://github.com/matrix-org/matrix-react-sdk/tree/dbkr/e2e_backups)

@nadonomy is working on the proper UX in parallel, so check whether he's produced any final E2E UX designs before getting started on the UI.

**Comment by bmarty** [comment]
FTR: on iOS: https://github.com/vector-im/riot-ios/issues/2070
