### ISSUE TITLE
m.emote message does not parse links

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#2652]
Sending the message:

```
/me wants to go to [the park](https://thepark.com) today
```

has a hyperlink on Riot web but not in Riot android, even though `formatted_body` contains a `<a>` tag.

**Comment by bmarty** [comment]
Done

**Comment by bmarty** [comment]
Actually emote message wasn't able to display any formatted element (bold, italic, link, etc.) due to this bug

**Comment by bmarty** [comment]
You will be able to go to the park fix the fix :)

**Comment by anoadragon453** [comment]
Hooray, thanks Benoit!
