### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-android#2659]
The latest version:
Android 3.2.1

Has below compile error
D:\code\matrix\riot-android\vector\src\main\java\im\vector\activity\StickerPickerActivity.kt: (142, 30): Unresolved reference: getBasicGson

**Comment by bmarty** [comment]
Hello, yes, it's due to change in the SDK. Please compile against the latest develop branch of the SDK.
You can clone the Android Matrix Sdk and then run script ./compile_with_sdk_project.
or just check out the `master` branch of Riot.

**Comment by wjhtinger** [comment]
I have use the master branch of Riot, but has the same issue.
