### ISSUE TITLE
unable to share Fotos, Files from other apps to riot-android since update 0.8.18 and using new Status.im Theme

### ISSUE THREAD

**Issue by chrissi55** [vector-im/riot-android#2672]
I updated to 0.8.18
I switched to settings -> Themes from "light Design" to new "Status.im" Theme. Since that i can't share Files, Screenshots by klicking on "Share with.." using the fork Symbol in other apps.

Means when e.g. using the Gallery App, klicking fork Symbol in a Foto to "share it with ...." then selecting riot .... nothing happened. (riot crashed and looped in restarts)
Back to old "default" Design and everything works fine again...

Any ideas?

My Nokia7+ ist running under Android Pie 
I'm using the 0.8.18 from Fdroid Shop no PlayStore Version.

**Comment by jnpf** [comment]
Same here (play store version, pie on pixel 2 XL)

**Comment by bmarty** [comment]
Thanks for reporting I will look at this

**Comment by bmarty** [comment]
@vulet would you have a look to this issue please?

**Comment by jnpf** [comment]
Thank you @vulet.

In addition, I'm happy to get a new theme on mobile - don't like that mindgreen (sorry @bmarty ✌️😁)

Is it possible to create a custom design based on yours, vulet?

**Comment by vulet** [comment]
Thank you for reporting @jnpf. The previous issue should be covered [here](https://github.com/vector-im/riot-android/pull/2670/commits/1fc57fa76dd89390fc573f7a9bb9e2a7044fcea6). The Status.im theme was already existent on riot-web, so I thought it would be a safe thing to port over here. I don't think riot-web currently supports custom themes, but perhaps it might still be alright? It might be a good idea to open up a new issue, and also to see @bmarty's thoughts.

**Comment by bmarty** [comment]
The green color of riot themes will be replaced in a near future.
By the way, the Status theme should not use it anymore (colors are more blue), there is still a few changes to do to replace it every where (overriding the AppCompat theme default color)
