### ISSUE TITLE
/markdown no longer works

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#2673]
Trying to use the `/markdown` command doesn't seem to change or toggle anything.

Version 0.8.18 (F-d9d8db49)

**Comment by bmarty** [comment]
It's working for me...
`/markdown` does not seems to work... I check this
Try to change the settings from the settings screen?

**Comment by anoadragon453** [comment]
Ahh, that's actually much better than doing `/markdown` and just expecting a toggle to have worked.

Perhaps there could be a message that pops up saying "either on or off should be written after /markdown"?

And/or the auto complete popup for commands should have an
`<on|off>` for the /markdown command.

**Comment by bmarty** [comment]
yes, I'm coding it :)

**Comment by anoadragon453** [comment]
Awesome, thank you!
