### ISSUE TITLE
Clicking a room link loads forever even if one is already in that room

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/riot-android#2674]
Clicking a room link (be it pill or not) in a chat room takes you to the home screen and just loads forever. The room is never opened.

This happens whether you are already in the room or not.

Version 0.8.18 (F-d9d8db49)

**Comment by anoadragon453** [comment]
Additionally, users report that matrix.to links handled by Riot Android run into the same loading problem.

**Comment by styromaniac** [comment]
I can confirm since I brought up the issue. Anoadragon453 is actually confirming what I said.

**Comment by anoadragon453** [comment]
Indeed. That is true.

**Comment by anoadragon453** [comment]
Also happens for the "Jump to first unread message" button.

**Comment by BloodyIron** [comment]
I'm also seeing the "loading spinning wheel" on android:

- riot 0.8.18 G-b156
- android 7.0

It takes me to the list of rooms/chats I'm in, then does the loading animation, then just times out after a handful of seconds.

**Comment by bmarty** [comment]
Fixed along with #2689
