### ISSUE TITLE
Bug report -> Report bug in main menu

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [vector-im/riot-android#2675]
![bug](https://user-images.githubusercontent.com/14617699/47259364-4b27ce80-d4b1-11e8-909c-a5e7ae35e908.png)

I'm not an english speaker, but "Bug report" is a fact and "Report bug" is an action, is not it?

**Comment by vulet** [comment]
"Settings" is also a noun. The "Exit" and "Sign out" happen instantly, aside from the confirmation to "sign out". This is opposed to "settings" and "bug report" listed, as you are in fact being directed to a new page where you are setting the presets for the verb to take place.

**Comment by vulet** [comment]
"Settings" is also a noun. The "Exit" and "Sign out" happen instantly, aside the confirmation to "sign out". This is opposed to "settings" and "bug report" listed, as you are in fact being directed to a new page where you are setting the presets for the verb to take place.

**Comment by c-e-p-x-u-o** [comment]
Thank you (:
