### ISSUE TITLE
qbittorrent crashing after 20 sec

### ISSUE THREAD

**Issue by madmilltown** [vector-im/riot-android#2678]
qBittorrent version: v4.1.3

Caught signal: SIGSEGV
Stack trace:
  /usr/lib/libQt5Network.so.5 : ()+0x9aca4  [0x7f0da93dfca4]
  /usr/lib/libQt5Network.so.5 : ()+0x9959b  [0x7f0da93de59b]
  /usr/lib/libQt5Core.so.5 : QObject::event(QEvent*)+0xe2  [0x7f0da90a0352]
  /usr/lib/libQt5Widgets.so.5 : QApplicationPrivate::notify_helper(QObject*, QEvent*)+0x84  [0x7f0da9c63e14]
  /usr/lib/libQt5Widgets.so.5 : QApplication::notify(QObject*, QEvent*)+0x211  [0x7f0da9c6b6e1]
  qbittorrent : Application::notify(QObject*, QEvent*)+0x23  [0x55937cff8b43]
  /usr/lib/libQt5Core.so.5 : QCoreApplication::notifyInternal2(QObject*, QEvent*)+0x179  [0x7f0da9075c39]
  /usr/lib/libQt5Core.so.5 : QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*)+0x1dc  [0x7f0da9078ccc]
  /usr/lib/libQt5Core.so.5 : ()+0x2c59d4  [0x7f0da90c99d4]
  /usr/lib/libglib-2.0.so.0 : g_main_context_dispatch()+0x2bf  [0x7f0da7d213cf]
  /usr/lib/libglib-2.0.so.0 : ()+0x6cf89  [0x7f0da7d22f89]
  /usr/lib/libglib-2.0.so.0 : g_main_context_iteration()+0x2e  [0x7f0da7d22fce]
  /usr/lib/libQt5Core.so.5 : QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)+0x69  [0x7f0da90c8fc9]
  /usr/lib/libQt5Core.so.5 : QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)+0x13c  [0x7f0da90748cc]
  /usr/lib/libQt5Core.so.5 : QThread::exec()+0xb9  [0x7f0da8ebdeb9]
  /usr/lib/libQt5Core.so.5 : ()+0xc3f65  [0x7f0da8ec7f65]
  /usr/lib/libpthread.so.0 : ()+0x7a9d  [0x7f0da8deaa9d]
  /usr/lib/libc.so.6 : clone()+0x43  [0x7f0da89eab23]
Segmentation fault (core dumped)
 
running manjaro18 xfce on thinkpad t400

**Comment by mattboardman** [comment]
What does this have to do with Riot for android?
