### ISSUE TITLE
App becomes unusable in RTL mode

### ISSUE THREAD

**Issue by OffifialMITX** [vector-im/riot-android#2708]
When selectin "Force RTL layout direction" in the developer settings the app becomes messed up to a point where one can't even read or write mesages.

I don't actually want this to be fixed, since I highly doubt that _anyone_ needs this and there are more important things to take care of, but I wanted this to be a known thing.

**Comment by bmarty** [comment]
Hi @OffifialMITX,

Yes, thanks for reporting. I'm glad to announce that RTL support is coming in the next release. See #2271 and #2693 

Benoit
