### ISSUE TITLE
Build option to not fall back to Google's TURN server

### ISSUE THREAD

**Issue by AltNico** [vector-im/riot-android#2721]
At F-Droid we recently learned that Riot falls back to Google's TURN server when a home server does not provide its own TURN server. Is this correct?

To [quote from the issue](https://gitlab.com/fdroid/fdroiddata/issues/1434) I just opened in _fdroiddata_:
> In the developer chat @mvgorcum shared that [Riot falls back to using Google's servers](https://matrix.to/#/!ZmSZzxujGNoCyoCETU:matrix.org/$154185961919nzzjN:matrix.vgorcum.com) when a user's home server doesn't provide [its own TURN server](https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.rst). [...]
> This is a big metadata leak that wasn't obvious to me as an operator of my own Synapse instance. Also, I don't think many of Riot's users know about this fallback. To make this clear: voice and video streams will not be relayed though Google. Their TURN server is just telling users their external IP addresses so they can attempt a peer-to-peer call. Still, this gives Google information about the social graph of users. [...]
> If a home server doesn't provide a TURN server, Riot apparently falls back to using Google's one.
> To prove his statements, @mvgorcum linked two pieces of code:
```java
/** The fallback server to use for STUN. */
MatrixCall.FALLBACK_STUN_SERVER = 'stun:stun.l.google.com:19302';
```
> Source: https://github.com/matrix-org/matrix-android-sdk/blob/88d96c710392e1f1c6ed1646788938a569e27a2f/matrix-sdk/src/main/assets/www/call.js#L58
```java
// define at least on server
if (iceServers.isEmpty()) {
  Log.d(LOG_TAG, "## createLocalStream(): use the default google server");
  iceServers.add(new PeerConnection.IceServer("stun:stun.l.google.com:19302"));
}
```
> Source: https://github.com/matrix-org/matrix-android-sdk/blob/6ba5f6c27ed841b5695f84084457fc293fbff777/matrix-sdk/src/main/java/org/matrix/androidsdk/call/MXWebRtcCall.java#L597

As a first step I proposed adding a warning to Riot's description in F-Droid to inform users about this behavior of Riot. In addition, I think a build option for Riot would make sense that disables this fallback to Google's servers.

**Comment by manuroe** [comment]
This is fixed by https://github.com/vector-im/riot-android/issues/3223
