### ISSUE TITLE
Usability: Contact id is difficult to find

### ISSUE THREAD

**Issue by vranki** [vector-im/riot-android#2756]
I have a friend who's on both Matrix and Telegram (via gateway). I'd like to share him to another friend.

First issue is that I can't figure out which contact is his Matrix contact a he's with two identities. I can't find the user id anywhere. I don't know which contact is from Matrix and which from Telegram. 
Also there is no "share contact" function found anywhere. I search from contact's information view and long press the contact, but nothing there.

Finally I had to ask on a matrix channel how to see contact id. The answer is to tap on the contact name to reveal the id. That's poor usability.

Solution would be to display the id with contact's name or a visible button to reveal it.

**Comment by bmarty** [comment]
Yes, the user id may be hard to find and you have effectively to click on the user display name, just below the avatar on a member screen.

Please note that a long click on the user id will copy it.

It's maybe a good idea to display both user name and user id, on two separate lines on a member screen.

**Comment by bmarty** [comment]
After discussion with the team here, we want to add a section `advanced` at the bottom of a member detail page, to display its userId (the same way it is done on a Room detail page, for roomId)

**Comment by vranki** [comment]
That would solve this issue IMO and should be easy to implement.

**Comment by bmarty** [comment]
We will add the userId below the username, as RiotWeb does.
Simple click will replace long click to copy username or user id

**Comment by vranki** [comment]
I can implement this - looks like quite easy task.

**Comment by bmarty** [comment]
Done

**Comment by bmarty** [comment]
![displaynameuserid](https://user-images.githubusercontent.com/3940906/49952879-2b36e900-fefd-11e8-8114-97e34b4fb89e.png)

**Comment by vranki** [comment]
Looks like we both implemented this.
