### ISSUE TITLE
Crypto store: Stop duplicating devices

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2784]
The android SDK suffers from the same misusage of Realm as the iOS SDK in this [issue](https://github.com/vector-im/riot-ios/issues/2132#issuecomment-447935081) and duplicates devices in their DB table on each storage request.

**Comment by bmarty** [comment]
Done. As seen with @manuroe, contrary to iOS implementation,`DeviceInfoEntity` has primary key, so it's not possible to have duplication in the DB. That said, I've fixed a bug if a device is deleted, to avoid ghost devices in the DB
