### ISSUE TITLE
Consider using Notification.MessagingStyle instead of InboxStyle

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2823]
All is described here: https://developer.android.com/reference/android/app/Notification.MessagingStyle

It will also be useful for https://github.com/vector-im/riot-android/issues/2811

For Riot, maybe use Person to provide Room detail?

**Comment by theLimitBreaker** [comment]
Can I work on this issue ?

**Comment by bmarty** [comment]
Hi @theLimitBreaker ,
Yes, but @BillCarsonFr is currently doing some rework on the notification channels, so maybe wait for is PR to be merged first (at the beginning of next week, I'll ping you)
Benoît

**Comment by theLimitBreaker** [comment]
Thank You !

**Comment by theLimitBreaker** [comment]
Before working directly on Riot-Android. I tested and made demo for messaging style .
Here are screenshots. I just want to confirm that 
 **Do we want the same thing in Riot-Android or is there something else specific to do ?**

#### Collapsed State of Several Room Notifications
<img src= "https://user-images.githubusercontent.com/24780524/50767013-52d16500-12a1-11e9-9fd9-5195d79a2fb2.jpeg" width=360>

#### Expansion of Several Rooms
<img src="https://user-images.githubusercontent.com/24780524/50767065-7c8a8c00-12a1-11e9-8688-f818d187f2e5.jpeg" width = 360>

#### Direct Reply to Room 
<img src="https://user-images.githubusercontent.com/24780524/50767211-fa4e9780-12a1-11e9-9339-44ed78fc49ce.jpeg" width=360>

####  After Direct Reply particular room (Riot-Android)
<img src="https://user-images.githubusercontent.com/24780524/50767124-a93ea380-12a1-11e9-91cd-947d0b2dd6f3.jpeg" width=360>

**Comment by bmarty** [comment]
Yes, @theLimitBreaker, this first shot looks amazing!

**Comment by bmarty** [comment]
FTR https://developer.android.com/training/notify-user/build-notification#messaging-best-practices
