### ISSUE TITLE
Blur Image Preview Take Picture

### ISSUE THREAD

**Issue by theLimitBreaker** [vector-im/riot-android#2831]
### Image Preview While Sending 
<img src = "https://user-images.githubusercontent.com/24780524/50736969-efd0c700-11e9-11e9-99cf-37b601adfffb.jpeg" width=360>

### Image Preview while taking  pic from System App
<img src="https://user-images.githubusercontent.com/24780524/50736990-2c042780-11ea-11e9-92e5-b4883dfd8673.jpeg" width=360>

**Comment by bmarty** [comment]
Yes, thanks for reporting. It look like auto-focus is no enabled (TBH I already noticed that but haven't created the GH issue yet)
