### ISSUE TITLE
Riot Android considers closing parenthesis as part of link

### ISSUE THREAD

**Issue by babolivier** [vector-im/riot-android#2835]
Sometimes I send messages to friends looking like:

> (oh and btw here's a useful link: https://example.com/my-link)

Riot Android tends to include the closing parenthesis in the clickable link, which results in my friends reading my message from there getting 404s.

**Comment by bmarty** [comment]
Hi @babolivier, thanks for reporting

**Comment by OffifialMITX** [comment]
@babolivier You can use markdown formatting to avoid this: `[text](link)`

`(Here is a link for [Riot](riot.im))`
↓↓↓
(Here is a link for [Riot](riot.im))

**Comment by babolivier** [comment]
I know that, but for a mobile use I find it quite annoying if I have to surround all of the links I send via Riot with Markdown (but thanks for your comment).

**Comment by bmarty** [comment]
Fixed by #3010
