### ISSUE TITLE
use the same image preview activity across the app

### ISSUE THREAD

**Issue by dkanada** [vector-im/riot-android#2845]
There are two image preview sections right now, one named MediaPreviewActivity and one that is only an overlay in MediaPickerActivity. The interface for the preview activity is much cleaner and could be utilised in the picker activity to reduce duplicate code. The picker activity is also extremely huge right now so it would shrink that activity slighty, making it a lot more readable. The picker activity could pass the files to the preview activity, and get a pass or fail return value from the preview activity to either take another image or use the current image.

**Comment by bmarty** [comment]
Yes, I agreee with that, thanks for the suggestion.

> an overlay in MediaPickerActivity

I do not like overlay like that, and we should fight against them :).. And there is a really ugly stop button in the middle of the screen for vidéo preview...
