### ISSUE TITLE
Room Version Upgrade: Clicking the link on the tombstone event invites you to choose which app you want to load the link in

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-android#2867]
![image](https://user-images.githubusercontent.com/1922197/51198021-01e9ee00-18eb-11e9-8c15-f42e89b08732.png)

![image](https://user-images.githubusercontent.com/1922197/51198028-06160b80-18eb-11e9-9b09-c8b4599f402e.png)

**Comment by bmarty** [comment]
It's working for me, I'm redirected to the next room preview where I can join the room.

**Comment by ganfra** [comment]
This link is handled as a permalink. Do you have the same process when clicking on a permalink in a message?

**Comment by lampholder** [comment]
No, and if I _do_ allow the link to open in Chrome, copy the URL (of the form https://matrix.to/#/!RoOmId:matrix.org), paste it the composer and send it into the timeline, then click on the link in the timeline, clicking _that_ link works fine.

So it's only clicking the link in the tombstone event that invites me to open it in the application of my choice.
