### ISSUE TITLE
minor improvements to media viewer

### ISSUE THREAD

**Issue by dkanada** [vector-im/riot-android#2868]
I would like to remove the download on long click action because it conflicts with a really nice android gesture (double tap and drag up and down to zoom) and I would also like to add an action to download media to a specific folder.

@bmarty any opinions on the two changes before I start working on them?

**Comment by bmarty** [comment]
Hi @dkanada ,
Yes, I do not like the long click as well (but I don't understand why it is conflicting with double tap and swipe gesture?).
As there is also a menu item to download the media, I assume we can remove the long click event on the media.
Benoît
