### ISSUE TITLE
Message notifications improvement

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#287]
1- The quick reply should be removed but it seems useless by now
-> It would remove the "Open" button which is useless
-> The Quickly Reply seems useless (for example, with a room invitation)

2- The badge should be updated to match the application badge even with the fdroid version

Until we have the final design.

**Comment by erikjohnston** [comment]
We should also display the number of bing messages.

@ara4n

**Comment by bmarty** [comment]
I close this one, replaced by #2823
