### ISSUE TITLE
Reconsider Auto-Reply Feature

### ISSUE THREAD

**Issue by BrainBlasted** [vector-im/riot-android#2875]
Lately I've had to say different variations of "Riot mobile auto-replied to the wrong message" often, because Riot has tried to guess what I'm replying to and failed consistently. Because there's no option to turn it off, I kind of have to deal with it. Unfortunately, it still disrupts the flow of conversations.

In my view, an app should not try to guess things like what someone is replying to, or even how they want to present their replies. What I think could be better:

* Turning auto-reply off by default and let users enable it
* Somehow ask "are you replying to this", either with a dialog or potentially showing Riot's "guess" above your message for context, and allow users to deny it.

**Comment by bmarty** [comment]
I'm not sure to understand what you mean.
You send a reply when a previous message is selected and you send a new message.
When you select a message, you can see that hint change. This UX can be considered quite bad, and will be improve in the future (see #2532).
There is no guess from Riot to find a message you are replying to.

**Comment by BrainBlasted** [comment]
Hmm, I don't noticeably have anything selected when this occurs, but that's probably just my bad eyes 😅 Yeah, the current UX isn't the best - I completely confused what was happening. Closing this one, then.
