### ISSUE TITLE
key backup: new recover method detected

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2926]
@manuroe commented on [Mon Feb 04 2019](https://github.com/vector-im/riot-meta/issues/256)

On mobile, we should display a modal when we detect a new backup version on the HS like web:

![](https://matrix.org/_matrix/media/v1/download/matrix.org/SLHiTcPRXyRiILAeePsoviRu)

**Comment by bmarty** [comment]
Closed by #2974
