### ISSUE TITLE
key backup: Display the restore button only if required

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2927]
@manuroe commented on [Wed Feb 06 2019](https://github.com/vector-im/riot-meta/issues/259)

The restore button is currently always displayed even after a successful recover. This is a disturbing UX.

To fix it we need to:
- [x] update the [spec](https://github.com/uhoreg/matrix-doc/blob/e2e_backup/proposals/1219-storing-megolm-keys-serverside.md) so that matrix clients can detect there is a difference between backed up keys and locally stored keys
- [x] implement this spec change on server
- [ ] implement it on clients

---

@manuroe commented on [Wed Feb 06 2019](https://github.com/vector-im/riot-meta/issues/259#issuecomment-460992275)

Spec proposal: https://github.com/uhoreg/matrix-doc/pull/2.

**Comment by bmarty** [comment]
I Think we can close this due to #2980
