### ISSUE TITLE
There is no visual difference if setting is disabled or not

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2929]
Ex:

![image](https://user-images.githubusercontent.com/3940906/52425615-a7fcd280-2afc-11e9-82a3-c8ca8a6a5fef.png)

Incoming call ringtone is disabled here.

It can also be observed if you disable the notification for the account. All settings under are disabled.

It's a regression, it was working before the Riot reskin.

Bug observed in all four available themes.

**Comment by theLimitBreaker** [comment]
Working on it .

**Comment by theLimitBreaker** [comment]
@bmarty  Making TextColor Selector for each theme solves the issue. I tried for Light Theme it worked

<img src="https://user-images.githubusercontent.com/24780524/52524346-f0b1b880-2cc1-11e9-9bd7-659c8f95428b.jpeg" width=360>

if you agree with this . I would proceed then ?

**Comment by bmarty** [comment]
Yes, seems like you get the solution. Feel free to submit a PR :)
