### ISSUE TITLE
Escape eventIds in CS API requests

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2934]
@manuroe commented on [Fri Feb 08 2019](https://github.com/vector-im/riot-meta/issues/261)

Event IDs in room version 3 can now include hashes in them according to [MSC1659](https://github.com/matrix-org/matrix-doc/pull/1659).

APIs that must be checked:
```
/admin/purge_history/(?P<room_id>[^/]*)(/(?P<event_id>[^/]+))?
/events/(?P<event_id>[^/]*)$
/rooms/(?P<room_id>[^/]*)/report/(?P<event_id>[^/]*)$
/rooms/(?P<room_id>[^/]*)/event/(?P<event_id>[^/]*)$
/rooms/(?P<room_id>[^/]*)/context/(?P<event_id>[^/]*)$
/rooms/(?P<room_id>[^/]*)/redact/(?P<event_id>[^/]*)
/rooms/(?P<room_id>[^/]*)/receipt/(?P<receipt_type>[^/]*)/(?P<event_id>[^/]*)$

**Comment by ganfra** [comment]
By default Path parameters are already escaped by retrofit: 
https://square.github.io/retrofit/2.x/retrofit/index.html?retrofit2/http/Path.html

**Comment by manuroe** [comment]
Because of #2947, could we double-check please?

On iOS, I ended to port the js [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent#Description) to have the expected behavior.

Also, MXPatterns.isEventId() must support v3 event ids that looks like `$pmOSN/DognfuSfhdW/qivXT19lfCWpdSfaPFKDBTJUk+` (iOS commit: https://github.com/matrix-org/matrix-ios-sdk/pull/633/commits/454a3fc1be82f051285a4680334df4070f9ec559?utf8=%E2%9C%93&diff=split&w=1)

**Comment by bmarty** [comment]
Double check done :)
