### ISSUE TITLE
Receiving lots of unwanted notifications

### ISSUE THREAD

**Issue by seekM** [vector-im/riot-android#2935]
I'm using Android (version 6.0.1) and the riot-android client (version 0.8.21 (G-b161), downloaded from the Google Play Store).

I'm constantly getting riot notifications claiming there would be new messages. However, when I open the riot app, there are no new messages. Nothing has been posted, nobody has left or entered the room. I'm in one room only with two other members. 

I tried "Rooms > Mark all as read" and "Settings > Clear cache" but it did not help. "Settings > Troubleshoot Botifcations" says that "basis diagnostics is ok" (green icons only).

It can take between a few seconds to approx. 30 minutes to receive such a notification. Therefore, over time I get a lot of unwanted notifications.

**Comment by BloodyIron** [comment]
Are you still having the issue? If not, consider closing this ticket. If you are, perhaps report your current version and whether the behaviour has changed.

**Comment by seekM** [comment]
I uninstalled the Android client because of this issue. At the moment I'm using the desktop client which works fine for me. If I try the Android client in the future and still experience this issue, I'll post here again.
