### ISSUE TITLE
Key backup: Update wording in setup and sign out flows

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2945]
We must use copy provided in orange comments bubbles:

https://app.zeplin.io/project/5b857c64b1747a2c472290da/screen/5c5ca1fb4bbea33503e3af1a

**Comment by bmarty** [comment]
@BillCarsonFr can we close this one?

**Comment by BillCarsonFr** [comment]
merged
https://github.com/vector-im/riot-android/pull/2957
