### ISSUE TITLE
long icon press shortcut

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-android#2949]
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

The last or favorite rooms should be in the shortcut list. There also may be call actions there.

**Comment by bmarty** [comment]
Duplicate of #2896
Please upvote for it!

**Comment by 532910** [comment]
Sorry!
How should I upvote for it, just thumb up?

**Comment by bmarty** [comment]
Yes :)
