### ISSUE TITLE
Media Viewer: display image in high quality

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2967]
Glide is used to display media, but when pinching to zoom in hi-res pictures, quality is bad.
We should find an option to tell Glide to display images in high quality, to allow high quality zooming.
Also, it seems that Glide use RGB_565 by default, which is not the best quality.

**Comment by progserega** [comment]
Image in chat room:
![screenshot_20190224-114328](https://user-images.githubusercontent.com/1297163/53293997-7f7a1580-382a-11e9-8279-68ae230d9a00.png)

Opened image in riot view:
![screenshot_20190224-114334](https://user-images.githubusercontent.com/1297163/53294002-8bfe6e00-382a-11e9-95c4-cdf21da33963.png)

Max zoom in riot view:
![screenshot_20190224-114339](https://user-images.githubusercontent.com/1297163/53294009-9e78a780-382a-11e9-91d7-5a8d09ee10d4.png)

Save image from riot, open it by external image viewer and see quality of real max zoom:
![screenshot_20190224-114428](https://user-images.githubusercontent.com/1297163/53294013-ab959680-382a-11e9-83a8-d86f3908b948.png)

Media info:
![screenshot_20190224-114528](https://user-images.githubusercontent.com/1297163/53294023-d1bb3680-382a-11e9-906a-94aeca06aa70.png)

**Comment by bmarty** [comment]
thanks @progserega for the example :)
