### ISSUE TITLE
Claims of display names being linkified

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-android#2975]
Source: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$2458-5-3-4T01949.620972|Steela_Oresdotter's_Determined_Bear_Hates_Haven_Bay's_Jittery_Locust:ponies.im?via=matrix.org&via=disroot.org&via=chat.weho.st

See below:
![](https://t2l.io/_matrix/media/v1/thumbnail/matrix.org/LzUolADZiFGCtpjnhaPLARFz?width=800&height=600)

**Comment by BillCarsonFr** [comment]
suggest to do not linkify at all state events? or only linkify user ids?
