### ISSUE TITLE
Build Failed - Unresolved reference: canRestoreKeys

### ISSUE THREAD

**Issue by palmtown** [vector-im/riot-android#2976]
Hello,

The develop branch commit ac807e09e0bf77e9052a40b080d38891ebe486dd generates an error when building "Unresolved reference: canRestoreKeys" 

It seems it is caused by file SignOutViewModel.kt in the code below, canRestoreKeys is not defined in any other file.  

This seems to be a bug.

 fun canRestoreKeys(): Boolean {
        return mxSession
                ?.crypto
                ?.keysBackup
                ?.canRestoreKeys() == true
    }

**Comment by bmarty** [comment]
Hi @palmtown ,

Please follow instruction here: https://github.com/vector-im/riot-android/blob/develop/CONTRIBUTING.md#compilation

Benoit

**Comment by palmtown** [comment]
Hi @bmarty,

Thank you for your response; note that I tried to compile as per URL, however, it did not work as I received error "sed: can't read : No such file or directory" 

What I did was changed directory to the riot-android project files, ran "git clone https://github.com/matrix-org/matrix-android-sdk.git" and then "./compile_with_sdk_project.sh"

It seems the instructions are not very detailed, and I'm not able to figure out the exact procedure.  Would you be kind enough to provide a bit more details on how to run this?  Also, note will I be able to run this command on a Linux PC, or does it have to be run on the windows PC with Android Studio that I am using?

**Comment by palmtown** [comment]
Hello @bmarty,

I run this on my the same PC with Android Studio and it seems although it generates the errors, it may have changed the settings.gradle in main project folder and the build.grade file in the vector folder, however, it will not sync and generates the error below.  I have provided the error and attached the files hereto below.

ERROR: Unable to resolve dependency for ':vector@appDebug/compileClasspath': Could not resolve project :matrix-sdk.
Show Details
Affected Modules: vector

[payload.zip](https://github.com/vector-im/riot-android/files/2885568/payload.zip)

**Comment by palmtown** [comment]
Hello @bmarty,

I was able to resolve this issue, in short, you have to download the https://github.com/matrix-org/matrix-android-sdk outside of the riot-android project folder.  Also, although it generates an error when you run "./compile_with_sdk_project.sh" it still seems to modify the files.

Thereafter, I performed a sync and runt he project and all seems to work fine.  However, my question is, am I now able to re-comment the code that ./compile_with_sdk_project.sh uncommented?  Also, am I able to remove the matrix-android-sdk?  Or should I leave everything as is?
