### ISSUE TITLE
Reskin: Palette updates

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#2987]
@manuroe commented on [Thu Feb 21 2019](https://github.com/vector-im/riot-meta/issues/266)

Minor updates:
- [x] links in blue (new links color in  https://app.zeplin.io/project/5c122fa790c5b4241ffa6be7/screen/5c619592daff2f1241d82e75)
- [x] use notices colors for badges background in section headers (the 37 in https://matrix.org/_matrix/media/v1/download/matrix.org/MkkbPIYjaGAbtxTUuUbvUMiy)

**Comment by bmarty** [comment]
Done
