### ISSUE TITLE
Messages sent through JS API received in desktop but not android

### ISSUE THREAD

**Issue by waterdrop01** [vector-im/riot-android#2989]
Hello,

I have two accounts, one is my personal account, the other one is used as a bot account to programmatically send messages (notifications).

Problem: messages sent by bot account to the room ID thanks to JS API are not displayed on the Android client. But notifications are well received (in the Android top bar) but they don't display in the Riot app chatroom.

Also, they a correctly displayed on the desktop client (of both accounts).

I tried creating another room (so new room id) but same problem on the Android side.

Any idea?

Thank you!

**Comment by bmarty** [comment]
Hi @waterdrop01 ,
Can you paste such an Event content here please?
Thanks

**Comment by waterdrop01** [comment]
I'm using this code to fire the message:
```js
const content = { body: '',
       format: 'org.matrix.custom.html',
       msgtype: 'm.text',
       formatted_body: '\n  <b>XXXX</b> XXXX <b>XXXXX</b> :<br>\n  <li>\n  <ul>\n  <u>message</u> : xxxxxx\n  </ul>\n  <ul>\n  <u>action to take</u> : xxxxxx.\n  </li>\n  </ul>\n  ' }

const res = await matrix.sendEvent('!nrTbFyfXjxcDwtaNsi:matrix.org', 'm.room.message', content, '');
```
With SDK printing this in the server console:
```
sendEvent of type m.room.message in !nrTbFyfXjxcDwtaNsi:matrix.org with txnId m1551197262363.1
Event sent to !nrTbFyfXjxcDwtaNsi:matrix.org with event id $1551197262106900GswUk:matrix.org
```

From the desktop client, clicking on the `three dots > view source` shows this:
```json
{
  "content": {
    "body": "",
    "format": "org.matrix.custom.html",
    "formatted_body": "<hr><p>\n  <b>XXXX</b> XXXX <b>XXXXX</b> :<br>\n  <li>\n  <ul>\n  <u>message</u> : xxxxxx\n  </ul>\n  <ul>\n  <u>action to take</u> : xxxxxx.\n  </li>\n  </ul>\n  </p>",
    "msgtype": "m.text"
  },
  "event_id": "$1551197262106900GswUk:matrix.org",
  "origin_server_ts": 1551197262459,
  "sender": "@xxxxbot:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 788
  },
  "room_id": "!nrTbFyfXjxcDwtaNsi:matrix.org"
}
```
On the xxxxbot user browser client, I can also see the above message. **But** on my Riot Android App, **nothing appears...**

Thank you very much @bmarty for your help on this!
