### ISSUE TITLE
the icon is removed after the last update

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-android#2994]
Update to 0.8.23 (G-b164) from the previous version on the stable or beta channel removes icon from desktop.

**Comment by 532910** [comment]
Affected systems: LineageOS 15.1 (8.1.0), LineageOS 14.1 (7.1.2)

**Comment by bmarty** [comment]
Yes, sorry about that.

This is a side effect of https://github.com/vector-im/riot-android/commit/0f471b436b029dfd3ed33884d52550d0f0b1149d

Please add again the Riot icon on your Homescreen.

**Comment by 532910** [comment]
Same issue, again, with the 0.8.26 (G-b169)
