### ISSUE TITLE
develop and master branch debugging, compile error

### ISSUE THREAD

**Issue by fuxianwei** [vector-im/riot-android#2997]
run `./gradlew assembleDebug` and `./gradlew assembleRelease` error
please help me

Software Environment：
mac os 10.13.5
android studio 3.3
jdk 1.8

`* What went wrong:
Execution failed for task ':vector:processAppfdroidDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/ff/Desktop/work/github/riot-android/vector/src/appfdroid/debug/google-services.json
  /Users/ff/Desktop/work/github/riot-android/vector/src/debug/appfdroid/google-services.json
  /Users/ff/Desktop/work/github/riot-android/vector/src/appfdroid/google-services.json
  /Users/ff/Desktop/work/github/riot-android/vector/src/debug/google-services.json
  /Users/ff/Desktop/work/github/riot-android/vector/src/appfdroidDebug/google-services.json
  /Users/ff/Desktop/work/github/riot-android/vector/google-services.json
`

**Comment by bmarty** [comment]
You have to specify a product flavor.
To build PlayStore version, please run 
> ./gradlew assembleAppDebug

To build F-Droid version:

> ./gradlew assembleAppfdroidDebug
