### ISSUE TITLE
Handle well-known data in the login response

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3002]
@manuroe commented on [Tue Feb 26 2019](https://github.com/vector-im/riot-meta/issues/271)

As described in [MSC1730: Mechanism for redirecting to an alternative server during login](https://github.com/matrix-org/matrix-doc/pull/1730).

JS PR: https://github.com/matrix-org/matrix-react-sdk/pull/2384.

**Comment by bmarty** [comment]
Done
