### ISSUE TITLE
I can't start Riot.im after updating it

### ISSUE THREAD

**Issue by peter099** [vector-im/riot-android#3003]
I updated Riot.im and now if i try to launch it i see a message 'permission denied'.

**Comment by bmarty** [comment]
Strange... Are you using GPlay version? Can you provide some log?

**Comment by peter099** [comment]
Yes, i downloaded riot.im from google play. By the way, my device is using android 4.4.2.
How to provide logs?

**Comment by peter099** [comment]
I found the issue. For some reason the icon from the previous version was not updated and trying to start riot.im from it gave me this permission denied message.

**Comment by bmarty** [comment]
Ok I assume it's another side effect of change of launcher Activity (see ref in #2994)
