### ISSUE TITLE
Open link in new tab

### ISSUE THREAD

**Issue by natrius** [vector-im/riot-android#3008]
On android when opening 2 links they get opened in the same tab, overwriting the other content. 
In every other app and on riot-browser the link get opened in a new tab and this should be default.

It is really annoying espacially in rooms where a lot of information backed with link is going on and i want to read the links itself later. 

**Reproduce**

Open first link in first tab, copy URL, open new tab, paste link and open site. Status: 2 tabs with the same content. Second: Open second link and it will get opened in the first tab.

**Comment by natrius** [comment]
@MatMaul 
How and where should i do that when receiving a link in the android app?

**Comment by MatMaul** [comment]
Sorry I am talking to the devs here 😊 I'll have a look if I can find the code and do a PR.

**Comment by bmarty** [comment]
Hi @natrius @MatMaul ,

This is a duplicate of #381 which contain link to the code

Benoît

**Comment by natrius** [comment]
Oh, whopps, searched but could not find anything that was fitting. Thanks :)

**Comment by bmarty** [comment]
No problem :)
