### ISSUE TITLE
Cryptography is disabled when logging in

### ISSUE THREAD

**Issue by Polsaker** [vector-im/riot-android#3018]
I have a homeserver which supports both SSO and password authentication. When logging in via either of the two methods I get a prompt reading "Riot now supports end-to-end encryption but you need to log in again to enable it", if I click "OK" I'm prompted to log in again, and after doing so I get the same message telling me to log in again...

If I tap on "Later" and go to settings to enable encryption the app crashes (the crash log is similar to the one being addressed by #3012)

**Comment by bmarty** [comment]
Hi @Polsaker ,

Yes, I've seen this behavior also, since I'm working on #3006.

We will improve this, thanks for reporting. Action taken for this issue:

- [ ] Change wording of dialog button. "Ok" should not lead to a Sign Out

Benoît
