### ISSUE TITLE
Closing bracket breaks links on Android, not on Desktop

### ISSUE THREAD

**Issue by matrixuser123** [vector-im/riot-android#3020]
I’ve found a bug in Riot for Android 0.8.23 on Android 7 and Android 9: If I add a link in brackets like (help for Riot: https://about.riot.im/help), the link is usable on Riot for Desktop (1.0.1-1). The Android version of the clickable link includes the closing bracket so the link doesn't work anymore.

**Comment by bmarty** [comment]
Hi @matrixuser123,
Thanks for reporting.
@BillCarsonFr maybe check this in the context of #3010 ?
Thanks
Benoit

**Comment by BillCarsonFr** [comment]
In fact the trailing round bracket is considered as part of the link when it's locating at the end of the current message (e.g https://about.riot.im/help)$ , but not if there is text after).

Notice that round brackets are valid and the link could totally be [https://about.riot.im/help)] :/
