### ISSUE TITLE
Splash screen flashes white for dark theme

### ISSUE THREAD

**Issue by tleydxdy** [vector-im/riot-android#3021]
Might be better if the splash screen is dark, so it won't cause sudden flashes.

**Comment by bmarty** [comment]
Yes, but default theme of Riot is light so it has been decided that the Splash is light as well, before the theme can be applied. There is no solution AFAIK.
For ref. Youtube App has the same issue.

**Comment by tleydxdy** [comment]
However, light -> dark for half a second -> light, is way less intrusive than dark -> light for half a second -> dark.
