### ISSUE TITLE
Support SSO in mobile apps

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3025]
@manuroe commented on [Mon Mar 04 2019](https://github.com/vector-im/riot-meta/issues/276)

If an homeserver requires SSO, mobile apps should allow it nicely like web.

Current display on Riot-iOS:
![simulator screen shot - iphone 6s plus - 2019-03-01 at 08 51 29](https://user-images.githubusercontent.com/8418515/53743809-e4bdae80-3e9b-11e9-9ebe-5f105d6141bb.png)

Riot-Web:
<img width="591" alt="screenshot 2019-03-01 at 07 40 32" src="https://user-images.githubusercontent.com/8418515/53743857-fbfc9c00-3e9b-11e9-8efc-62d884c469b2.png">

**Comment by bmarty** [comment]
FTR, this is how it looks like once implemented on Riot-Android:

![sso](https://user-images.githubusercontent.com/3940906/53884787-a56a9b80-401c-11e9-94fc-62e012132172.png)
