### ISSUE TITLE
Accessibility - Jitsi is red text on a green background

### ISSUE THREAD

**Issue by edent** [vector-im/riot-android#3027]
Hard to read for me. Impossible to read for colour-blind users.

![screenshot_20190305-101300__01](https://user-images.githubusercontent.com/837136/53809749-425e0380-3f4d-11e9-9c81-f1706641fc6a.jpg)

**Comment by bmarty** [comment]
Hi @edent ,
thanks for reporting, it's fixed in last release 0.8.24 of Riot
Benoît
