### ISSUE TITLE
Unread badge stuck on homescreen

### ISSUE THREAD

**Issue by BobVul** [vector-im/riot-android#3029]
I believe this is related to a room invite that was cancelled before I could decline it. Followed by the room admin deciding to delete the cancellation event (?!?!?!).

On Riot web, the invitation stayed visible even after being declined. Clearing cache and reloading (independently for every machine!) seems to have removed it.

On Riot Android, declining the invitation removed all trace of it from the main screen. However, I now have a "1" badge stuck on the app on the homescreen/app drawer. "Mark all as read" does not seem do anything.

Running the most recent version on Play Store, 0.8.23 (G-b164). Connected to a custom homeserver originally running 0.99.0 but now updated to 0.99.2. Invite came from a remote homeserver running 0.99.1rc1.

**Comment by bmarty** [comment]
Do you still observe the issue on Riot 0.8.26?

**Comment by BobVul** [comment]
Hm. It does seem to have gone away at some point but I can't say what exactly fixed it, update or otherwise.

**Comment by bmarty** [comment]
Ok, thanks, let's assume that it's fixed thanks to the work we have done on notifications
