### ISSUE TITLE
E2E: SAS Verification (olm)

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3045]
@lampholder commented on [Tue Dec 11 2018](https://github.com/vector-im/riot-web/issues/7829)

SAS module (or any better name)
- create/delete session
- generate SAS code (as an array of numbers)
- hash data

---

@jryans commented on [Wed Jan 30 2019](https://github.com/vector-im/riot-web/issues/7829#issuecomment-458993331)

Fixed by https://git.matrix.org/git/olm/commit/?id=94f664e7256215f33639dbbad6aaf87ada082a9f.

**Comment by BillCarsonFr** [comment]
merged to olm
