### ISSUE TITLE
URLs sent in bot messages are no longer clickable

### ISSUE THREAD

**Issue by non-Jedi** [vector-im/riot-android#3048]
In latest version on Google play (0.8.24 (G-ba66)), Any URL in an `m.room.message` with `"msgtype": "m.notice"` is no longer clickable. This means that most matrix bots aren't usable currently from Riot Android.

In image below, top message is a normal `m.text`, and bottom is an `m.notice`.

![riot-android-m-notice](https://user-images.githubusercontent.com/17915621/54129078-e16a7b80-43e3-11e9-9ebf-5b1c2ea3ef55.png)

**Comment by bmarty** [comment]
Hi @non-Jedi ,
Thanks for reporting.
Refer to #3043 
Benoît
