### ISSUE TITLE
Widgets: Attempt to re-register for a scalar token if ours is invalid

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3051]
@manuroe commented on [Tue Mar 12 2019](https://github.com/vector-im/riot-meta/issues/279)

Riot mobile apps should validate `scalar_token` before using it as riot-web does with https://github.com/matrix-org/matrix-react-sdk/pull/1668.

**Comment by bmarty** [comment]
Done, by intercepting 403 error from the WebView
