### ISSUE TITLE
Silent LED notification not working

### ISSUE THREAD

**Issue by ASoTNetworks** [vector-im/riot-android#3059]
Since version 0.8.24 (G-b166) on Android 9 I am not getting any silent LED notifications. 

In the Advanced Notifications Settings -> Configure Silent Notifications -> Advanced it is missing the Blink light option where as the noisy setting have it.

I wonder if it is related to https://github.com/vector-im/riot-android/pull/2813

**Comment by bmarty** [comment]
You have to change the style of the notification to see option for led/blink/sound/etc.

Note that it may depends on your device model.
