### ISSUE TITLE
Always have notification "initializing service"

### ISSUE THREAD

**Issue by bajizs** [vector-im/riot-android#3065]
Riot Version: 0.8.25 (G-b167)
Android version 9

From last update I always see notification from RIOT "initializing service". I can't remove this notification, only with killing RIOT, and restarting it, but after some time the message is visible again.

**Comment by abunasar** [comment]
Same here, any workaround?

**Comment by bmarty** [comment]
You can kill the app to make the notification to disappear.
Also the issue is fixed and will be released soon

**Comment by matrixes** [comment]
@bmarty There was an update pushed to GPlay on the 25th of March, and this issue wasn't a part of that update.
How come?

**Comment by bmarty** [comment]
I'm working on it :)

**Comment by bmarty** [comment]
Removed in Riot 0.8.27
