### ISSUE TITLE
Network Error / Error "Null" upon sending a message

### ISSUE THREAD

**Issue by thckmnn** [vector-im/riot-android#3083]
Hello guys,

we use a Matrix-Server without federation, so just locally for ourselves. Everything on iOS / Windows works, but when Android-Clients try to send a message, it shows Network Error / Error "null". We have tried it via WiFi and via mobile network. It happens on every Android Phone. I will send a Bug Report in shortly.

Edit: Bug report sent in.

Any ideas?

**Comment by lixmal** [comment]
I could observe the same behaviour today, but only when I tried to mention someone. The input looked like this:
`displayname: xxxxxx`

**Comment by thckmnn** [comment]
This topic can be closed. It was a firewalling mistake on my part.
