### ISSUE TITLE
after update to 0.8.26 on Samsung S9 error in the presentation of the telefon/video plug in

### ISSUE THREAD

**Issue by horstvogel** [vector-im/riot-android#3085]
after update to 0.8.26 (google version) on Samsung S9 Android 9 error in the presentation of the telefon/video plug in. 
You have to scroll to see the video call. The same with the upload button

0.8.25
![image](https://user-images.githubusercontent.com/25108737/55273739-7d92ee80-52cf-11e9-9778-f8abb573b57d.png)

After the update to 0.8.26
![image](https://user-images.githubusercontent.com/25108737/55273746-91d6eb80-52cf-11e9-814c-136d0bd1406f.png)

![image](https://user-images.githubusercontent.com/25108737/55273748-98fdf980-52cf-11e9-9a8f-6fd23b5ab038.png)

**Comment by bmarty** [comment]
FTR Works fine on S9+ with language set to German.

**Comment by bmarty** [comment]
I've fixed an issue in the dialog layout for RTL language, it could maybe also fixes this issue.
Please let me know if it's ok in Riot 0.9.01 (not yet released)

**Comment by horstvogel** [comment]
@ bmarty: Yes, 0.9.01 solved the problem!!! Thanks!!!
