### ISSUE TITLE
User can not send photo if application is turkish

### ISSUE THREAD

**Issue by murat-aksoy** [vector-im/riot-android#3123]
Hi,
I set the language to Turkish. I try to take and send a photo but it fails.
Steps to produce :
1 - Set the language as Turkish.
2 - Go to a room
3 - Select the option Video Kaydet veya fotoğraf çek
4 - take a photo
5 - on the preview screen press Tamam which means OK
6 - you will get an error instead of showing the Send As dialog.
![riot-error](https://user-images.githubusercontent.com/48415714/56281967-a3fdba00-6116-11e9-9468-534b38605c16.jpg)

If application is english or french, there wont be problem. I checked the image path and I can see the taken image in the path.

**Comment by bmarty** [comment]
Sorry to hear that, thanks for reporting.

**Comment by murat-aksoy** [comment]
Can someone which file should I debug? I want to debug and fix the issue. This feature is very important for us.

**Comment by bmarty** [comment]
Hi,
Let I'm having a quick look at this issue

**Comment by bmarty** [comment]
Ok, I figured it out.
Taken photo is store in file "VectorImage_<date>.jpg"
And the I becomes 'ı' (i without a point, specific to Turkish language) when toLowerCase() is called, which make the regexp fails to get the file extension...

**Comment by murat-aksoy** [comment]
Hi,
Thank you for your effort. Could you give me the file name and line so I can take a look at it and try to fix.

**Comment by murat-aksoy** [comment]
You've already fixed it. Thank you very much. I tested it and it works like a charm :+1:

**Comment by bmarty** [comment]
Thanks for the test.
The fix will be available in the next release.
Benoit
