### ISSUE TITLE
Very confusing mistake in Arabic translation 

### ISSUE THREAD

**Issue by invertor** [vector-im/riot-android#3129]
In the Arabic translation (which I tested for few minutes) the user would see the sentence which means "voice call" next to the symbol of the camera, while the sentence which means "video call" next to the phone symbol.
The true function is for sure the one of the symbol i.e to make a video call you have to click on the camera and the phone for a voice call

**Comment by bmarty** [comment]
Hi @invertor ,
Thanks for reporting, we will check this
Benoit

**Comment by amiraliakbari** [comment]
Just as a related reminder, the Weblate translation site (and readme badge) is not working.

**Comment by bmarty** [comment]
Hi @invertor @amiraliakbari ,

Is it ok like that?

<img width="421" alt="image" src="https://user-images.githubusercontent.com/3940906/56968331-467c5b00-6b63-11e9-999f-449a0b7fa482.png">

Once confirmed I will merge the fix
Thanks
Benoit

**Comment by invertor** [comment]
It's fine like this. 
Thanks
