### ISSUE TITLE
im.vector.app in GPlay doesn't support push notifications

### ISSUE THREAD

**Issue by di72nn** [vector-im/riot-android#3134]
It seems that currently published GPlay version doesn't support push notifications: there are background sync settings present and the app does not register for FCM (microG allows to see/control it).

**Comment by Skirmisher** [comment]
I'm also running microG, but im.vector.app (version 0.9.00) appears to have FCM push functionality. All of the tests under "Troubleshoot Notifications" in the app settings pass, and microG indicates that the app is registered and receiving messages. However, notifications never appear for me, while they worked correctly with im.vector.alpha previously. I am unsure if this is a related bug or some other issue; unfortunately, it's almost impossible to tell.

**Comment by di72nn** [comment]
The "Troubleshoot Notifications" screen reports "SERVICE_NOT_AVAILABLE":
![Screenshot_20190426-144558_Riot im](https://user-images.githubusercontent.com/1114779/56803015-94772300-6832-11e9-8060-5cd720b3535a.png)

`im.vector.alpha` 0.8.29 reports no such errors and works fine on the same device.
I'm running LineageOS 15.1 with microG.
Exactly the same problem is occuring on a second device running the same ROM.

I've also sent an in-app bug report.

**Comment by Skirmisher** [comment]
My issue with notifications not appearing seems to have been resolved by either
- disabling battery optimizations for the app (which it used to prompt for but no longer does)
- updating LineageOS

So my issue, naturally, is unrelated, because Android.

**Comment by di72nn** [comment]
Turns out microG has some issues with displaying GCM registration confirmations for new apps. I temporary disabled "Confirm new apps" in "microG Settings - Google Cloud Messaging - Advanced". After running troubleshooting Riot appeared in the list of apps registered for GCM.

Sorry for bothering.
