### ISSUE TITLE
no notifications

### ISSUE THREAD

**Issue by takiainen** [vector-im/riot-android#3138]
After the hacking incident Riot doesn't show notifications anymore. I'm running latest version from F-droid on Oneplus One, Lineage Pie ROM. 

-I have enabled all "noisy" notifications in mobile and desktop
- I have disabled battery optimizations
- Riot's built in notification "helper" says everything is ok

As a side note, a friend of my running iOS complains daily, that she hasn't received notifications for a year.

As a another side note: video / sound calls hardly ever come through. And even when they do show up, they fail to connect with caller after pressing "answer". This issues has been present since the beginning.

**Comment by vsatmydynipnet** [comment]
See here: https://github.com/vector-im/riot-android/issues/3122

**Comment by ekim501** [comment]
I'm having the same issue - I can see the icon in the notification bar - but I don't get any popups or sounds.

**Comment by anmol26s** [comment]
same issue

**Comment by UralZima** [comment]
Hi. I created a new issue, because mine is very strange and more detailed description, and differs from this, it may help to resolve this issue. Please take a look https://github.com/vector-im/riot-android/issues/3162

**Comment by echto** [comment]
Might be the latest version of synaspe and not riot-andriod.

**Comment by zwieberl** [comment]
See also #2800

**Comment by BloodyIron** [comment]
We're now at the point where the majority of people that I know that use riot are never getting notifications of messages sent. Somehow the notification system has gotten significantly worse in the last year. This is specifically isolated to android, and even I don't get alerts at times.

What exactly is going on here to address notification issues on android? Because it's useless to have a chat app that you never get alerted of chat.

**Comment by xuhdev** [comment]
You can try to disable battery optimization for the app. In settings, search for "battery optimization", and disable optimization for this app.

**Comment by takiainen** [comment]
This fissue got fixed with updates.

**Comment by xuhdev** [comment]
@takiainen What do you mean? I'm having this issue after the renaming...
