### ISSUE TITLE
Improve verification

### ISSUE THREAD

**Issue by natrius** [vector-im/riot-android#3140]
I'm using riot for a while now on Windows, Linux and Android with some friends. One of the biggest complaints is about the verification system itself. Because if i add something a new device everybody has to verify this device on every own device (or installation). 
Plus, if a new one joins a encrypted room, he has to click a really annoying amount of times to verify all devices, espaically if someone has Riot installed on various devices. (in my example 5 [maybe 6] times. Have fun with that... )

Suggestions for improvement:

 - If i verify a new device from someone on my computer, there should be a checkmark if i want to verify it on every device (or set the default behavior in settings maybe?)
 - Make it possible to verify every device from someone at once while leaving the possibility to verify manually afterwards.

With the first suggestion it is easier when a new device is added and the second one is still protection about mass surveilance while leaving the possibility to check every device for journalists or people who need protection. 

I searched for a similiar issue but could not find one.

**Comment by natrius** [comment]
Another idea: 

I verify a person with the possibility to check every device. When a new device is added, leave it to the user who is adding the new device, not the persons who are communication. 
So, my partner adds ME as secure and to trust all my devices at once (default) but with the ability to check every device on its own (advanced). When I want to add another device, I should be the one who makes verification. With desktop and add an android device -> Show a QR to scan with the cellphone.  Done. Add a new Desktop device -> Emoji-Verification. And the opposite site gets a note that a new device was added (or something like that). So, the main-load for doing the stuff is on my side, not on the one i am chatting with. But he still has the options to check every device individually.

**Comment by BillCarsonFr** [comment]
Hello, I think you should take a look at 'cross signing':
https://github.com/uhoreg/matrix-doc/blob/cross-signing2/proposals/1756-cross-signing.md
https://github.com/matrix-org/matrix-doc/pull/1756
