### ISSUE TITLE
Background service stops as soon as I close the app

### ISSUE THREAD

**Issue by OffifialMITX** [vector-im/riot-android#3146]
It consistently happens that since 0.8.26 F-Droid, Riot consistently stops working as soon as I close the window (by sliding it away from the overview).

I checked everything by now - the selftest shows no problems, notifications are enabled, I gave every possible permission, but it still happens.

I have Android 7.1.1

_Sent from my Moto E (4) Plus using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by anmol26s** [comment]
same issue

**Comment by BillCarsonFr** [comment]
Hi,
Yes the service is not running anymore permanently in background. When the app enters background, if there is no FCM, the service is stopped and scheduled to start in x minutes (configurable) using the WorkManager API in order to sync with the server.

**Comment by OffifialMITX** [comment]
Well it doesn't start again in my case at all. I can go on for hours without getting notifications, even thogh my setting says 6 minutes.

On May 6, 2019 2:39:21 PM UTC, Valere <notifications@github.com> wrote:
>Hi,
>Yes the service is not running anymore permanently in background. When
>the app enters background, if there is no FCM, the service is stopped
>and scheduled to start in x minutes (configurable) using the
>WorkManager API in order to sync with the server.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/vector-im/riot-android/issues/3146#issuecomment-489645211

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BillCarsonFr** [comment]
When it starts you should see a notification stating that it is syncing with the server. If not please submit a bug report (rage shake) so i can look at the logs
