### ISSUE TITLE
Markdown blockquotes are not rendered correctly

### ISSUE THREAD

**Issue by kythyria** [vector-im/riot-android#315]
Vector-android inserts additional vertical whitespace when paragraph breaks happen near or in blockquotes, which Github and vector-web agree should not be there:

Correct:
![Correct (vector-web)](https://cloud.githubusercontent.com/assets/2553724/16902945/f48deb74-4c66-11e6-818c-966e6626d139.png)

Wrong:
![Wrong (vector-android)](https://cloud.githubusercontent.com/assets/2553724/16902949/2f5593ba-4c67-11e6-81f7-3d7fe86fc311.png)

**Comment by ylecollen** [comment]
The android client uses android.text.html to render the markdowns.
It seems that Android has its own way to display them.
I assume we will need to implement our own rendering class.

**Comment by bmarty** [comment]
It's done now
