### ISSUE TITLE
Room upgrades do not work on federated servers.

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#3186]
Sounds like the same bug as https://github.com/vector-im/riot-ios/issues/2486 exists on Android.  This is pretty terrible.

**Comment by EmJayArr** [comment]
+1. Clicking on the "conversation continues here" link when the room was upgraded resulted in a "it is not currently possible to re-join an empty room" error. Worked fine from the web client, and then I was able to use it on Android.

**Comment by mtauz** [comment]
+1 same here, riot android 0.9.1 was unable to join a new V4 Room. After search in the room directory I could in the same room in upgraded version.

**Comment by bmarty** [comment]
Fixed in #3215

**Comment by bmarty** [comment]
(Riot 0.9.2)
