### ISSUE TITLE
Listen for events on boot

### ISSUE THREAD

**Issue by sim6** [vector-im/riot-android#319]
Firstly, thanks for your work.

Please, could you add an option to start to listen events on boot?

Thank you.

**Comment by ylecollen** [comment]
Which version ? The google play or the F-droid one ?
It should work out of the box for the GCM one.

**Comment by sim6** [comment]
I'm using the f-droid.org build on FairPhone2 with OpenSourceOS and doesn't start at boot.

**Comment by sim6** [comment]
It doesn't listen for events on boot using the f-droid build with  Samsung Galaxy Xcover 2 GT-S7710

**Comment by sim6** [comment]
See also #838

**Comment by sim6** [comment]
Done via https://github.com/vector-im/riot-android/commit/2ea7205195de12899572766d5d401294e0598fc1
