### ISSUE TITLE
Request: Update F-Droid version

### ISSUE THREAD

**Issue by derritter88** [vector-im/riot-android#3190]
Hi there,

is it possible to get the current version of Riot.im Android messenger also via F-Droid?
Currently the up-to-date version (0.9.1) is only available via Google Play Store.
The F-Droid version is still on version 0.8.28a.

Thanks, Mathias

**Comment by mvgorcum** [comment]
You can track the issue [here](https://gitlab.com/fdroid/fdroiddata/issues/1601). Generally the F-droid builds are done by the F-droid volunteers. Currently this hangs on a compilation issue with jitsi, see [here](https://github.com/jitsi/jitsi-meet/issues/4106#issuecomment-493508737).

If anyone has time to dig in to the issue, that would be great.

**Comment by paskalito** [comment]
This seems to have happened! :D

(unfortunately push still doesn't work)

**Comment by mvgorcum** [comment]
Note that push can't work with the f-droid version, because that uses FCM which is proprietary and thus can't be included in f-droid.

The f-droid version regularly checks the server to see if there are new messages. If you don't get notifications it's possible that android killed riot-android.
