### ISSUE TITLE
Implement Message Editing and Reactions

### ISSUE THREAD

**Issue by Ryonez** [vector-im/riot-android#3218]
The latest release of riot-web [here (v 1.3.0)](https://github.com/vector-im/riot-web/releases/tag/v1.3.0) has enabled message editing and reactions.

This is great, I've been using the config to enable them on my website and desktop client, and was looking forward to it being released across all platforms.
After updating my clients I came here to check and found no updates that added the two new features.

I was under the impression that one of the reasons labs are used is to hold back features that weren't ready for all platforms, so being slightly confused I checked riot-ios and yup, message editing and reactions added.

Coming back I found that I'd missed that the readme.md had been updated some time ago to point out most of the development is now on something called [RiotX](https://github.com/vector-im/riotX-android). And it seems this is the android client that got message editing and reactions.

So now I'm here to ask the you implement them into your default official client. I'm surprised it wasn't in tandem with the other clients, or even before RiotX especially given how much is missing from it. I can understand the desire to make something better, but until you have at least feature parity with the old app, please release new features on both or at the least on the official default android app and not just the new one that's missing basic features.

**Comment by Ryonez** [comment]
Been 4 weeks, any update? This is a pretty major feature missing.

**Comment by ara4n** [comment]
We don't have the bandwidth to work on both Riot Legacy and RiotX on Android.  Instead, RiotX is progressing at top speed to replace Riot Legacy asap; in most respects it's already way better and should be usable day to day as a replacement, leaving legacy for fallback only when you need something specific that only legacy can do.

So, i'm afraid this isn't going to happen (unless someone off the core team felt the urge to go and contribute it, but even then we'd be unlikely to merge it as the last thing we need is to handle support & maintenance for yet more features on Riot legacy).

**Comment by Ryonez** [comment]
As mentioned before, I understand the desire to switch completely to working on your new app. But being frank, it's not ready for casual use. According to your play store page for it, it's missing the following:

* Account creation
* Room settings (list room members, etc.)
* Calls
* Widgets

Not on the page, but missing:

* Sticker support

With support for account creation missing already, it's not ready for new users. With Room settings missing admins are required to have the "Legacy" app when they are out and about( at least if they have to make changes, so maybe not required as such).
With Stickers missing, normal users in a chat have to use "Legacy" to see what it was.

RiotX is *useable*, it's nice and smooth, but it's not there yet, there's to much missing. And while you consider the "Legacy" app to be legacy, it's still the official app, and is only missing message editing as far as I know at the moment. While adding new features to it will mean RiotX will take a little longer, it does mean there is at least one feature complete client for your users to use. And I think that's pretty important.

Once RiotX has feature parity with your "Legacy" app, go ham, drop this client completely and shift to it. It's just right now, you seem to be trying to start the process when it's not ready for it.

Note: Legacy is in quotes simply because I don't view it as legacy yet. It doesn't have a replacement.
