### ISSUE TITLE
Prompt to accept identity server policies before inviting them to a room

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3227]
Prompt for accepting IS terms before inviting a user by email address (if you haven't already agreed to that IS's policies)

The final conclusion is to display the generic Terms modal flow when you access an IS for the first time.
UX: https://zpl.io/brMdWo3

Riot-web issue with all the discussion: https://github.com/vector-im/riot-web/issues/10093

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2602)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riotX-android](https://github.com/vector-im/riotX-android/issues/434)

**Comment by bmarty** [comment]
Implementation is done
