### ISSUE TITLE
Identity server v2 API authentication

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3228]
From riot-web created by [jryans](https://github.com/jryans): vector-im/riot-web#10408  

[MSC2140](https://github.com/matrix-org/matrix-doc/pull/2140) defines a new v2 API for Identity Servers and uses OpenID authentication as defined in [MSC1961](https://github.com/matrix-org/matrix-doc/pull/1961).

We need to add support for the new API version and authentication requirement in all places that IS APIs are used.

**Comment by jryans** [comment]
An additional detail here (discussed in https://github.com/vector-im/riot-web/issues/10525#issuecomment-520493366) is the client should send `is_token` to the HS for any requests proxied through it to the IS.

**Comment by jryans** [comment]
This was later changed to `id_access_token`.

**Comment by BillCarsonFr** [comment]
Closed in favor of #3295
