### ISSUE TITLE
Ability to disconnect from the identity server by pressing buttons in user settings

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3253]
The riot-web issue has a screenshot:
https://github.com/vector-im/riot-web/issues/10425

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2649)

**Comment by jryans** [comment]
Ideally this will also warn when 3PIDs are still bound as in https://github.com/vector-im/riot-web/issues/10550.

**Comment by jryans** [comment]
Riot Web has tweaked the bound 3PID warning text as part of https://github.com/vector-im/riot-web/issues/10750:

<img width="779" alt="2019-09-06 at 15 05" src="https://user-images.githubusercontent.com/279572/64434240-018ba680-d0b8-11e9-9b2d-08efa8285791.png">
