### ISSUE TITLE
Allow email registration when no IS

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3260]
Cloned from https://github.com/vector-im/riot-web/issues/10571.

Current thinking is that this should use unauthed capabilities as proposed in https://github.com/vector-im/riot-web/issues/10571#issuecomment-521938437 (MSC coming) to detect whether the HS handles emails itself.

**Comment by bmarty** [comment]
Done: 53b98a9649e49c25a96bc02fdb8fc30c42b1e3a8
