### ISSUE TITLE
Handle terms agreement in the Discovery section of settings

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3263]
Cloned from https://github.com/vector-im/riot-web/issues/10522.

It's possible that the Discovery section of settings is the first place the user interacts with their identity server, and therefore we need to show some kind of state when terms haven't been agreed yet, allow for agreeing the terms, etc.

For Riot Web, the designs are: https://zpl.io/brMdWo3

<img width="969" alt="Screenshot 2019-08-13 at 15 15 28" src="https://user-images.githubusercontent.com/4626865/62981110-44ba6880-bddd-11e9-95cf-fb4b79927946.png">

Marking needs-design for mobile.

**Comment by BillCarsonFr** [comment]
c0c0130ed9b7369461b91e778611c648b5afeccd
