### ISSUE TITLE
We should make it clear in the UI that device names are publicly readable

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3265]
Cloned from https://github.com/vector-im/riot-web/issues/10216

**Comment by bmarty** [comment]
Done:
![image](https://user-images.githubusercontent.com/3940906/63531720-6a482000-c509-11e9-9947-53d2d5e45447.png)

![image](https://user-images.githubusercontent.com/3940906/63531739-746a1e80-c509-11e9-9516-69b76b785ba2.png)

**Comment by manuroe** [comment]
@bmarty, do not forget to update the modal "Device Information":

 
<img width="396" alt="Screenshot 2019-08-26 at 17 20 30" src="https://user-images.githubusercontent.com/8418515/63701755-d4bcd100-c825-11e9-9c7f-c5b9a867d3d9.png">

**Comment by bmarty** [comment]
Done

![image](https://user-images.githubusercontent.com/3940906/63845188-ddc6b300-c989-11e9-891a-b9d847bbe87d.png)
