### ISSUE TITLE
Handle the case of no IS in features that require IS to lookup

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3277]
Cloned from https://github.com/vector-im/riot-web/issues/10619.

Since it's now possible to be disconnected from an identity server entirely (your session has no active identity server), it's unclear how features that require an IS to function should behave.

For the case of the Discovery section in Settings, it's easy enough: you have no IS, so we don't show any 3PIDs to control.

However, there are other IS-using features in Riot, like:

1. Inviting by 3PID
2. (There might be more such features in mobile, so please add if so.)

**Comment by BillCarsonFr** [comment]
Here c6e1b188b43db8e4d2a6fec33985418f00f07565
