### ISSUE TITLE
Email help text on registration should be updated without binding

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3278]
Riot Web issue: https://github.com/vector-im/riot-web/issues/10674

New wording: https://github.com/matrix-org/matrix-react-sdk/pull/3355/files#diff-1f012ebe9aff500e45537ee54d009d17R574-R591

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2675)

**Comment by bmarty** [comment]
Done
