### ISSUE TITLE
Send IS for adding MSISDNs only when required by HS

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3281]
Cloned from https://github.com/vector-im/riot-web/issues/10599

Similar to email handing, [MSC2263](https://github.com/matrix-org/matrix-doc/pull/2263) records that `m.require_identity_server` will return a boolean that applies to both email and MSISDN cases.

Earlier in the project, it was unclear what would happen for MSISDN cases. As of this task, we we will only supply an IS to the HS in the following paths:

* Registration with MSISDN, but do not send if `m.require_identity_server` exists and is false
* Adding MSISDN to HS account, but do not send if `m.require_identity_server` exists and is false
* Binding MSISDN for discovery (request proxied via HS, always send IS)

This should match the behaviour with email.

**Comment by BillCarsonFr** [comment]
Done in sdk 66be4128b8aa4b768f009ed17c06ff5db3b76c61
