### ISSUE TITLE
Use wellknown to discover the IS of a custom HS

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3283]

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2686)

**Comment by bmarty** [comment]
Done. Not that the Identity server field is populated, but my stay hidden, depending on the HS configuration

**Comment by bmarty** [comment]
https://github.com/matrix-org/matrix-android-sdk/commit/d65225fe04d361a9b2fed4993d852d37478fa04e
and https://github.com/vector-im/riot-android/commit/78226f46e17f2c0be3beb0f422a050eb572269a6
