### ISSUE TITLE
Lowercase emails during IS lookup calls

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3289]
Cloned from https://github.com/vector-im/riot-web/issues/10754

As described in MSC2265, we should lowercase emails as part of lookup requests to avoid confusion because of casing.

This is particularly important for the new hashing based lookup style, since the IS can't see the plaintext version to adjust the case.

**Comment by BillCarsonFr** [comment]
Already done by bmarty in sdk f507dd56afaca15165882ce068bb9e0d845b135b
