### ISSUE TITLE
Riot configuration link to customise HS

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3294]
From riot-meta created by [manuroe](https://github.com/manuroe): vector-im/riot-meta#307  

This link will open the app and set up the homeserver URL (and the identity server URL while it is still required).

doc:  https://docs.google.com/document/d/12lYrrjP9q5BXghJICYTo0gvHMewGrXGznoozMRLPpMw

**Comment by bmarty** [comment]
Done in #3296
