### ISSUE TITLE
Use `id_access_token` in CS API when required

### ISSUE THREAD

**Issue by manuroe** [vector-im/riot-android#3295]
Make sure we pass the token on CS APIs that need it, ie:
 - inviteByThreePid: `POST /rooms/$roomId/invite`
 - all `/requestToken` APIs: 
     - `/register/email/requestToken`
     - `/register/msisdn/requestToken`
     - `/account/3pid/email/requestToken`
     - `/account/3pid/msisdn/requestToken`
     - `/account/password/email/requestToken`
     - `/account/password/msisdn/requestToken`

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2704)

**Comment by manuroe** [comment]
With https://github.com/matrix-org/matrix-doc/blob/anoa/msc_separate_hs_api/proposals/2290-separate-threepid-bind-hs.md, it seems we will not need this token for:
     - `/account/3pid/email/requestToken`
     - `/account/3pid/msisdn/requestToken`
     - `/account/password/email/requestToken`
     - `/account/password/msisdn/requestToken`

**TODO**: douche check this and check requirements for others. Then, update the issue.

**Comment by anoadragon453** [comment]
The required endpoints should just be:

* `POST /rooms/$roomId/invite`
* `POST /createRoom`

The `/requestToken` endpoints (at least password and registration) shouldn't need it. I'll try to figure out what's up.

**Comment by BillCarsonFr** [comment]
See #3322
