### ISSUE TITLE
Use the new backend APIs for adding-3pid-to-homeserver and binding-3pid-on-identity-server when they exist. 

### ISSUE THREAD

**Issue by lampholder** [vector-im/riot-android#3300]
The new APIs will be defined in https://github.com/matrix-org/matrix-doc/pull/2290

* [x] Detect whether HS supports MSC2290 (look for unstable flag `m.separate_add_and_bind` or API version `r0.6.0`)
* [ ] Always show account 3PID section in Settings (even without IS) if the HS supports MSC2290
* [x] Add SDK support for `POST /_matrix/client/r0/account/3pid/bind`, `POST /_matrix/client/r0/account/3pid/unbind`, and `POST /_matrix/client/r0/account/3pid/add`
* [x] Add SDK support for `POST /_matrix/identity/v2/validate/<medium>/requestToken`
* [x] Implement new 3PID add flow for MSC2290 servers
* [x] Implement new 3PID bind flow for MSC2290 servers
* [x] Use `/unstable` prefix for APIs

**Comment by jryans** [comment]
See also Riot Web version: https://github.com/vector-im/riot-web/issues/10839

**Comment by BillCarsonFr** [comment]
baf6eb31b9038e17f729406e0cb5f9a030d15ae4
29e8b726e3d6b3c81316a4f1c0e5363f1c715578
