### ISSUE TITLE
TLS 1.3 Support

### ISSUE THREAD

**Issue by florian2833z** [vector-im/riot-android#3301]
Hello,

I need TLS 1.3 Support for the android application. Riot for windows seemingly supports this but android doesn't. When will TLS 1.3 be available?

**Comment by florian2833z** [comment]
Android 9

**Comment by florian2833z** [comment]
I just found out that Android does not support TLS 1.3, issue resolved.

**Comment by tleydxdy** [comment]
fwiw, my lineageos 16 (android 9) does support tls 1.3 it seems

**Comment by florian2833z** [comment]
Well then the samsung firmware sucks
