### ISSUE TITLE
[Feature Request] Pin messages

### ISSUE THREAD

**Issue by floviolleau** [vector-im/riot-android#3306]
For now, we can pin messages on a chat with the web version of Riot

Could it be possible to add also this feature to the mobile app?

It will be helpful ;)

Thanks!

**Comment by bmarty** [comment]
It will not be done in Riot-Android, but rather in https://github.com/vector-im/riotX-android/

**Comment by bmarty** [comment]
Also where do you see an option to pin a message?

**Comment by floviolleau** [comment]
Hi,

Sorry, it's in French but you will understand :).

![image](https://user-images.githubusercontent.com/5442973/65226587-6c30df00-dac7-11e9-9e1c-e82d182b7571.png)
![image](https://user-images.githubusercontent.com/5442973/65226560-61764a00-dac7-11e9-9330-329a2695995e.png)

**Comment by floviolleau** [comment]
As I understand it will be developped in RiotX
