### ISSUE TITLE
Riot should check for r0.6.0 server support alongside feature flags

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3312]
Cloned from https://github.com/vector-im/riot-web/issues/10883

To avoid a scenario where the server stops advertising the flags due to a spec release. See https://github.com/matrix-org/matrix-js-sdk/pull/1035 and related links.

**Comment by BillCarsonFr** [comment]
Fixed on https://github.com/matrix-org/matrix-android-sdk/pull/488/commits/ada967e2c90beebc692f86418cd099d6b5d98835
