### ISSUE TITLE
Add User-Interactive Auth to /account/3pid/add

### ISSUE THREAD

**Issue by jryans** [vector-im/riot-android#3333]
Add User-Interactive Authentication to the `/account/3pid/add` endpoint as per [MSC2290](https://github.com/matrix-org/matrix-doc/pull/2290/files#diff-05cde9463e9209b701312b3baf2fb2ebR48).

See also https://github.com/matrix-org/synapse/pull/6119
Cloned from https://github.com/vector-im/riot-web/issues/11003

**Comment by BillCarsonFr** [comment]
When auth is required (and it should always be), the flow looks like:
First POST /account/3pid/add

{
    "sid":"DDBPiNqdYcwpXTmC",
    "client_secret":"Eqj0NhnulGDLIJwYIDTP1MTSesYaTpi2"
}

401

{
	"session": "AKMdFRcWreRwtDxlKiNZRVCV",
	"params": {},
	"flows": [{
		"stages": ["m.login.password"]
	}]
}

Last POST /account/3pid/add

{
    "auth": {
    	"identifier": {
    		"type": "m.id.user",
    		"user": "@testmanu:example.com"
    	},
    	"password": "111111",
    	"session": "AKMdFRcWreRwtDxlKiNZRVCV",
    	"type": "m.login.password",
    	"user": "@testmanu:example.com"
    },
    "client_secret": "Eqj0NhnulGDLIJwYIDTP1MTSesYaTpi2",
    "sid": "DDBPiNqdYcwpXTmC"
}

200
