### ISSUE TITLE
Crash on Android - IllegalArgumentException

### ISSUE THREAD

**Issue by Jurrie** [vector-im/riot-android#3355]
Riot.im updated on 8 october (15 hours ago according to Android). Since then, when I open Riot, I get a crash.

Stacktrace starts with:
java.lang.RuntimeException: Unable to create application im.vector.VectorApp:
java.lang.IllegalArgumentException: Invalid URL host: ""
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5838)

I use Riot with a private Synapse installation. I do not use an identity server, and I suspect I have left that field empty on first use. (I can not check this now of course - the bloody thing keeps crashing.) Maybe that's related...

**Comment by RussellAult** [comment]
I'm having exactly the same issue (app crashes on start, same stacktrace, private Synapse server with a blank identity server setting) except that the update for me came from the Play Store instead of F-Droid.

**Comment by Jurrie** [comment]
My update came from the Play Store also. I do not use F-Droid.

**Comment by BillCarsonFr** [comment]
There is a new version 0.9.8 published on the store. Can you try with this one when you get the update? thx

**Comment by Jurrie** [comment]
Aaaah... much better! App is working now - thanks for the quick response!

**Comment by RussellAult** [comment]
That solved it for me too. Thanks!
