### ISSUE TITLE
F-Droid build outdated (again)

### ISSUE THREAD

**Issue by akallabeth** [vector-im/riot-android#3357]
Anything happened that the f-droid version stays at 0.9.4?
really looking forward to the new notification stuff found so an update of the build scripts would be really appreciated ;)

**Comment by akallabeth** [comment]
Ok, https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/im.vector.alpha.yml is not up to date.

**Comment by Kovaelin** [comment]
Is F-Droid just an afterthought? It's outdated again. Last update on the Play Store was from a month ago.
