### ISSUE TITLE
Room Widget Permission UX

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-android#3378]
Related to https://github.com/vector-im/user-stories/issues/7

Before loading a room widget created by another user, the user should be prompted to give explicit permission.
Permission is given once per widget

<img width="259" alt="image" src="https://user-images.githubusercontent.com/9841565/68305245-9a827200-00a7-11ea-83af-cf5511918a24.png">

Use SDK to store and retrieve permission

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2833)
