### ISSUE TITLE
Room Widget Permission / Global UX to revoke given permisions 

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-android#3379]
See https://github.com/vector-im/user-stories/issues/7

BR: I can revoke this permission if I change my mind by interacting with a top-level widget UX element

>I can revoke this permission on a per-widget basis if I change my mind by interacting with a UX element on the 'top level' of the widget (i.e. I don't have to click into a 'widget options' context menu)

**Comment by manuroe** [comment]
Kamino cloned this issue to [vector-im/riot-ios](https://github.com/vector-im/riot-ios/issues/2834)

**Comment by BillCarsonFr** [comment]
Looks like requirements changed, and it can be put in context menu
