### ISSUE TITLE
Missing Access Token when making call to identity server

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/riot-android#3404]
See rageshakes:

https://github.com/matrix-org/riot-android-rageshakes/issues/8299
https://github.com/matrix-org/riot-android-rageshakes/issues/8204
https://github.com/matrix-org/riot-android-rageshakes/issues/8090

**Comment by akashpal-21** [comment]
I have the same issue, nobody can find me on matrix with my email or phone. Hasnt been fixed yet

**Comment by mlnease** [comment]
I have the same issue--under Settings>Discovery my address displays 'Missing Access Token' in red, but with no clue how to fix it.

Thanks for your time and attention.

**Comment by akashpal-21** [comment]
It seems like no one cares enough to fix it.
If only i knew how to fix it. Telegram it is for now i guess.

**Comment by asdil12** [comment]
Does anyone of you with this issue use an account on the `matrix.org` server?
I have this issue too and want to verify that it is not a configuration issue of my homeserver.

**Comment by svenb1234** [comment]
Yes, this happens with accounts at matrix.org as well.

**Comment by swot-thomper** [comment]
This is a pretty major roadblock for expanding their user base. Are the developers going to acknowledge this issue?

**Comment by stuart12** [comment]
I see this connected to my homeserver (which uses vector.im) and to matrix.org.

On the "Discovery" screen, under "Discoverable email addresses", there is a red "Missing Access Token" message under each email address and "Retry" button next to each email address. When I click on "Retry", I get a spinner and soon afterwards a toast saying "java.lang.Exception: Missing Access Token". This is with F-Droid Riot 0.9.10 (F-6f8ee3c4f) on Android (LineageOS 17.1 & 16.0) and with Google Play Riot 0.9.10 (G-6f8ee3c4f) on LineageOS 16.0.

I cannot see any exceptions with "adb logcat".

**Comment by MikeCheque** [comment]
This issue still persists in my setup

**Comment by svenb1234** [comment]
Fixed for me.
