### ISSUE TITLE
Missing Access Token

### ISSUE THREAD

**Issue by akashpal-21** [vector-im/riot-android#3411]
![Screenshot_20200110-181617_1](https://user-images.githubusercontent.com/46517170/72154072-8f99d580-33a7-11ea-9210-a878eeddda1e.jpeg)

**Comment by vrozsas13** [comment]
I noticed this too.

**Comment by swot-thomper** [comment]
Can't figure out why this is happening.
I can see no other threads about it have received any kind of response from devs

**Comment by bmarty** [comment]
Duplicate of #3404
