### ISSUE TITLE
No push notification when using Wireguard

### ISSUE THREAD

**Issue by derritter88** [vector-im/riot-android#3423]
I am using Wireguard (VPN) for a week but I am unable to get any notifications when someone sends me a message.
As soon as I open the app I can see all unread messages.

I have used the Riot built-in debug tool but it does not show any errors.

**Comment by derritter88** [comment]
Was an issue with my firewall.
Solved it by opening the necessary push ports for Google push notifications

**Comment by jesushfloresn** [comment]
> Was an issue with my firewall.
> Solved it by opening the necessary push ports for Google push notifications

Hello, Sorry.

What are the necessary ports?

**Comment by derritter88** [comment]
I had to allow the Google push services:
5228-5230 TCP/UDP
