### ISSUE TITLE
Share an image with text from an external app

### ISSUE THREAD

**Issue by 145k0v** [vector-im/riot-android#3427]
From an external app, I try to share an image with text like this:
```
Intent i = new Intent();
i.setAction(Intent.ACTION_SEND);
i.putExtra(Intent.EXTRA_STREAM, bitmap);
i.putExtra(Intent.EXTRA_TEXT, stringText);
i.setType("image/jpeg");
startActivity(Intent.createChooser(i, "title"));
```
If I set mime type to
- "image/jpeg", only the image is shared;
- "image/jpeg, text/plain", again, only image is shared. This time image is visible in Riot Android app, but not in the desktop client (in the desktop client I have to click on the image to see it, otherwise it looks like a big transparent empty message);
- "text/plain", only text is prefilled in the message input, and no image is sent

**Comment by bmarty** [comment]
Riot-Android does not (and I assume will never) support sending image with caption.
RiotX may support this in the future

**Comment by EsmaeeilMoradi** [comment]
Riot-Android : i added a caption to image and video. (I added a caption to the file name and send, receive file name another client. extract file name and edit  String finally show in  text view )
