### ISSUE TITLE
Exporting E2E keys in RiotX not working

### ISSUE THREAD

**Issue by bergmannf** [vector-im/riot-android#3479]
When I export the E2E keys from the RiotX App it creates a new file in the downloads folder, but when I try to import the keys (either in RiotX or the desktop app) it fails with the message `Trailer line not found`.

When I check the generated file it looks like this:

```
-----BEGIN MEGOLM SESSION DATA-----
<about 28000 lines of base64 data with newline every second line>
```

It seems there is not corresponding `-----END MEGOLM SESSION DATA-----`.

I tried the workaround to add the `-----BEGIN MEGOLM SESSION DATA-----` line by hand, but that did not fix it and only changed the error to `Authentication check failed: incorrect password?`

The `RiotX` app is version `0.20.0 [40020002] (G-b2640)`

**Comment by bmarty** [comment]
Please open RiotX (which is now Element-Android) into this project: https://github.com/vector-im/element-android

**Comment by JustinTArthur** [comment]
@bmarty can you clarify what you mean by open RiotX into element-android?

**Comment by aaronraimist** [comment]
@JustinTArthur he is asking you to file the issue here: https://github.com/vector-im/element-android/issues

**Comment by bmarty** [comment]
Yes, sorry for the typo, I mean "Please open RiotX **issues** into Element Android project"
