### ISSUE TITLE
Consider removing (or renaming) Riot Android from the play store

### ISSUE THREAD

**Issue by ghost** [vector-im/riot-android#3482]
Riot for Android has major compatibility issues with the current Riot Web/Desktop clients. Encryption verification currently doesn't work at all (it hangs indefinitely after accepting emoji verification) and, from what I can tell, Riot Android development has been largely abandoned in favor of RiotX. This situation means the top official result for Riot/Matrix on the Play Store is an app that largely doesn't work. This hurts adoption and increases friction for new users. 

I'm aware RiotX is still in a preview/Early Access state, but it's already more usable than Riot Android in practice. For that reason I would suggest removing this project from the Play store or at least consider renaming it to "Riot (Legacy)" or something similar to make it clear this application is no longer recommended.

**Comment by bmarty** [comment]
Yes, that's true. RiotX will replace Riot-Android on the PlayStore in a few weeks as per https://github.com/vector-im/riotX-android/issues/1273
