### ISSUE TITLE
Failed to resolve: org.matrix.gitlab.matrix-org:olm:3.1.2

### ISSUE THREAD

**Issue by sealiasheq** [vector-im/riot-android#3501]
Report them on the RiotX project: https://github.com/vector-im/riotX-android

When I run riot get me bellow error:

```
Failed to resolve: org.matrix.gitlab.matrix-org:olm:3.1.2
Show in Project Structure dialog
Affected Modules: matrix-sdk, matrix-sdk-crypto
```

I see bellow links but not work for me:

[vector-im](https://github.com/vector-im/riot-android/issues/3242)

[jitpack](https://github.com/jitpack/jitpack.io/issues/3908)

[vector-im](https://github.com/vector-im/riot-android/issues/3194)

What can I do?

**Comment by bmarty** [comment]
> What can I do?

Sadly nothing better than wait for Jitpack to provide the lib again, which seems to be the case now.
