### ISSUE TITLE
Riot becomes unusable after update to element.

### ISSUE THREAD

**Issue by theauditor** [vector-im/riot-android#3508]
Yesterday evening I had upgraded my Riot Android to Element. The latest update.
Issue flow.
1. Updated the client to  1.0.0.40100002 (Element)
2. Opened client.
3. The app gets stuck on Initial sync.
4. The message reads "Importing account Data", the Status bar stays semi filled and then restarts the progress from beginning in a never-ending loop.
5. Issue has been persistent for 30 minutes I kept the phone to see if it fixes itself.

This issue had plagued my RiotX install previously (but not on Riot), one primary reason I could not use RiotX , however this does not seem to be fixed. The issue is there with RiotX too. 

Using Mi A3 - Android One - Android v10

Screenshots : https://postimg.cc/gallery/gZdTD8B

**Comment by Faless** [comment]
In my case, it was caused by this: vector-im/riotX-android#1699 .
As mentioned in this comment https://github.com/vector-im/riotX-android/issues/1699#issuecomment-661362434 , deleting all the blocked users from the web client, then allowed me to correctly login from the android client.

**Comment by theauditor** [comment]
Deleted blocked users and it solved the issue. 
Seems it is about to be fixed on the next update.

Thank you, @Faless
