### ISSUE TITLE
Landscape view in Element, poorly arranged compared to Riot.im

### ISSUE THREAD

**Issue by zeigerpuppy** [vector-im/riot-android#3509]
In landscape view in Element, the notification for rooms is presented in a vertical list.
This means that the user has to scroll to see which conversations are active.

The view in Riot.im is much better, because the notifications are presented horizontally (one row for people, another row for rooms).

There is much better visibility in the Riot.im approach,
please implement this view for users who rely in landscape orientation.

**Comment by bmarty** [comment]
Please open issue about Element in https://github.com/vector-im/element-android
