### ISSUE TITLE
Update issue creation templates

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/riot-android#3517]
Clarify that the riotX repo
- is now the element repo
- should be used for element

![image](https://user-images.githubusercontent.com/2803622/93872338-489f0680-fcd0-11ea-9f70-ec94bf1245c9.png)

**Comment by bmarty** [comment]
Done, thanks for reporting that!

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/3940906/93883286-aa1ba100-fce1-11ea-8404-5de395ae0356.png">
