### ISSUE TITLE
Add a setting to toggle rageshake on/off

### ISSUE THREAD

**Issue by oddvar** [vector-im/riot-android#411]
> Rageshake is a feature when the phone detects 'shaking' it offers bug report options.
> It is annoying if it keeps popping up when you don't want it...

A few people asking how to turn rageshake off. It would be nice to be able to toggle it.

**Comment by ylecollen** [comment]
There also is a button to disable it.
The confirmation dialog has 3 buttons : one is "disable"

**Comment by oddvar** [comment]
ah nice. But is there a way to turn it on again after you have disabled it?

**Comment by Mikaela** [comment]
I would also like to restore the ability to rageshake after saying never to it a long time ago.

I know that I can send a rageshake by selecting report a bug from menu, but that preselects screenshot and most of times when I want to rageshake, I am unable to get a screenshot of the problem as report a bug takes the screenshot immediately of the home interface.

**Comment by bmarty** [comment]
There is now a dedicated setting to enable/disable rageshake
