### ISSUE TITLE
f-droid: Add an option for Vector to autostart when phone boots

### ISSUE THREAD

**Issue by oddvar** [vector-im/riot-android#412]
Several people have requested this feature

**Comment by ara4n** [comment]
See also #319

**Comment by unknownloner** [comment]
I would also like this feature added. I'm currently using the F-Droid version, and I suspect that at some point in the future I'll reboot my phone and forget to manually launch riot, and as a result I'll miss messages until I either get to my computer or remember to launch it again.

Would be great to be able to auto-start at boot.

**Comment by inducer** [comment]
This seems to be present in recent releases, as of 0.7.03.

**Comment by sim6** [comment]
@ylecollen I think this issue can be closed since https://github.com/vector-im/riot-android/commit/2ea7205195de12899572766d5d401294e0598fc1 was released.

**Comment by giomfo** [comment]
Thx @sim6, you're right

**Comment by sim6** [comment]
:)
