### ISSUE TITLE
Markdown : <Li> tags are not properly rendered on android < Lollipop

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#420]
Certain elements are rendered with extra line breaks. 

Including, but probably not limited to: ordered and unordered list, quotes (>).

https://vector.im/beta/#/room/!GnEEPYXUhoaHbkFBNX:matrix.org/$1472213655396333cKkdQ:matrix.org

**Comment by sabrinaj** [comment]
Fixed. See https://github.com/vector-im/riot-android/issues/1255.
