### ISSUE TITLE
Better welcome screen

### ISSUE THREAD

**Issue by oddvar** [vector-im/riot-android#43]
Currently when you register and load the app, you see this massive white screen (attached) with no obvious thing to do (except, perhaps, clicking on the + sign which creates a room, which is probably not the first thing you want to do).

We should have a better welcome screen or perhaps "first time use" overlay with "click here to view a directory of rooms" and "click here to search for your contacts" etc. 
![welcome](https://cloud.githubusercontent.com/assets/1705873/13923424/77dde782-ef78-11e5-861d-7af10315f766.png)

**Comment by bmarty** [comment]
Hello, I think this (old) pb is fixed now
