### ISSUE TITLE
Update the notifications management design to have the same features level than the webclient

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#472]
The notifications have four available settings on the webclient
-> All messages (loud)
-> All messages
-> Mention only
-> Mute 

the mobile clients have only two 
-> enable (== All messages)
-> disable (== mention only)

**Comment by Valodim** [comment]
:upvote:, this is a critical feature and the number one complaint I get about Riot-Android right now. "mentions only" is the only reasonable notification mode for channels with any amount of activity.

**Comment by 4311021x** [comment]
It seems like disable completely disables it. I get notifications on the webclient only when I set it to mentions only.

**Comment by giomfo** [comment]
fixed (https://github.com/matrix-org/matrix-android-sdk/commit/5a2e26a6d77f538daf536412b6779cc1a9d1953c)
