### ISSUE TITLE
Need a design for files (images, videos and files) inside chat history?  thumbnails video indicator loading wheel when the doc is loading Failure mode if the file is unsent

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#478]
Need a design for files (images, videos and files) inside chat history?

thumbnails
video indicator
loading wheel when the doc is loading
Failure mode if the file is unsent

**Comment by giomfo** [comment]
see https://github.com/vector-im/vector-ios/issues/588 and https://github.com/vector-im/vector-ios/issues/592

**Comment by antikewl** [comment]
Send error: https://zpl.io/14wyfu
Image thumbnail: https://zpl.io/9TATV
Video thumbnail: https://zpl.io/25ajAa
Image upload: https://zpl.io/bzj95
Image upload portrait: https://zpl.io/PdUzE
Image upload failed: https://zpl.io/ZwbNK2
File wo preview: https://zpl.io/Z2c2H5X

**Comment by giomfo** [comment]
antikewl, the provided design seems ok

About 'Send error' (https://zpl.io/14wyfu), the avatar of the unsent message is wrong, isn't it?
BTW, we plan to display on mobile app the same message as the web with 2 options: "Resend all or cancel all now". Could you please update this screen?

**Comment by antikewl** [comment]
How's this: https://zpl.io/14wyfu

**Comment by giomfo** [comment]
LGTM

**Comment by bmarty** [comment]
Seems to be done
