### ISSUE TITLE
Change the message edit edit like in web 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#479]
Need the icon

**Comment by antikewl** [comment]
I need a bit more info for this one. Can you provide a screenshot?

**Comment by giomfo** [comment]
We need the same icon as the web client for the event context menu `(...)`
![screen shot 2016-10-07 at 15 33 55](https://cloud.githubusercontent.com/assets/8969772/19191626/9765c48a-8ca3-11e6-8656-874f3c702160.png)

**Comment by antikewl** [comment]
The individual messages on Android shouldn't have a context menu icon. The context menu is revealed via a press and hold.

**Comment by giomfo** [comment]
antikewl, how the user can display the timestamp of a message in android design?
I did not succeed to find the relative screen.

**Comment by bmarty** [comment]
done
