### ISSUE TITLE
Custom notification setting

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-android#509]
Android notification setting should be a choice of either full last message, or several snippets on a new line each like WhatsApp or several of the latest messages in full, like Slack 
from Aaron Sollesse (@AaronSollesse ) on twitter

**Comment by neomodern** [comment]
**Current Riot notification-style = 'full last message' notification:**
Person 3: Test message to see how long a message can fit in the notification UI. 

**WhatsApp 'several snippets on a new line each' notification:**
Person 1: Test message to see how lon...
Person 2: Reply to message to see how...
Person 3: Reply to the reply to messag...

**Slack 'several of the latest messages in full' notification:**
Person 1: Test message to see how long a message can fit in the notification UI. 
Person 2: Reply to test message to see how long a message can fit in the notification UI. 
Person 3: Reply to the reply to message to see how long a message can fit in the notification UI. 

3 different styles, and in the interest of being everyone's cup of tea I'd say it's best to offer the user the choice of what notification style they prefer.

**Comment by bmarty** [comment]
Done in Riot 0.8.26
