### ISSUE TITLE
Support ability to select the room directory server being queried

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#513]
We're going to turn off the ability for synapses to spider other synapses for rooms, and instead make it the client's problem to select the server being queried

**Comment by erikjohnston** [comment]
(The PR that added it: https://github.com/matrix-org/synapse/pull/1121)

**Comment by ylecollen** [comment]
We're waiting after dbkr & leo APIs.

**Comment by ara4n** [comment]
this now exists, i believe?
