### ISSUE TITLE
The riot-android client should delete notifications, if they are marked read by another client.

### ISSUE THREAD

**Issue by maralorn** [vector-im/riot-android#526]
It already does this at the moment, but only when you open the app.

**Comment by ylecollen** [comment]
Which version are you using ? google Play or F droid.

The android client is only woken up a by notification. If there is none, the android client cannot clear it.

**Comment by ylecollen** [comment]
I don't reproduce your issue.
Do you always reproduce it ?
Could you send a bug report ?

**Comment by maralorn** [comment]
Uh, yes, I can always reproduce it.
I use the latest the riot version from the playstore with android 6.
To my knowledge I have all relevant power saving features disabled.

When I get a mention or a highlight on matrix. My phone vibrates and the LED starts blinking. When I now open Riot in the browser and read the message the phone continues to blink. Now when I pick up my phone and open riot-android. I can see the notifications for a split second and then the client apparently gets all informations from the server and marks everything read and deletes the notifications.

**Comment by ylecollen** [comment]
maralorn,

could you send a bug report just after having your issue? 
i don't reproduce it.

**Comment by Valodim** [comment]
thought this didn't work as well, but I just tested this behavior explicitly and it works just fine for me (albeit a bit slow). Using riot from gplay, and I'm on my own homeserver so that's not it.

@maralorn Can you still reproduce this?

**Comment by maralorn** [comment]
Wow, this got totally lost on me. No I can’t.
