### ISSUE TITLE
Provide a smarter notification icon

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#530]
![screenshot_2016-09-20-09-13-14](https://cloud.githubusercontent.com/assets/8971031/18660790/b9ad4e9e-7f12-11e6-9761-c2864a95168f.png)

**Comment by giomfo** [comment]
Matthew, the Android users complain about the current notification icon.
Could you please check whether a smarter notification icon may be provided?

**Comment by bmarty** [comment]
Hello @dkanada ,

Thanks for the proposal. Yes, feel free to submit a PR to update the notification icon. Please follow the Android guidelines here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar (no need to take care of Android version before 3.0)

Thanks

Benoît

**Comment by bmarty** [comment]
Done
