### ISSUE TITLE
Improve room UI in landscape with conf call banner

### ISSUE THREAD

**Issue by pedroGitt** [vector-im/riot-android#533]
Steps to reproduce:
1. device1: start a conf call in room A
2. device2: go to room A (the red banner "Ongoing conference call.." is displayed on the top)
3. device2: rotate the device to be in landscape mode
4. device2: start typing a message to launch the keyboard
5. device2: in certain devices, once the keyboard is displayed, there is not enough space left between the banner and the keyboard to see the room message's

[Screen shot issue - permalink](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$14743042193112mpjYN:berigora.net)

**Comment by ylecollen** [comment]
![qgwxfbemhzyftkyujscwjjud](https://cloud.githubusercontent.com/assets/8971031/18663740/0b964b9a-7f20-11e6-87b1-ce4754a4b4ba.png)

**Comment by bmarty** [comment]
This issue won't be addressed.
Fix is to rotate screen back to portrait
