### ISSUE TITLE
Support writing strikethrough text in markdown using ~~text~~

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#545]
~~Strikethrough~~

**Comment by ylecollen** [comment]
The markdown is properly parsed but not properly displayed.

**Comment by Matrixcoffee** [comment]
According to my tests the latest release version sends tildes as-is. I will test the latest develop build tomorrow.

**Comment by ghost** [comment]
Okay, I confirm that the 5 october f-droid build now properly parses ~~ when sending messages.

I recommend this bug to be closed since it's working, and vector-im/element-web#544 to be reopened, since that one is about the rendering issue.

**Comment by unclechu** [comment]
It could be solved by inserting `U+0336` after every symbol inside tildes, like t̶h̶i̶s̶.

**Comment by pedro-nonfree** [comment]
pleeeeeease

**Comment by ghost** [comment]
Parsing works, so closing this. See vector-im/element-web#544 for the rendering issue.

**Comment by mlaily** [comment]
Hello,

This feature does not work in Riot web 1.5.13

And according to my simple test, it's the markdown that is not parsed at all:

![image](https://user-images.githubusercontent.com/1535823/77311247-09cbcc00-6d00-11ea-85ed-fb03585c951a.png)


Could someone please re-open this issue?

**Comment by unclechu** [comment]
@mlaily `<del>strike</del>` works

**Comment by mlaily** [comment]
> 
> 
> @mlaily `<del>strike</del>` works

Thanks for the tip, indeed it does.

But this is not user-friendly at all. This issue is about supporting the standard (?) markdown way with "~~".

**Comment by mcg-matrix** [comment]
> This feature does not work in Riot web 1.5.13
 > [...]
 > Could someone please re-open this issue?

That would now be vector-im/element-meta#529, I guess.
