### ISSUE TITLE
Add setting to have a separate notification for each Room

### ISSUE THREAD

**Issue by ajvsol** [vector-im/riot-android#556]
Right now all Room notifications are stacked in one notification, with only a small numerical indicator to show that multiple Rooms have new messages.

**Relevant to this:** also having a separate notification for each Matrix User you're logged in as, or for every 'folder/group of Rooms' you have created.

**Comment by jfrederickson** [comment]
I would actually suggest setting this as the default - it's what Facebook Messenger does, and for users with lots of small chats between friends it's incredibly helpful to make sure you don't miss any.

**Comment by bmarty** [comment]
Done in Riot 0..8.26
