### ISSUE TITLE
Media picker: Switching camera button and exit button are not very visible

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#565]
Related to https://github.com/vector-im/vector-ios/issues/610.

A solution is required for android too

**Comment by ylecollen** [comment]
The android client uses the IOS client UX by now.

**Comment by antikewl** [comment]
Now uses the android back arrow, has a black background with 40% opacity. I have also switched the icons to white so that they're both less obtrusive and more legible.

https://zpl.io/zMcKh

**Comment by giomfo** [comment]
signed off
