### ISSUE TITLE
Swipe left to quickly switch to the next active room

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#573]
And swipe right to go back to previous rooms. If there are no more previous rooms, show the room list.

Supercedes #527

**Comment by Matrixcoffee** [comment]
See also the discussion starting here: https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/$147503281810dzyQM:max.mislik.de

Excerpts relevant to implementation:

>Order is by swipe history. If you run out of history on swiping right, you get the room list. If you run out of history on swiping left, it should probably **go to the room with the oldest unread message**, and append it to history. History should be cleared on entering a room by means of the room list. (This all is more intuitive than it sounds.)

-
>mmi: The tl;dr of it is "swipe left to see unread messages; swipe right to go in reverse until you hit the room list."

**Comment by ylecollen** [comment]
The current implement is limited 
-> swipe left : go back to the recents page.

**Comment by ara4n** [comment]
It sounds from https://github.com/vector-im/riot-android/issues/527 as if we don't have the same UI as iOS on this - and meanwhile, folks like Viber & Telegram supporting swipe-for-back on Android.  What happened to this in the end?

**Comment by ara4n** [comment]
oh, actually, #1871 is actually asking for https://github.com/vector-im/riot-android/issues/527. let's try solving that one first.
