### ISSUE TITLE
Design for direct chat in member details page 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#619]
According to https://github.com/vector-im/vector-web/issues/2099

The joined rooms should be displayed before the "start direct chat button".

We need a design for the mobile clients.

**Comment by ylecollen** [comment]
![zuinsarqxigbagjvakgqjthr](https://cloud.githubusercontent.com/assets/8971031/19267716/970eb87e-8fb0-11e6-8b22-a8326eadb5c5.png)

**Comment by giomfo** [comment]
The current design is fine
