### ISSUE TITLE
Register without internet connection : the unability to register is not clear

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#637]
To reproduce:
- Launch Riot without internet connection
- Hit the register button to open the register form
- The register button should be disabled like the log in button
- When you fill the form and hit the register button, there is no indication that the register is impossible because of the internet loss

**Comment by sabrinaj** [comment]
I just tested and as soon as I arrive on the register form, there is a toast message saying "Unable to register..." which is clear enough I think. 

From now on, I also disable the registration button in that case (`develop` branch).

**Comment by jeangb** [comment]
I agree it seems OK now, button is disabled and there is this toast.
Validated.
