### ISSUE TITLE
Room directory shows non-canonical alias for some rooms that have no name set

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#638]
Version 0.5.3-dev (FDroid-b157c96)

**Comment by Matrixcoffee** [comment]
![screenshot_2016-10-18-20-37-29](https://cloud.githubusercontent.com/assets/21172059/19509564/d8bd89ac-95ce-11e6-966f-63b29d4a4728.png)
![screenshot_2016-10-18-20-10-38](https://cloud.githubusercontent.com/assets/21172059/19509576/e51f1166-95ce-11e6-8c2f-ab8b99c207be.png)

**Comment by bmarty** [comment]
TODO check if it is still the case

**Comment by bmarty** [comment]
@Matrixcoffee this old issue seems fixed now, can you confirm please? (I've check for #offtopic)

**Comment by bmarty** [comment]
Let's re-open it if this issue is observed again
