### ISSUE TITLE
Contact details: Start voice call failed silently

### ISSUE THREAD

**Issue by giomfo** [vector-im/riot-android#654]
"Start VoIP call" is available only for contact for whom a direct 1:1 room exists. Both members must have joined this room too.

We should not display the call options when this kind of room is missing.

**Comment by pedroGitt** [comment]
- After discussion, this item is considered as a "feature"
- The options to start a voip call or a video call present in the member details UI, are removed to align with the other platforms
- These options will be re considered, **once some UI specs will be available**

**Comment by ylecollen** [comment]
Works as Pedro describes
