### ISSUE TITLE
Shouldn't be normal tap on avatar for mention and long tap for menu, and not vice versa, as we have now?

### ISSUE THREAD

**Issue by aliencq** [vector-im/riot-android#667]
Mentions is used more frequently, than menu.

**Comment by ylecollen** [comment]
We have this design/behaviour by now on mobile clients.
We need to discuss about it.

**Comment by aliencq** [comment]
Normal tap for mention is used already on nicknames, btw.

**Comment by bmarty** [comment]
Current behavior is:

- tap on avatar: open member detail
- tap on username: mention
- long tap on message: open menu

So I think this issue can be closed
