### ISSUE TITLE
missing material design on Android 4.4

### ISSUE THREAD

**Issue by eyelash** [vector-im/riot-android#673]
On Android 4.4 the switches in the room settings do not use material design:
![screenshot_2016-09-20-17-41-48](https://cloud.githubusercontent.com/assets/2668288/20000175/80640768-a276-11e6-8a6e-e1b646dd2c8f.png)

I tried to find the cause and I believe it is because you are not using [SwitchPreferenceCompat](https://developer.android.com/reference/android/support/v7/preference/SwitchPreferenceCompat.html).

**Comment by ylecollen** [comment]
The client uses the preferenceFragment so it is OS dependant.
We need to find a way to have the material design anyway.

**Comment by ylecollen** [comment]
https://github.com/vector-im/riot-android/commit/3d77b0631d64cd38c418aa58fbe277f4da774cf0
