### ISSUE TITLE
Overview of received photo is black

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#676]
- Send a photo (from the image gallery of the phone) from device 1
- After reception on device 2: 
The photo is rotated and when I click on it the overview is black.
![black overview on received photo](https://cloud.githubusercontent.com/assets/22364949/20052626/1c38416c-a4d5-11e6-8f80-7b97c1cb54df.png)
Sent photo from device 1 is
![sent photo](https://cloud.githubusercontent.com/assets/22364949/20052963/abe479c4-a4d6-11e6-9b63-e9b02d1d0fc3.jpg)

Version 0.5.3-dev (20372b8)

**Comment by ylecollen** [comment]
Black could mean that the media cannot be downloaded.

**Comment by ylecollen** [comment]
I cannot fix this issue without a bug report (i don't reproduce it).
