### ISSUE TITLE
No notification Sound

### ISSUE THREAD

**Issue by sachoosaini** [vector-im/riot-android#681]
I have created a group, i have enabled the notifications from each and every setting. But when anybody from the group send ant message only the LED blinks. There is no sound that message or any file recieved. This bug has also been reported in the play store also.

**Comment by ylecollen** [comment]
Could you check with the webclient if the message should have sound ?
Do you know which rules triggered it ?
COuld you send a bug report ?

**Comment by sachoosaini** [comment]
well i don't know what had trigger it... i am attaching screen shots. I am android 6.0 and i had one phone on android 5.1.1 also. Well what happens is, there is no sound from notifications... Attaching screenies to explain what i meant. 
![screenshot_20161111-072717](https://cloud.githubusercontent.com/assets/10970138/20202069/97860a6a-a7e2-11e6-9208-cc9816e68e43.png)
![screenshot_20161111-072722](https://cloud.githubusercontent.com/assets/10970138/20202070/9ba78efc-a7e2-11e6-85a2-04529be3db84.png)
![screenshot_20161111-072731](https://cloud.githubusercontent.com/assets/10970138/20202073/9efd50f0-a7e2-11e6-98dd-ec67af0ace8f.png)
![screenshot_20161111-072753](https://cloud.githubusercontent.com/assets/10970138/20202075/a2352694-a7e2-11e6-9d9b-1ff34a7c7126.png)

..  i am 100% sure this the bug. Please add an option to choose manually a notification sound from android default notification sounds....

**Comment by ylecollen** [comment]
Have a look on the webclient interface.

We don't have the design to enable / disable sound.

**Comment by sachoosaini** [comment]
@ylecollen well in group you will never be notified about the message with sound. But when i choose any user for personal or private chat individually, then notification sounds are there.

**Comment by ylecollen** [comment]
![web settings](https://cloud.githubusercontent.com/assets/8971031/21137147/df547c6e-c128-11e6-9f01-b41e26b1b5ce.png)

**Comment by ylecollen** [comment]
Did you check the web settings ?
I believe that by default, there is no sound.

Moreover, you might have customised your notification rules for this room.

**Comment by dva-re** [comment]
I have same issue. When I played in the web client with checkboxes - the sound of the phone appeared in groups.

But how can I do it without web client?

**Comment by sachoosaini** [comment]
@ylecollen yeah i have ticked this option. But still there are no notifications in groups. So its not application issue ?

**Comment by bytesnz** [comment]
@sachoosaini, is this when you have the group chat open? I have just noticed that you don't get any sound if you have the chat open, which is a little annoying (for me at least). Wouldn't need to be the notification sound, just some sort of blip to say there is a new message

**Comment by bmarty** [comment]
Old, please open again if the issue is still observed
