### ISSUE TITLE
Cancelling download of encrypted image does not work

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#723]
How to reproduce:

* Click an image in an encrypted room. (Slow connection or big file will be helpful here.)
* Press the back button to go back to the timeline.
* Press the `X` next to the progress bar under the image.
* Answer "Yes" when asked if sure.
* Watch the progress bar continue to grow...

**Comment by ylecollen** [comment]
i suspect it is related the slowness we have with encrypted rooms.

I suspected to cancel several image uploads.

i will test with low end devices.

**Comment by Matrixcoffee** [comment]
I have some more info on this. I suspect Riot was downloading a (very big) thumbnail. It seems that for very big thumbnails, Riot shows the progress bar and the **x**, but if you press the **x** and press "yes", it does not cancel the thumbnaiil download.
