### ISSUE TITLE
Add the emojione from  http://emojione.com/demo/

### ISSUE THREAD

**Issue by maxlinux2000** [vector-im/riot-android#751]
This program would be even cooler with the emoticons

![emoti](https://cloud.githubusercontent.com/assets/5683921/20609383/05f01eb0-b28c-11e6-81d2-7a52e66bc238.png)

**Comment by Mikaela** [comment]
This would be especially good for consistency as currently Riot Desktop is using emojione and those emojis look very different on Android (and possibly iOS) which uses its native emojis.

I think Telegram is also using emojione on all clients.

**Comment by TheLastProject** [comment]
IIRC, Telegram actually uses the Twitter emojis by default, of which the copyright status is unclear, which is why the Telegram fork on F-Droid ships without those and uses system emoji. Anyway, Emoji One is a very good emoji set and I'd definitely support using that

**Comment by zzottel** [comment]
Actually, I don't mind which set it is, but consistency is important—among Web and Android and iOS as well as among different Android devices.

See also: https://www.inverse.com/article/14097-emoji-differences-by-platform

**Comment by bmarty** [comment]
Emojis can be sent by modern Android keyboard
