### ISSUE TITLE
Slowdown : Reduce the launching time.

### ISSUE THREAD

**Issue by sachoosaini** [vector-im/riot-android#753]
Using android 6.0.1, Cyanogenmod ROM.
Well I think after you applied the ability to encrypted messages, the app start slowing down a bit. I Mean before app was like whatsapp. There was no lag while opening. It got open in instant. I mean like you open whatsapp and VOILA all your messages are there. But now Vector kinda take time  to load. A few seconds. I am attaching the video. 
Device 
HONOR 5X .. 2gb ram. So i think its sufficient. [https://1drv.ms/v/s!AjPCVP5rZR0FjBSiy8jq2vwsT7I6](url)

**Comment by Matrixcoffee** [comment]
Hi. What version of Riot?

**Comment by sachoosaini** [comment]
@Matrixcoffee 0.6.3

**Comment by ylecollen** [comment]
Could you send a bug report ?
we should be able to tell you what takes a longer time.
I don"t think it is slower than before.

Notice, it takes only 3 seconds to be launched : it is not so slow.
You dont need to kill the application each time you don't use it.
Morever, the application is fully loaded only when the GCM registration to the third party server is done.

**Comment by sachoosaini** [comment]
@ylecollen well its not like that it is a bug. Well consider any app like whatsapp From the point of view of user. I can understand that every time app maybe registering with the server. 
But 3 seconds are ok with me, but with other people who are used to other apps. You need to convince them that something new more good and secure than whatsapp. Most of people are not of that view. 
When you click whatsapp then it does not take make you just login. It just shows all your groups and messages. Even when internet access is kinda slow or may not be there, you can just open any contact or group and type a message and it will get delivered at the moment when internet gets back. There are many countries where internet access is very weak. I mean people still use 2g networks. But RIOT needs to login after few minutes, like you said 3 seconds. I mean why should when there is no internet connectivity i should wait for the app to login. There is should be app opening style like whatsapp. At the moment you click the app icon from apps drawer, the very moment i couble be able to see the messages. There should be no need to go to the notification drop down menu to open the app and see messages. 
But RIOT is RIOT at the end of day. I love it and its great. Just wanted to make the user interface look good and craze to use.

**Comment by ylecollen** [comment]
We will improve this launching time when the encryption will be stable.

If you have time to help us, you are welcome.

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/6c279dda82d29e7940ea2b948b3c4c25eea0964e

should help

**Comment by ylecollen** [comment]
https://github.com/vector-im/vector-android/commit/45b489767a89c87952fbe0b9fb623e70c8537375 should help too.

**Comment by sachoosaini** [comment]
@ylecollen i can provide feedback. Please bring a tutorial somewhere about how to give you bug reports. I mean all the stuff you need to know about the issue. It would be really useful

**Comment by sachoosaini** [comment]
@ylecollen yesterday i have installed the RIOT as i flashed a new ROM. Now i could say RIOT is back :) ..Maybe its a team viewer but for me its my family's first talking platform these days....
