### ISSUE TITLE
status always be offline at some phones

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-android#762]
App run at a phone with Android version 4.2.2, after phone screen turn off, the status always become offline, cant notice only messages or events.

**Comment by ylecollen** [comment]
Could you send a bug report ?

**Comment by wjhtinger** [comment]
Just how to send a bug report ?

**Comment by ylecollen** [comment]
![bug_report](https://cloud.githubusercontent.com/assets/8971031/21017665/622fd92a-bd6a-11e6-8a9c-4b7fc1065eab.jpeg)

**Comment by ylecollen** [comment]
Notice that you might have installed a battery saver application which turns the connection off.

**Comment by wjhtinger** [comment]
I would want to know what connection which keeps the riot online? Or what services is used for this? 
When the phone screen turn off, I am sure that the Intenet aceess is OK, just because other IM App works well.

**Comment by ylecollen** [comment]
The android user is seen as offline because the application has been put in background.
The device receives push notifications if you define some rules to get them.
You can customize them in the global settings (the webclient has a better UI)

**Comment by ylecollen** [comment]
wjhtinger, i'm still waiting after your bug report.

**Comment by wjhtinger** [comment]
The  bug report has been sent, sorry for some delay

**Comment by ylecollen** [comment]
wjhtinger,

could you update your client and send a new bug report ?
Your latest ones were empty.

Anyway, any user will be seen offline when the application is put in background.
But, even when putting in background, you should receive some notifications if the dedicated pushes settings have been properly set.

**Comment by wjhtinger** [comment]
I use the latest version(6.4), find the report email attachment is always empty. I tested the version(5.2) is OK(4 attachments). Maybe I need to submit a issue for this?

About the offline issue, I tested four diffrent android phone, only that one has this issue. About 10 minutes after screen is locked, the status become offline, and cant give any notifications. I comfirmed that the settings is OK.

**Comment by wjhtinger** [comment]
I find another phone has this problem now.

**Comment by wjhtinger** [comment]
I have found the root cause now, just because that phone will turn off the WiFi for power saving in standby.
Close the issue.
