### ISSUE TITLE
localized version of Riot

### ISSUE THREAD

**Issue by maxlinux2000** [vector-im/riot-android#763]
Hi,
I found that strings.xml is localized only in english language.
I can translate in spanish and Italian if the programmers want integrate the localized files on the main sources.

**Comment by ylecollen** [comment]
It would be nice.

**Comment by mytbk** [comment]
l10n+1. I think using Zanata/Transifex would be nice.

**Comment by maxlinux2000** [comment]
You are rigth.... closing
