### ISSUE TITLE
[e2e] Single megolm session used in two rooms

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-android#765]
As reported at https://github.com/matrix-org/synapse/issues/1670

**Comment by richvdh** [comment]
It looks like event id `$14809148653745127JvpkR:matrix.org`  (in room `!XLWyWCSLuZXbEICJOL:matrix.org`) was sent using a megolm session (`G12NLajfv46nT7jjxVs4ek8FLbRyYxBaoVaghdOIcJE`) which was meant for room `!NmnHdagwJzKENAFywg:matrix.org`.

**Comment by ylecollen** [comment]
i don't see how to reproduce this issue.

**Comment by ylecollen** [comment]
duplicate of https://github.com/vector-im/riot-android/issues/864
