### ISSUE TITLE
Video call Avatar position should be in the top left

### ISSUE THREAD

**Issue by maxlinux2000** [vector-im/riot-android#767]
When I do a video call with Riot, my avatar is positioned on the nose of my partner. 
My avatar was better positioned, to the top left of the screen.

I think that the problem is in VectorCallViewActivity in this function:

```
private void insertCallView() {
        if(null != mCallView) {
            // set the avatar
            ImageView avatarView = (ImageView) VectorCallViewActivity.this.findViewById(R.id.call_other_member);

            // the avatar side must be the half of the min screen side
            Display display = getWindowManager().getDefaultDisplay();
            Point size = new Point();
            display.getSize(size);

            int side = Math.min(size.x, size.y) / 2;

            RelativeLayout.LayoutParams avatarLayoutParams = (RelativeLayout.LayoutParams)avatarView.getLayoutParams();
            avatarLayoutParams.height = side;
            avatarLayoutParams.width = side;

            avatarView.setLayoutParams(avatarLayoutParams);

            VectorUtils.loadCallAvatar(this, mSession, avatarView, mCall.getRoom());

            // insert the call view above the avatar
            RelativeLayout layout = (RelativeLayout)findViewById(R.id.call_layout);
            RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);
            params.addRule(RelativeLayout.CENTER_IN_PARENT, RelativeLayout.TRUE);
            layout.removeView(mCallView);
            layout.addView(mCallView, 1, params);

            // init as GONE, will be displayed according to call states..
            mCall.setVisibility(View.GONE);
        }
    }
```

I think that the problem is in the line
`params.addRule(RelativeLayout.CENTER_IN_PARENT, RelativeLayout.TRUE);`

....but I'm new in java so at the moment I can't fix it

some on can help me to fix this problem?

**Comment by ylecollen** [comment]
Could you post a screenshot ?

**Comment by maxlinux2000** [comment]
Sorry for the delay, I'm busy.

![screenshot_20161214-112212](https://cloud.githubusercontent.com/assets/5683921/21179073/b3e441f2-c1f2-11e6-95b7-43073d5312e7.png)

...as you can see the position of the avatar, annoys the vision of the face with whom you are talking.
It's best to move the avatar up or down, on one side.

**Comment by ylecollen** [comment]
there is a feature request to be able to move the avatar.

**Comment by maxlinux2000** [comment]
in the last build (0.6.5 from playstore) the avatar box is now in the bottom left. This is enough for the moment, but the ability to move the avatar is better :+1:
