### ISSUE TITLE
Notifications not cleared when room is read with custom HS

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-android#769]
In rooms set to notify on 'All messages', the notification is not cleared when the room is read in another client

**Comment by ylecollen** [comment]
When some messages are read from another client, the server should send a dedicated push notification to update the application badge.

The client triggers a catchup to retrieve the read messages and dismiss the notification if required.

**Comment by richvdh** [comment]
Hopefully this will be fixed by https://github.com/matrix-org/synapse/pull/1678.
