### ISSUE TITLE
[e2e][enhancement] A way to easily export device fingerprint

### ISSUE THREAD

**Issue by wldhx** [vector-im/riot-android#772]
Currently, the device fingerprint presented in Settings is not selectable or copyable, which is suboptimal for verification purposes.

Either these fields should be made copyable, or - even better - a separate export functionality allowing sharing device name and fingerprint with a share intent should be implemented.

**Comment by intelfx** [comment]
(cf. vector-im/riot-ios#857)

**Comment by ylecollen** [comment]
Long tap on each field  copies it to the clipboard

**Comment by wldhx** [comment]
@yannick It doesn't on F-droid 0.6.3 (21e7806), though perhaps it has indeed been fixed upstream.

I'd argue that a "share fingeprint" button is still beneficial regardless.
