### ISSUE TITLE
Bug report / rageshake does not get user consent before sharing potentially personal data

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-android#774]
It's nice to be able to dump a bug report from within Riot. However, I was very surprised when I first found out what I had sent, as the generated ZIP file contained a screenshot, disclosing information about the rooms I've joined, as well as the last message for each. Nothing happened, fortunately, but there could well have been confidential information .

I think the user needs to give consent before the package is sent. Could Riot please display the screenshot along with a message what else will be sent, and only do so if the user's okay with it?

Thanks,
-m

**Comment by ylecollen** [comment]
you can already send the zip in a oneself room and check the zip content.

The screenshot could be optional.

**Comment by madduck** [comment]
Oh I could have also first sent the bug report to myself by e-mail… had I known that there'd be a screenshot included. But I didn't know that, and by the time I found out, it was too late.

The screenshot could be optional, or at the very least, the user could be asked if they give consent to publishing the screenshot, maybe including a preview.
