### ISSUE TITLE
the 0.6.4 riot send encrypted message very slow

### ISSUE THREAD

**Issue by LifeNT** [vector-im/riot-android#780]
I send encrypted message to the same room, with my android phone and PC, both latest client, the PC riot has no delay, send very fast , but  android riot 0.64 is very slow, each message encrypted will wait 10-30 seconds before it's sent out, I mean message keep green  for 10-30 seconds,  I tried in different rooms, a cross home server room seems got very serious delay .
I don't get this delay with last version  on my phone, I mean yesterday there's no such serious delay, the last version only delay at first encrypted message,  the follows send quickly, but the 0.64 riot on android has big delay.

**Comment by LifeNT** [comment]
I have get back to  riot 0.6.3 on my phone ,encrypted message send quickly and smooth again!

**Comment by ylecollen** [comment]
I improved the code to reduce memory usage...

**Comment by ylecollen** [comment]
Could you test the latest develop version ?

**Comment by LifeNT** [comment]
I have updated desktop riot, it's auto updated, there's no problem yet,
send message very quick.

2016-12-14 16:06 GMT+08:00 Yannick LE COLLEN <notifications@github.com>:

**Comment by LifeNT** [comment]
you could test this room: #cntwer:matrix.org , I created on matrix.org,
encrypted, it's realy slow when send message with 0.6.4, each message
delayed,

2016-12-14 16:09 GMT+08:00 LifeNT <0xlifent@gmail.com>:

**Comment by ylecollen** [comment]
Could you invite me into this room ?

**Comment by ylecollen** [comment]
it seems faster on the develop branch

**Comment by LifeNT** [comment]
I'll try new version.

2016-12-14 16:25 GMT+08:00 Yannick LE COLLEN <notifications@github.com>:
