### ISSUE TITLE
Add fingerprint option to login to app or fingerprint to any particular group 

### ISSUE THREAD

**Issue by methuselahin** [vector-im/riot-android#781]
well this is kinda very common thing these days. Phone's fingerprint sensor can be use to authenticate while entering in or logging into the application. These days more and more phones are coming with fingerprint sensors. [https://github.com/googlesamples/android-FingerprintDialog](url)
something like this if can be implemented that would be great.  Its a feature request more or less. Ebay uses this thing before you login into application.

**Comment by sachoosaini** [comment]
@ylecollen  anything for this ?
