### ISSUE TITLE
Riot doesn't handle volume settings properly

### ISSUE THREAD

**Issue by jgeysens** [vector-im/riot-android#783]
After using Riot for a video/voice call, it keeps hostage of the volume control when running in the background.   For example : when playing music using google play (on the phone and/or bluetooth), using the physical volume buttons will change the phone in-call volume.

Android version : 6.0.1
Riot version : 0.6.4 (and older versions)

**Comment by ylecollen** [comment]
Which device and which android version ?

**Comment by jgeysens** [comment]
Thx. This happened on android 6.0.1 on a sony xperia z5 compact.
