### ISSUE TITLE
'Share to room' UI sucks

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-android#801]
The rooms are not sorted by tag so it's impossible to find the room I need. Then I tapped the wrong room by accident and that was embarrassing

**Comment by ylecollen** [comment]
They are sorted by the latest messages time.

It was planned to add a search box but we did not have time yet to do it.

**Comment by atreyas** [comment]
The fact that share pastes and sends URL without a confirmation is itself the issue. When sharing, paste the link on the chart bar and let users edit it for manual send.

**Comment by bricewge** [comment]
As @atreyas said, what is shared should be put in the "edit box" but not send out automatically, this is behavior of the current Google messaging app (SMS).

It would also be nice to have the [Direct Share](https://developer.android.com/about/versions/marshmallow/android-6.0.html#direct-share) capability to share directly to a room from the share menu, bypassing the choice of a room inside Riot.

**Comment by bmarty** [comment]
- @atreyas The text is now (and it's been a while) copied in the EditText and not sent automatically.
- @bricewge Direct share is now tracked by #1103 
- @richvdh Filtering of rooms is now tracked by #2859
