### ISSUE TITLE
URL previews!

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#805]

**Comment by anoadragon453** [comment]
Keep in mind attackers can use this to reveal user's device information and IP address if implemented incorrectly. 

http://rsmck.co.uk/blog/imessage-preview/

Essentially this is possible the request will just have to be made from the server itself, though if users don't want to reveal the fact they're running a Matrix server this may also be an issue.

**Comment by ara4n** [comment]
absolutely. this is already sorted out for riot-web; the spidering is all proxied via the homeserver precisely to stop IPs or device info leaking to the target website.  There's also a load of whitelisting/blacklisting config on the server to stop malicious stuff getting spidered.

**Comment by ara4n** [comment]
To be clear: Display inline previews for URLs in timeline (for parity with riot-web), using the API as per https://github.com/matrix-org/synapse/blob/develop/docs/url_previews.md#api

**Comment by Vetgans** [comment]
Is [Android app doesn't show pictures from RSS-bot](https://github.com/vector-im/riot-android/issues/1477) perhaps related to this issue?

**Comment by anoadragon453** [comment]
@Vetgans Probably, actually.
