### ISSUE TITLE
How can I translate the app?

### ISSUE THREAD

**Issue by sim6** [vector-im/riot-android#811]
I can see this PR https://github.com/vector-im/riot-android/pull/660 but it isn't merged.

Is this the proper way to add translations?

See also https://github.com/vector-im/riot-android/issues/759 and https://github.com/vector-im/riot-android/issues/763

**Comment by sim6** [comment]
See also #849

**Comment by NathanBeelen** [comment]
Is there any clarity about why the translations aren't merged?

**Comment by Matrixcoffee** [comment]
The project maintainers don’t seem to be taking translations at the moment.

https://matrix.to/#/#riot-android:matrix.org/%241487938480379751GMruq:matrix.org has the last word on it.

**Comment by ara4n** [comment]
The concern here is that we're worried about the overhead of maintaining the translations, ensuring that they're synced and of suitable quality, and updated for each new release (without slowing down the release process even further).

I suggest we merge and see how it works out in practice (subsequently backing out the translations if we can't do a good enough job of maintaining them).

Separately, we'll get an online translation tool setup to make contribution easier.

**Comment by slipeer** [comment]
It's a pity. As far as I can tell at the moment almost the entire interface can be localized (except some strings from matrix-sdk) and that would be enough for a comfortable customer use.

**Comment by ara4n** [comment]
as i said: "I suggest we merge and see how it works out in practice" :)

**Comment by slipeer** [comment]
@ara4n Thanks. I did not see your answer when I wrote my own. ;)

**Comment by Matrixcoffee** [comment]
@ara4n Thanks for dislodging the translation efforts, and offering clarity.

(In other news, this issue is related to #357.)

**Comment by slipeer** [comment]
I'll draw your attention to the fact that for complete localization, you also need to translate strings in [matrix-android-sdk](https://github.com/matrix-org/matrix-android-sdk/blob/master/matrix-sdk/src/main/res/values/strings.xml) project. Riot uses it.

**Comment by bmarty** [comment]
Translations are now managed with Weblate

**Comment by comradekingu** [comment]
(Which is to be found at https://translate.riot.im/projects/riot-android/ )
