### ISSUE TITLE
add the email notif deactivation setting on android

### ISSUE THREAD

**Issue by AmandineLP** [vector-im/riot-android#817]

**Comment by ylecollen** [comment]
You have to tap on the email cell to remove the email from the linked emails list.

**Comment by pafcu** [comment]
This doesn't actually solve the issue. You might want to keep you email (for e.g. password resets) but not getting notifications. It's also inconsistent with how it is handled in Riot-web.

**Comment by krombel** [comment]
@omni:matrix.org mentioned [here](https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%2415147713204790935zaBNc:matrix.org) that (s)he could not find the option to remove the email notification target so the only way (s)he saw was to remove the email completely (as it is doable in riot-web). 
This is bad as you are loosing the ability to reset your password as well...
