### ISSUE TITLE
Emoji and e2e interract badly

### ISSUE THREAD

**Issue by vberger** [vector-im/riot-android#824]
In an e2e room, when I send messages containing emojis from my android device, my friend with riot-ios cannot read them, and gets the "unable to decrypt" error.

I can perfectly read their messages with emojis sent from their ios device on my android device.

All messages can be read from riot-web.

Some emojis seems to still work, like :snowflake: don't cause the message to be undecipherable, but most (like :cat:) do.

**Comment by ylecollen** [comment]
I put P2 issue because it only happens with some emojis.

**Comment by vberger** [comment]
From a discussion I had yesterday on #e2e:matrix.org , it may be related to Unicode's Basic Multilingual Plane : emojis in the BMP are correctly encrypted/decrypted, but emojis that are not in it are not.

**Comment by richvdh** [comment]
@vberger's client seems to be encoding non-bmp characters as CESU-8 instead of UTF-8. Yay java. I think Yannick has a fix for this in progress anyway.

**Comment by richvdh** [comment]
> non-bmp characters as CESU-8 instead of UTF-8

well, it encodes all characters as CESU-8. But the two are the same for BMP characters.

**Comment by richvdh** [comment]
This probably affects devices running android 5 and earlier, ftr.

**Comment by ylecollen** [comment]
I don't reproduce this issue on an android 4.4.4 device with the google play version (0.6.5) and the current develop one.

vberger  : could you test the develop version ?

**Comment by vberger** [comment]
Looks like it is fixed with last develop.

**Comment by ylecollen** [comment]
Thank you
