### ISSUE TITLE
Add autocomplete nickname button

### ISSUE THREAD

**Issue by subiol** [vector-im/riot-android#825]
In the irc mobile apps, usually there is a button that acts like pressing "TAB" in the desktop, it autocompletes any nickname you have started typing. For example if there is someone in the room named "OscarPeterson" and you write "Osc" and press this button, it will automatically complete it to "OscarPeterson". In the riot desktop webapp pressing "TAB" even shows you a bigger list of options for autocomplete.

Can we get similar functionality in the Android app?

**Comment by ylecollen** [comment]
you can already long press on the avatar in the room page or select Mention in the member details page.

The main problem is the design : how could we replace the TAB button ? we don't have enough place to add a button.

**Comment by subiol** [comment]
I understand its tricky from a ui point of view. That said the options you mention are not equivalent since sometimes the person you want to mention does not have a comment in the screen so you can tap its nick and going to the list of users really breaks the flow. That is why tab functionality is so useful.

I'm not a ui guy so take this suggestions as you see fit. 1. Im guessing there is no way in Android to tell the onscreen keyboard you need the tab key displayed, because that would solve it. 2. Have the option of using the user icon that is at the left of the text input as tab key. I'd be more than happy with this solution, but I'm not sure how intuitive it is, so that is why I suggest having it as an option in settings you can activate.

**Comment by subiol** [comment]
This has been solved already so closing it.
