### ISSUE TITLE
Warn the user when a new develop version is pushed

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#84]
It should be improved when the application will be published in the Google play store.

The user will be warned that a new version is published.

**Comment by ylecollen** [comment]
we can use
http://matrix.org/jenkins/job/VectorAndroidDevelop/lastSuccessfulBuild/api/json

it returns the latest sucessfuly build version.

**Comment by bmarty** [comment]
New build from Jenkins are sent automatically to the Riot Android room
