### ISSUE TITLE
Voip: Video call automatically hung up by callee

### ISSUE THREAD

**Issue by jeangb** [vector-im/riot-android#846]
To reproduce:
- In a 1:1 room, e2e or not
- Launch a video voip room with device 1
- Accept video call with device 2

Callee device 2 is automatically hung up and a toaster "call answered elsewhere" appears.
Detected by test RiotE2eEncryptionTests.java/startVoiceAndVideoCallInEncryptedRoom().
Version 0.6.6-dev (66ba524)
![video call hung up by callee](https://cloud.githubusercontent.com/assets/22364949/21932208/b052e524-d99f-11e6-9171-faf567269085.png)

**Comment by ylecollen** [comment]
fixed with 
-> https://github.com/matrix-org/matrix-android-sdk/commit/61f6fd904c25be64ba7722511724a5af49d5135b
-> https://github.com/vector-im/riot-android/commit/7e7b3f9cbc05ef7035c0fedd71e1d337bf7303ec
