### ISSUE TITLE
Member details screen: difference Android/iOS when unknown member

### ISSUE THREAD

**Issue by sabrinaj** [vector-im/riot-android#847]
From the unified search screen, when we input a valid email and access the member details screen, Android UI has more elements than iOS UI:
- Status
- "Admin tools" option
- Devices list

Android:
![Android](https://cloud.githubusercontent.com/assets/8929916/21932380/9cf81624-d9a0-11e6-8af2-e273322391ad.png)

iOS:
![iOS](https://matrix.org/_matrix/media/v1/download/matrix.org/WiXOZQqQWCBbCSCRHQdwbROB)

**Comment by jeangb** [comment]
Validated in 0.6.8-dev (7261594)
