### ISSUE TITLE
The rooms list is corrupted 

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#857]
Reported by Ralith in riot-android.

https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$148470018025050atUZA:ralith.com

the android client is often getting in a weird state where it doesn't display the correct room name for some room in the room list and trying to open such a room does nothing

**Comment by ylecollen** [comment]
Some rooms messages lists have been lost whereas the dedicated room summaries exist.

The MXFileStore should check if the retrieved data are still consistent at launch.

**Comment by jeangb** [comment]
Validated in 0.6.9-dev (e34ca0b)
