### ISSUE TITLE
Unable to register account 'connection refused'.

### ISSUE THREAD

**Issue by roadkillazpartybird** [vector-im/riot-android#859]
Trying to register and try out RIOT on Android (CM13), it's not letting me register.

Unfortunately the error message floats and disappears after a while, making bug-reporting hard. xP

Unable to register: Network Error: Failed to connect to matrix.org ... something something ... connection refused.

**Comment by ylecollen** [comment]
Could you get the device logs ? 
Do you use your own home server ?

**Comment by roadkillazpartybird** [comment]
It was my firewall, ignore me i am a noob. :)
