### ISSUE TITLE
Image preview : add image edition before sending it.

### ISSUE THREAD

**Issue by nvbln** [vector-im/riot-android#860]
I think it is a good idea to show the user a preview of the full image before sending it. 
This way the user can be sure that the (s)he is sending the right image.
Optionally it would be possible to add some small features to edit the image, like cropping.

**Comment by Matrixcoffee** [comment]
Mmm, yes, the original Matrix Console app does this too.

**Comment by lieuwex** [comment]
WhatsApp does this really nicely, in my opinion.

**Comment by bmarty** [comment]
I close this issue, the PR #1742 is merged. Thanks @nvbln. All: feel free to open new issue (and PRs :)) to improve the media previewer
