### ISSUE TITLE
E2E: Stale device lists

### ISSUE THREAD

**Issue by pstn** [vector-im/riot-android#863]
I can't aknowledge some keys in my riot client, because the devices don't get listed.
The device information to messages from these devices show "unknown device".
I'm not sure because I don't have too many devices tested, but I think it occurs every time, the device ID starts with a non alphanum char.

**Comment by richvdh** [comment]
related to https://github.com/vector-im/riot-web/issues/2305. Dunno if we already have a riot-android bug to track this.

**Comment by richvdh** [comment]
@ylecollen are we using this as the "stale device lists" bug (ie vector-im/riot-web#2305) for android?

**Comment by ylecollen** [comment]
@richvdh : yes, let defines this issue as the android "stale device lists" bug .

**Comment by pstn** [comment]
So, can I do anything to help this. Any useful logs I could post? This issue is breaking my workflow.

**Comment by ylecollen** [comment]
fixed in version
https://github.com/vector-im/riot-android/commit/6c2e04a182f023401ca98169f13af5c432503805

**Comment by richvdh** [comment]
reopening this because I think the algorithm we implemented was bogus

**Comment by pstn** [comment]
Btw: The Bug I had was fixed but not in this commit. It had something to do with parsing of the key signature.

**Comment by richvdh** [comment]
we need port https://github.com/matrix-org/matrix-js-sdk/pull/425 here.

**Comment by ylecollen** [comment]
Theses both issues have been released  on Riot versions >= 0.6.10
