### ISSUE TITLE
Can't decrypt my own messages on the same device

### ISSUE THREAD

**Issue by ZerataX** [vector-im/riot-android#864]
This just happened once and was fixed after a restart anyways.
I was sending a message in #megolm:matrix.org with Fdroid v0.6.5 and as soon as the message arrived it was replaced with 
`** Unable to decrypt: Unable to decrypt **`

![fdroid](http://0x0.st/OZj.png)

Later I check this on my laptop:

`** Unable to decrypt: Error: Mismatched room_id for inbound group session (expected !LMVMezeTndRRtgLKCp:matrix.org, was !UCnwUWwIKhcpaPTHtR:sw1v.org) **`

![laptop](http://0x0.st/OZQ.png)

**Comment by ylecollen** [comment]
the only reason i could find out if that two sessions had the same identifiers.

On the version > 0.6.5, the olm lib did not use a secured random string generator (the previous one was based on rand() instead of SecureRandom) so it might generate several times the same string.

**Comment by richvdh** [comment]
I believe this was fixed in 0.6.7
