### ISSUE TITLE
strange contact search behavior

### ISSUE THREAD

**Issue by xavierle** [vector-im/riot-android#866]
comparing to matrix

with riot client
to start a chat  with another user i need to write the complete ID
@username:homeserve.org

on matrix consoler
to create a room with another user
usualy i just need to write the username and the user is found

even if riot is nicer it makes it a bit unuseful

email invitation is not very usable neither

when the user have registered with an email.
sometimes it is a bit easier to find it but not always

**Comment by xavierle** [comment]
i made a bit more testing about contact search

in fact once 2 contacts visited the same room the search can find them easily

but it seems there is no seach possibility by username on a same homeserver
the only way to discover new contact is by personnal email ....

this is strange as after 2 visitors are on the same room thant search is very easy

**Comment by xavierle** [comment]
when you are connected on the homerserver = testserver.org
and that you search for ther username : bob

i would suggest that the user @bob:testserver.org si found

**Comment by ylecollen** [comment]
duplicate of 876

**Comment by Matrixcoffee** [comment]
#876
