### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by tessgadwa** [vector-im/riot-android#867]
Resubmitted from [Riot-Web General UX Thread #2984](https://github.com/vector-im/riot-web/issues/2984)

> UX I would find super handy: being able to swipe left to right from within a convo to go back to my convo list.  I constantly try to do it and it just highlights whatever message I'm swiping over.

Submitted from [designUX](https://matrix.to/#/!blHeuKmYNNfIqDlWGO:matrix.org/$14848596183729477CGGUG:matrix.org)

**Comment by Matrixcoffee** [comment]
#527
