### ISSUE TITLE
Warn that logging out will lose E2E keys

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#869]
Once we have megolm export wired up, we should obviously prompt the user to export

**Comment by BuZZ-dEE** [comment]
Why the user needs to export the keys? Export is a useful feature, but why the app can't store it by itself?

**Comment by ylecollen** [comment]
it seems safer to let the user decides when he/she wants to backup his e2e keys.
Moreover, the backup is quite slow.

Moreover, any file downloaded by the application will be deleted if it uninstalls. The user must move the file in a dedicated directory.

**Comment by ylecollen** [comment]
![ikgvuybxqiioqsbbseefbtpm](https://cloud.githubusercontent.com/assets/8971031/23262572/7e10babc-f9db-11e6-8529-aae5314a17f3.jpeg)

**Comment by ylecollen** [comment]
Available on the develop branch
