### ISSUE TITLE
Bug report sends data without user consent

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-android#888]
Filing a bug report through the app menu results in a swath of data being dumped into a ZIP file and potentially shared with the public, which surprise me at least. I think the app should definitely inform the user about what it'll do and what data it will share, possibly even give choices.

**Comment by ylecollen** [comment]
There is no hidden information 
-> by email : you can edit the attachment and modify/remove it
-> you can also send a comment in the riot-android room or with github (as you did).

We don't hide what it is sent like it is done by other software like Windows.

**Comment by madduck** [comment]
While it is true that there is no "hidden information", the information sent is still quite extensive, including verbose logs, configuration, and possibly a screenshot.

The normal user is *not* given a chance to check this beforehand and might well leak data they don't 
want to share.

If a user chooses to share the bug report with a Matrix room, the Zip file is uploaded without further information about its contents, or another check.

If a user chooses to share the bug report through other means, they also do not have the option to inspect/edit the content, as can b e seen e.g. by the following screenshot of K9-Mail — the attachment is ready to go and it would require a savvy user to first save it to the filesystem for inspection and later sending.

![screenshot_20170125-195926](https://cloud.githubusercontent.com/assets/195073/22282421/0d9da3b8-e341-11e6-9047-32156d805b3b.png)

Please reopen this bug report and inform the user about which data are being shared. Then, give them a final summary of what's about to happen ("you are about to send the Zip file containing the aforementioned data to the Matrix room #riot:matrix.org, which may be public. Are you sure you want to do that?").

Thank you,
-m

**Comment by Matrixcoffee** [comment]
Related: #842

**Comment by ylecollen** [comment]
The bug report is now sent to a dedicated server.
You have choice to add the logs.
