### ISSUE TITLE
Infinite contacts permission request dialog if it is rejected

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#891]
Steps to reproduce
-> Make a fresh install on an android >= 6.0 device
-> Start room creation or try to add a new user to an existing room
-> The contacts permission should be displayed : reject the permission

The permission dialog is displayed in loop.

**Comment by sabrinaj** [comment]
Fixed with commit https://github.com/vector-im/riot-android/commit/9948ad0fc228d5edeabb0548b4cdca939166f92d
