### ISSUE TITLE
Encryptation is broken after reinstallation

### ISSUE THREAD

**Issue by sim6** [vector-im/riot-android#895]
If we turn on room encryptation it works but after reinstall Riot doesn't work.

If we remove the old devices from device list of settings then it works again.

**Comment by ylecollen** [comment]
When you say reinstall, i assume you mean application update.

Did you get an alert dialog after the update ?
I fixed a backward compatibility issue this morning but it concerns the version < 0.6.4.
From which version did you update ?

**Comment by ylecollen** [comment]
Notice that the latest develop version supports the e2e keys import if something was broken.
i.e you can import your webclient e2e keys into the android client.

**Comment by ylecollen** [comment]
Should be fixed with 
https://github.com/vector-im/riot-android/commit/6c2e04a182f023401ca98169f13af5c432503805
