### ISSUE TITLE
Answering call in different device triggers infinite ringing

### ISSUE THREAD

**Issue by IvanSanchez** [vector-im/riot-android#921]
I run Riot on desktop and phone at the same time.

If:

* I have riot-android on the foreground in the phone, and
* I have riot-electron on the foreground in the desktop computer, and
* Somebody starts a call / video call with me, and
* I let it ring a couple of times in each device, and
* I answer the call in the desktop computer,

Then:

* riot-android will be stuck in a ringing loop, with no way to turn the ringing off.

I reproduced this once with 0.6.4 I think. I'm not really willing to test if this is reproducible, due to the annoyance of having to reset the phone after riot is stuck in the ringing loop.

**Comment by ylecollen** [comment]
IvanSanchez
Your issue should be fixed on the latest version.
Richvdh sent us a useful bug report which helped us to fix this annoying issue.

Could you test with the latest version ?

**Comment by IvanSanchez** [comment]
I see this might be a duplicate of #784. I'll try to see if it's reproducible later.

**Comment by ylecollen** [comment]
Duplicate #784.

**Comment by IvanSanchez** [comment]
Hmm, I forgot to properly test this. For what it's worth, I didn't experience this bug in the last few weeks.
