### ISSUE TITLE
Ask "Camera" permission for updating the profile picture. 

### ISSUE THREAD

**Issue by arsadeghi** [vector-im/riot-android#935]
If the Camera permission is not granted (which is the default case), after clicking on the profile icon to update the picture, the camera would not be turned on (see the gif below). 

@ylecollen  IMHO, the APIs for checking(checkSelfPermission)/asking(requestPermissions) CAMERA permission should get called after clicking on the profile icon.

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/11197005/22846060/8ed2478a-ef9a-11e6-96c9-96b986fd20fc.gif)

**Comment by 4311021x** [comment]
Now I see why the voice call from iOS to Android only resulted in a black image 😃

**Comment by arsadeghi** [comment]
Actually, this problem only happens in Android >= 6. In Android 5 and below, the Camera as well as other permissions are automatically granted at the installation time.
