### ISSUE TITLE
Usability: The compose window activation area is deceptively small

### ISSUE THREAD

**Issue by smkent** [vector-im/riot-android#941]
When a user taps to start writing a new message in the chat view, there is only a very small area that activates the message compose function. I have highlighted the approximate area a user can tap in red:

![riot_hitbox_2](https://cloud.githubusercontent.com/assets/2831985/22920975/9e1aea58-f24c-11e6-8a27-5f095623d89d.png)

Based on the UI, I would expect to be able to activate the message compose function by tapping anywhere around the "Type a message" line on the bottom panel, but tapping above/below the "Type a message" text on that panel does nothing. I highlighted the expected area that should activate the message compose function in blue:

![riot_hitbox_3](https://cloud.githubusercontent.com/assets/2831985/22921161/5dcde0e4-f24d-11e6-9000-3bd3548c4181.png)

Compare this with the Google Hangouts Android app. Tapping anywhere in the bottom panel around the compose text (area highlighted in red) activates the message compose function, as one would expect:

![hangouts_hitbox_2](https://cloud.githubusercontent.com/assets/2831985/22921190/7f235a3a-f24d-11e6-91f9-dab2ae8bfd81.png)

This is a significant usability problem. The first few times I used the Riot app, I thought the message compose activation was unreliable until I figured out that the activation area is just very small.

**Comment by jeangb** [comment]
Validated in 0.6.9-dev (e34ca0b)
