### ISSUE TITLE
Unable to rename device name

### ISSUE THREAD

**Issue by tchncs** [vector-im/riot-android#944]
While i can rename my devices in riot-desktop so far, i only can tab at the name in riot-android. Nothing happens.

**Comment by ylecollen** [comment]
Which version are you using ?

**Comment by tchncs** [comment]
`0.6.8 (FDroid-8f1140d)`

**Comment by ylecollen** [comment]
it has been added in the develop branch. (and it will be available with the next release).

http://matrix.org/jenkins/job/VectorAndroidDevelop/lastSuccessfulBuild/artifact/vector/build/outputs/apk/vector-appfdroid-debug.apk if you want to test it

**Comment by tchncs** [comment]
Oh that's great news, thanks!
