### ISSUE TITLE
Search in "Room directory" confusing when you press return

### ISSUE THREAD

**Issue by frabcus** [vector-im/riot-android#946]
I was trying to search the Room directory (in the Linux desktop app).

I type fast and instinctively press Return. This meant it tried to go to a room with the name of what I'm typing, and gave the message "You are trying to access a room.
Click here to join the discussion!".

I assumed this wasn't a search field after all, but a "go to specific named room" field

Instead, it turns out (and I only found out by asking someone else) I have to type and *wait* and that does a search as expected.

Some ideas:
1) Make it clearer it is search, perhaps with a magnifying glass button?
2) If e.g. I type "django" and press return, as well as showing a link at the top to join or make a room, it could conduct the search as well below.

**Comment by sabrinaj** [comment]
@frabcus This is the repository of the Android app. Please report your issues about the web client at https://github.com/vector-im/riot-web/issues. Thank you.
