### ISSUE TITLE
Hard to find the "Room directory" button

### ISSUE THREAD

**Issue by frabcus** [vector-im/riot-android#947]
When I first used Riot, I went straight into a room.

Then I couldn't work out how to get back out!

It took ages of exploring every button to find the tiny folder icon. The four icons down there are very small and cryptic for primary interface.

Some suggestions:

1) Put the "Room directory" command at the top of the list of rooms in the very visible sidebar above.
2) I guess then the "Create new room" could go in the same place. And "Start chat" in the section for "People".
3) Make all those icons a bit larger and clearer, preferably with text not just icons.

**Comment by sabrinaj** [comment]
@frabcus This is the repository of the Android app. Please report your issues about the web client at https://github.com/vector-im/riot-web/issues. Thank you.

**Comment by frabcus** [comment]
Sorry @sabrinaj! Am checking the correct issue tracker, and making appropriate reports.
