### ISSUE TITLE
e2e and auth keys should be blacklisted from google backup somehow

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#949]
see https://twitter.com/kyhwana/status/831634266576400385

**Comment by kyhwana** [comment]
I had previously enabled the Google backup/restore feature on my Nexus 5X and then factory wiped my Nexus 7. Upon restoring using my google account to the Nexus 7, the Riot app was restored and contained the the auth token + config for my home server as well as the E2E keys/fingerprint from my Nexus 7. There was no new device added to my device list.

**Comment by kyhwana** [comment]
Looks like android:allowBackup="true" in the androidmanifest.xml is enabling the backup.
And the E2E keys/login information is stored via SharedPreferences, which isn't being excluded from the backup specifically?

**Comment by TheLastProject** [comment]
Enhancement? Priority 2? Could you at very least disable allowBackup for the time being then? Because we're talking about **leaking private keys** which is literally one of the most serious security vulnerabilities you can have.

**Comment by richvdh** [comment]
@ylecollen: this is a security bug

**Comment by TheLastProject** [comment]
The easy fix, until someone takes the time to exclude the proper directories (which should be both the E2E encrypted keys and the chats, to prevent Google from getting a plain text copy of encrypted chats), would be to just set `android:allowBackup` to `false` in `vector/src/app/AndroidManifest.xml` and `vector/src/main/AndroidManifest.xml`.

I was creating a pull request despite the simplicity, but upon looking around more I realized I don't know enough of your build process to know what `vector/src/appfdroid/AndroidManifest.xml` is for exactly (aside that it builds for F-Droid).

It looks like `vector/src/app/AndroidManifest.xml` overwrites `vector/src/main/AndroidManifest.xml` and thus `vector/src/appfdroid/AndroidManifest.xml` should simply inherit the value from `vector/src/main/AndroidManifest.xml` but I cannot be sure as I do not know your build process. While many F-Droid users don't use Google Play Services, there are still enough that do, so care should be taken the F-Droid build does correctly set `android:allowBackup` to 'false` as well with the suggested change.

**Comment by ylecollen** [comment]
I set android:allowBackup to false.

**Comment by ylecollen** [comment]
http://androiddoc.qiniudn.com/training/backup/autosyncapi.html

We cannot exclude some dedicated directories/files because they are not hard coded.
The path depends in the user Id.
The application does not how the matrix SDK manages its data (and it might change)
