### ISSUE TITLE
New Rageshake: no feedback or progress indication at all

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#955]
Sending a bug report/rageshake via the new http API gives absolutely zero feedback. No info about:
1. transfer started successfully
2. transfer progress
3. upload completed successfully

**Comment by ylecollen** [comment]
![bug_report](https://cloud.githubusercontent.com/assets/8971031/23129484/25f30cc2-f783-11e6-9768-cd486389446b.jpeg)
