### ISSUE TITLE
Voice Calling turns off screen erroneously

### ISSUE THREAD

**Issue by waiyd** [vector-im/riot-android#957]
The voice call feature is intended to blacken the screen when the user is in-call via use of the ambient light sensor (e.g. if the phone is against the user's ear, the screen won't needlessly be on).

However it does this erroneously when the user has a call going on in the background, and may incidentally cover their ambient light sensor. This behavior continues after the user has left the call for a short amount of time. 

This should be fixed so that the screen is only automatically turned off when the user has the in-call screen open.

**Comment by ylecollen** [comment]
waiyd 

Which device do you have ?

**Comment by waiyd** [comment]
Galaxy S7 Edge on Marshmallow

Version 0.6.8
