### ISSUE TITLE
Bug Report: Progress bar is not visible if there is a lot of text

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#973]
And the window contents can't be scrolled.

![jjlvdmuwphbsvwcgrzbgnqjl](https://cloud.githubusercontent.com/assets/21172059/23311204/28343cea-faad-11e6-86d0-0cf0ac764a6d.jpeg)

**Comment by jeangb** [comment]
Validated in 0.6.9-dev (669ec70)
