### ISSUE TITLE
Support showing custom tags

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-android#988]
The [tags api](http://matrix.org/docs/spec/client_server/r0.2.0.html#room-tagging) allows users to tag rooms to better organize their room list. I'm pretty sure none of the Riot clients allow you to set these tags, but the tags can still be set through the API (via curl, for example).

Riot-web handles the tags nicely by just adding more groups on the side. Android however just mushes them together under 'Rooms', leaving a mess of rooms. It would be nice if the Android client at least supported the organization of the rooms and the UI to tag them coming at a later time.

**Comment by sabrinaj** [comment]
We have a meta ticket for this so I close this one.

See https://github.com/vector-im/riot-meta/issues/11
