### ISSUE TITLE
it sometimes takes several presses of the send button to get the message out

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-android#989]
Sometimes tapping on the send button doesn't do anything. Coffee says: 'It's not a mistap because I get the usual audible feedback on tapping. Just... nothing happens.'

**Comment by Matrixcoffee** [comment]
I still reproduce this on build 1086 (699ec70). There doesn't seem to be any change in behaviour.

**Comment by ylecollen** [comment]
There is a waiting PR.
https://github.com/vector-im/riot-android/pull/990
