### ISSUE TITLE
Dark theme and per-room color scheming support

### ISSUE THREAD

**Issue by bernedef** [vector-im/riot-android#992]
Some weeks ago, dark theme support has been added to Riot-Web (https://github.com/vector-im/riot-web/pull/2973). Riot-Android seems to be "stuck" to the Android light theme (Theme.AppCompat.Light) due to, among other things, some hard-coded color values.

Can we expect to have a dark theme of Riot-Android in the future?

Moreover, Riot-Web also supports per-room color scheming for a long time. These settings appear to be saved and retrieved per user and per room using this endpoint provided by the Matrix homeserver: /user/$userId/rooms/$roomId/account_data/org.matrix.room.color_scheme (https://github.com/matrix-org/matrix-react-sdk/commit/ef00a1624d34604e6883e8a20b9da26a51efc5fb and https://github.com/matrix-org/matrix-react-sdk/commit/3934b42ac88e975823b9bed5b3e46239d67ba1b4).

Can we expect to have per-room color scheming support in Riot-Android in the future?

**Comment by ylecollen** [comment]
The features will come later.
